//
//  QualityProfile.swift
//  Wallpaper
//
//  Quality profile configuration (resolution, frame rate).
//
//  Created by Jake Bromberg on 01/05/26.
//  Copyright © 2026 WXYC. All rights reserved.
//

import Foundation

/// A fixed quality profile that overrides adaptive thermal optimization.
///
/// Use this to specify fixed wallpaper FPS, scale, and LOD values for specific rendering contexts,
/// such as the wallpaper picker where lower quality is acceptable to reduce GPU load.
public struct QualityProfile: Equatable, Sendable {
    /// Target wallpaper frames per second (display rate).
    public let wallpaperFPS: Float

    /// Render scale factor (0.5 to 1.0).
    public let scale: Float

    /// Shader level of detail (0.0 to 1.0).
    public let lod: Float

    /// Whether frame interpolation is enabled.
    ///
    /// When enabled, the shader executes at `shaderFPS` while the display runs
    /// at `wallpaperFPS`, with intermediate frames generated by blending.
    public let interpolationEnabled: Bool

    /// The FPS at which the shader actually executes when interpolation is enabled.
    ///
    /// Display FPS (`wallpaperFPS`) is achieved by blending between shader frames.
    /// When `interpolationEnabled` is false, this equals `wallpaperFPS`.
    public let shaderFPS: Float

    /// Creates a quality profile with specified wallpaper FPS, scale, LOD, and interpolation settings.
    ///
    /// - Parameters:
    ///   - wallpaperFPS: Target display frames per second (clamped to 15-60).
    ///   - scale: Render scale factor (clamped to 0.5-1.0).
    ///   - lod: Shader level of detail (clamped to 0.0-1.0, default 1.0).
    ///   - interpolationEnabled: Whether to use frame interpolation (default false).
    ///   - shaderFPS: FPS for shader execution when interpolating (default: half of wallpaperFPS).
    public init(
        wallpaperFPS: Float,
        scale: Float,
        lod: Float = 1.0,
        interpolationEnabled: Bool = false,
        shaderFPS: Float? = nil
    ) {
        self.wallpaperFPS = wallpaperFPS.clamped(to: AdaptiveProfile.wallpaperFPSRange)
        self.scale = scale.clamped(to: AdaptiveProfile.scaleRange)
        self.lod = lod.clamped(to: AdaptiveProfile.lodRange)
        self.interpolationEnabled = interpolationEnabled
        // Default shader FPS to half of display FPS when interpolating
        let defaultShaderFPS = interpolationEnabled ? wallpaperFPS / 2 : wallpaperFPS
        self.shaderFPS = (shaderFPS ?? defaultShaderFPS).clamped(to: AdaptiveProfile.wallpaperFPSRange)
    }

    /// Quality profile for wallpaper picker cards (30 FPS, 0.75 scale, 0.5 LOD).
    public static let picker = QualityProfile(wallpaperFPS: 30, scale: 0.75, lod: 0.5)
}
