//
// AddAlbumRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddAlbumRequest: Sendable, Codable, Hashable {

    public var albumTitle: String
    public var artistName: String?
    public var artistId: Int?
    public var label: String
    public var labelId: Int?
    public var genreId: Int
    public var formatId: Int
    public var discQuantity: Int?
    public var alternateArtistName: String?
    public var albumArtist: String?

    public init(albumTitle: String, artistName: String? = nil, artistId: Int? = nil, label: String, labelId: Int? = nil, genreId: Int, formatId: Int, discQuantity: Int? = nil, alternateArtistName: String? = nil, albumArtist: String? = nil) {
        self.albumTitle = albumTitle
        self.artistName = artistName
        self.artistId = artistId
        self.label = label
        self.labelId = labelId
        self.genreId = genreId
        self.formatId = formatId
        self.discQuantity = discQuantity
        self.alternateArtistName = alternateArtistName
        self.albumArtist = albumArtist
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albumTitle = "album_title"
        case artistName = "artist_name"
        case artistId = "artist_id"
        case label
        case labelId = "label_id"
        case genreId = "genre_id"
        case formatId = "format_id"
        case discQuantity = "disc_quantity"
        case alternateArtistName = "alternate_artist_name"
        case albumArtist = "album_artist"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(albumTitle, forKey: .albumTitle)
        try container.encodeIfPresent(artistName, forKey: .artistName)
        try container.encodeIfPresent(artistId, forKey: .artistId)
        try container.encode(label, forKey: .label)
        try container.encodeIfPresent(labelId, forKey: .labelId)
        try container.encode(genreId, forKey: .genreId)
        try container.encode(formatId, forKey: .formatId)
        try container.encodeIfPresent(discQuantity, forKey: .discQuantity)
        try container.encodeIfPresent(alternateArtistName, forKey: .alternateArtistName)
        try container.encodeIfPresent(albumArtist, forKey: .albumArtist)
    }
}

