//
// AddRotationCardRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddRotationCardRequest: Sendable, Codable, Hashable {

    public var bin: RotationBin
    public var name: String?

    public init(bin: RotationBin, name: String? = nil) {
        self.bin = bin
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bin
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bin, forKey: .bin)
        try container.encodeIfPresent(name, forKey: .name)
    }
}


extension AddRotationCardRequest: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if bin == .unknownDefaultOpenApi { return true }
        return false
    }
}
