//
// AddToBinRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddToBinRequest: Sendable, Codable, Hashable {

    public var albumId: Int

    public init(albumId: Int) {
        self.albumId = albumId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albumId = "album_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(albumId, forKey: .albumId)
    }
}

