//
// AlbumSearchResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlbumSearchResult: Sendable, Codable, Hashable {

    public var id: Int
    public var addDate: Date
    public var albumTitle: String
    public var artistName: String
    public var codeLetters: String
    public var codeNumber: Int
    public var codeArtistNumber: Int
    public var formatName: String
    public var genreName: String
    public var label: String
    public var labelId: Int?
    public var albumDist: Double?
    public var artistDist: Double?
    public var rotationBin: RotationBin?
    public var rotationId: Int?
    public var plays: Int?
    /** True if this release is available on at least one streaming service. False means only available in the WXYC physical library. Null if unknown. */
    public var onStreaming: Bool?
    /** Credited album artist for compilations. */
    public var albumArtist: String?
    /** When the release was marked missing from the physical library. Null if in library. */
    public var dateLost: Date?
    /** When a previously missing release was found. Null if never lost. */
    public var dateFound: Date?
    /** Album cover artwork URL from Discogs. Null if artwork has not been fetched yet or is unavailable. */
    public var artworkUrl: String?
    /** Populated by Backend's catalog `/library/` search when a track-title match (CTA or LML proxy fallback) drove this release into the results, per catalog-track-search plan §5.1. Empty or absent on normal artist/album hits. Backward-compatible — existing consumers ignore the field.  */
    public var matchedVia: [TrackMatchHint]?
    /** Populated by Backend's catalog search when an artist-alias match (from `artist_search_alias`) drove this release into the results, per artist-search-alias plan PR 5. Sibling field to `matched_via` (which is track-title provenance). Empty or absent on normal artist/album hits. Backward-compatible — existing consumers ignore the field.  */
    public var matchedViaAlias: [ArtistMatchHint]?

    public init(id: Int, addDate: Date, albumTitle: String, artistName: String, codeLetters: String, codeNumber: Int, codeArtistNumber: Int, formatName: String, genreName: String, label: String, labelId: Int? = nil, albumDist: Double? = nil, artistDist: Double? = nil, rotationBin: RotationBin? = nil, rotationId: Int? = nil, plays: Int? = nil, onStreaming: Bool? = nil, albumArtist: String? = nil, dateLost: Date? = nil, dateFound: Date? = nil, artworkUrl: String? = nil, matchedVia: [TrackMatchHint]? = nil, matchedViaAlias: [ArtistMatchHint]? = nil) {
        self.id = id
        self.addDate = addDate
        self.albumTitle = albumTitle
        self.artistName = artistName
        self.codeLetters = codeLetters
        self.codeNumber = codeNumber
        self.codeArtistNumber = codeArtistNumber
        self.formatName = formatName
        self.genreName = genreName
        self.label = label
        self.labelId = labelId
        self.albumDist = albumDist
        self.artistDist = artistDist
        self.rotationBin = rotationBin
        self.rotationId = rotationId
        self.plays = plays
        self.onStreaming = onStreaming
        self.albumArtist = albumArtist
        self.dateLost = dateLost
        self.dateFound = dateFound
        self.artworkUrl = artworkUrl
        self.matchedVia = matchedVia
        self.matchedViaAlias = matchedViaAlias
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case addDate = "add_date"
        case albumTitle = "album_title"
        case artistName = "artist_name"
        case codeLetters = "code_letters"
        case codeNumber = "code_number"
        case codeArtistNumber = "code_artist_number"
        case formatName = "format_name"
        case genreName = "genre_name"
        case label
        case labelId = "label_id"
        case albumDist = "album_dist"
        case artistDist = "artist_dist"
        case rotationBin = "rotation_bin"
        case rotationId = "rotation_id"
        case plays
        case onStreaming = "on_streaming"
        case albumArtist = "album_artist"
        case dateLost = "date_lost"
        case dateFound = "date_found"
        case artworkUrl = "artwork_url"
        case matchedVia = "matched_via"
        case matchedViaAlias = "matched_via_alias"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(addDate, forKey: .addDate)
        try container.encode(albumTitle, forKey: .albumTitle)
        try container.encode(artistName, forKey: .artistName)
        try container.encode(codeLetters, forKey: .codeLetters)
        try container.encode(codeNumber, forKey: .codeNumber)
        try container.encode(codeArtistNumber, forKey: .codeArtistNumber)
        try container.encode(formatName, forKey: .formatName)
        try container.encode(genreName, forKey: .genreName)
        try container.encode(label, forKey: .label)
        try container.encodeIfPresent(labelId, forKey: .labelId)
        try container.encodeIfPresent(albumDist, forKey: .albumDist)
        try container.encodeIfPresent(artistDist, forKey: .artistDist)
        try container.encodeIfPresent(rotationBin, forKey: .rotationBin)
        try container.encodeIfPresent(rotationId, forKey: .rotationId)
        try container.encodeIfPresent(plays, forKey: .plays)
        try container.encodeIfPresent(onStreaming, forKey: .onStreaming)
        try container.encodeIfPresent(albumArtist, forKey: .albumArtist)
        try container.encodeIfPresent(dateLost, forKey: .dateLost)
        try container.encodeIfPresent(dateFound, forKey: .dateFound)
        try container.encodeIfPresent(artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(matchedVia, forKey: .matchedVia)
        try container.encodeIfPresent(matchedViaAlias, forKey: .matchedViaAlias)
    }
}


extension AlbumSearchResult: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if rotationBin == .unknownDefaultOpenApi { return true }
        return false
    }
}
