//
// AlbumInfoResponseAllOfRotation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlbumInfoResponseAllOfRotation: Sendable, Codable, Hashable {

    public var id: Int?
    public var rotationBin: RotationBin?
    public var addDate: Date?
    public var killDate: Date?

    public init(id: Int? = nil, rotationBin: RotationBin? = nil, addDate: Date? = nil, killDate: Date? = nil) {
        self.id = id
        self.rotationBin = rotationBin
        self.addDate = addDate
        self.killDate = killDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case rotationBin = "rotation_bin"
        case addDate = "add_date"
        case killDate = "kill_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(rotationBin, forKey: .rotationBin)
        try container.encodeIfPresent(addDate, forKey: .addDate)
        try container.encodeIfPresent(killDate, forKey: .killDate)
    }
}


extension AlbumInfoResponseAllOfRotation: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if rotationBin == .unknownDefaultOpenApi { return true }
        return false
    }
}
