//
// AlbumUrlsUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Replace-wholesale set of a catalogued release&#39;s definitive external links — the request body of &#x60;PUT /library/{id}/urls&#x60;. The &#x60;urls&#x60; array REPLACES whatever links the release currently has; position IS the contract (storage order), an empty array clears them, and there is no partial/merge form. This is the release-scoped write that stands alone from a rotation add: &#x60;RotationCreateFields.urls&#x60; already carries links on the filings/rotation-add path (Backend persists those release-scoped for the catalogued arm), while this sets them independent of any rotation stint (BS#2491). Same one &#x60;urls&#x60; vocabulary as the read shapes (&#x60;AlbumSearchResult&#x60;/&#x60;AlbumDetail&#x60;) and &#x60;RotationCreateFields.urls&#x60;.  */
public struct AlbumUrlsUpdate: Sendable, Codable, Hashable {

    public static let urlsRule = ArrayRule(minItems: nil, maxItems: 20, uniqueItems: false)
    /** The links to store for this release, in the order they should be displayed. Plain strings, not `format: uri` — MDs paste bare domains, so a value carries no scheme guarantee and a renderer must not bind one into an href without checking it. An empty array clears the release's links. Bounded at 20 links of 2048 characters each — identical to the read shapes and `RotationCreateFields.urls` — and the bounds ship with the field because oasdiff treats adding a request-side bound later as a breaking change.  */
    public var urls: [String]

    public init(urls: [String]) {
        self.urls = urls
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case urls
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(urls, forKey: .urls)
    }
}

