//
// AlbumMetadataResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlbumMetadataResponse: Sendable, Codable, Hashable {

    /** Discogs release ID */
    public var discogsReleaseId: Int?
    /** Discogs release page URL */
    public var discogsUrl: String?
    /** Release year from Discogs */
    public var releaseYear: Int?
    /** Album artwork image URL */
    public var artworkUrl: String?
    /** Discogs genre classifications */
    public var genres: [String]?
    /** Discogs style classifications (more specific than genres) */
    public var styles: [String]?
    /** Primary record label name */
    public var label: String?
    /** Discogs artist ID, for linking to artist metadata */
    public var discogsArtistId: Int?
    /** Full release date when available (e.g. \"2024-03-15\") */
    public var fullReleaseDate: String?
    /** Release tracklist */
    public var tracklist: [TrackListItem]?
    /** Attributed external critic-review snippets, each linking out to the original */
    public var criticReviews: [CriticReviewItem]?
    /** Consented WXYC DJ album reviews (social_consent = true) for this album. Reviewer identity is never included. */
    public var wxycReviews: [WxycReviewItem]?
    /** Spotify URL for the album or track */
    public var spotifyUrl: String?
    /** Apple Music URL for the album or track */
    public var appleMusicUrl: String?
    /** YouTube Music search URL */
    public var youtubeMusicUrl: String?
    /** Bandcamp search URL */
    public var bandcampUrl: String?
    /** SoundCloud search URL */
    public var soundcloudUrl: String?
    /** True when a music director has marked this release as not on Discogs; downstream render surfaces should suppress Discogs-derived artwork/links/tracklist. Mirrors the `Album` schema's MD-set marker (WXYC/wiki plans/rotation-discogs-unavailable.md). */
    public var discogsUnavailable: Bool?
    /** Optional free-text reason for `discogsUnavailable`. */
    public var discogsUnavailableNote: String?

    public init(discogsReleaseId: Int? = nil, discogsUrl: String? = nil, releaseYear: Int? = nil, artworkUrl: String? = nil, genres: [String]? = nil, styles: [String]? = nil, label: String? = nil, discogsArtistId: Int? = nil, fullReleaseDate: String? = nil, tracklist: [TrackListItem]? = nil, criticReviews: [CriticReviewItem]? = nil, wxycReviews: [WxycReviewItem]? = nil, spotifyUrl: String? = nil, appleMusicUrl: String? = nil, youtubeMusicUrl: String? = nil, bandcampUrl: String? = nil, soundcloudUrl: String? = nil, discogsUnavailable: Bool? = nil, discogsUnavailableNote: String? = nil) {
        self.discogsReleaseId = discogsReleaseId
        self.discogsUrl = discogsUrl
        self.releaseYear = releaseYear
        self.artworkUrl = artworkUrl
        self.genres = genres
        self.styles = styles
        self.label = label
        self.discogsArtistId = discogsArtistId
        self.fullReleaseDate = fullReleaseDate
        self.tracklist = tracklist
        self.criticReviews = criticReviews
        self.wxycReviews = wxycReviews
        self.spotifyUrl = spotifyUrl
        self.appleMusicUrl = appleMusicUrl
        self.youtubeMusicUrl = youtubeMusicUrl
        self.bandcampUrl = bandcampUrl
        self.soundcloudUrl = soundcloudUrl
        self.discogsUnavailable = discogsUnavailable
        self.discogsUnavailableNote = discogsUnavailableNote
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case discogsReleaseId
        case discogsUrl
        case releaseYear
        case artworkUrl
        case genres
        case styles
        case label
        case discogsArtistId
        case fullReleaseDate
        case tracklist
        case criticReviews
        case wxycReviews
        case spotifyUrl
        case appleMusicUrl
        case youtubeMusicUrl
        case bandcampUrl
        case soundcloudUrl
        case discogsUnavailable
        case discogsUnavailableNote
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(discogsReleaseId, forKey: .discogsReleaseId)
        try container.encodeIfPresent(discogsUrl, forKey: .discogsUrl)
        try container.encodeIfPresent(releaseYear, forKey: .releaseYear)
        try container.encodeIfPresent(artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(genres, forKey: .genres)
        try container.encodeIfPresent(styles, forKey: .styles)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(discogsArtistId, forKey: .discogsArtistId)
        try container.encodeIfPresent(fullReleaseDate, forKey: .fullReleaseDate)
        try container.encodeIfPresent(tracklist, forKey: .tracklist)
        try container.encodeIfPresent(criticReviews, forKey: .criticReviews)
        try container.encodeIfPresent(wxycReviews, forKey: .wxycReviews)
        try container.encodeIfPresent(spotifyUrl, forKey: .spotifyUrl)
        try container.encodeIfPresent(appleMusicUrl, forKey: .appleMusicUrl)
        try container.encodeIfPresent(youtubeMusicUrl, forKey: .youtubeMusicUrl)
        try container.encodeIfPresent(bandcampUrl, forKey: .bandcampUrl)
        try container.encodeIfPresent(soundcloudUrl, forKey: .soundcloudUrl)
        try container.encodeIfPresent(discogsUnavailable, forKey: .discogsUnavailable)
        try container.encodeIfPresent(discogsUnavailableNote, forKey: .discogsUnavailableNote)
    }
}

