//
// AlbumDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The album-detail response: one &#x60;wxyc_schema.library&#x60; row plus its artist / format / genre joins, as &#x60;getAlbumFromDB&#x60; projects it. FOUR operations return exactly this shape — &#x60;GET /library/info&#x60; (both its &#x60;album_id&#x60; and its &#x60;legacy_release_id&#x60; branch), &#x60;PATCH /library/{id}&#x60;, &#x60;PATCH /library/{id}/missing&#x60;, and &#x60;PATCH /library/{id}/found&#x60;. The three PATCHes re-read through &#x60;getAlbumFromDB&#x60; after their write, so there is one shape here, not two. They previously pointed at &#x60;AlbumSearchResult&#x60; (#365), which declares seven search-only properties no album-detail handler emits (&#x60;album_dist&#x60;, &#x60;artist_dist&#x60;, &#x60;rotation_bin&#x60;, &#x60;rotation_id&#x60;, &#x60;artwork_url&#x60;, &#x60;matched_via&#x60;, &#x60;matched_via_alias&#x60;) — do not re-point a detail operation at it. Named for the shape, not for one endpoint: this was &#x60;AlbumInfoResponse&#x60;, which read as \&quot;the &#x60;/library/info&#x60; response\&quot; while serving four. Deliberately FLAT rather than &#x60;allOf: [Album, …]&#x60;, though it began that way and every property below &#x60;format_id&#x60; is also on &#x60;Album&#x60;. Two reasons. The differ compares &#x60;allOf&#x60; branches one at a time, so re-pointing the three PATCHes here from the flat &#x60;AlbumSearchResult&#x60; read as \&quot;removed ten required properties\&quot; three times over and reddened the breaking-change gate for a change that removes nothing. And the composition was only half true: &#x60;Album&#x60; is the RAW inserted row &#x60;POST /library&#x60; returns — snake_case &#x60;discogs_unavailable&#x60;, no joins, no &#x60;reconciled_identity&#x60; — while this is the serialized, joined read shape. Sharing a base implied an equivalence the two do not have (see WXYC/Backend-Service#2216).  */
public struct AlbumDetail: Sendable, Codable, Hashable {

    public static let discogsUnavailableNoteRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    public static let urlsRule = ArrayRule(minItems: nil, maxItems: 20, uniqueItems: false)
    /** Backend's serial `wxyc_schema.library.id`. */
    public var id: Int
    public var artistId: Int
    public var albumTitle: String
    public var codeNumber: Int
    public var genreId: Int
    public var formatId: Int
    /** `library.label`. Nullable in the database; the key is always present because the projection always selects it.  */
    public var label: String?
    /** The SAME column as `label` — `getAlbumFromDB` projects `library.label` twice, under both names, so both are always present and always equal. Prefer `label`; `record_label` is retained because consumers read it (#373).  */
    public var recordLabel: String?
    public var labelId: Int?
    public var addDate: Date
    public var discQuantity: Int?
    public var alternateArtistName: String?
    /** Credited album artist for compilations (e.g., \"Kruder & Dorfmeister\" on a DJ-Kicks release filed under Various Artists). */
    public var albumArtist: String?
    /** Joined from `artists.artist_name`. */
    public var artistName: String
    /** Joined from `artists.alphabetical_name` — the filing form (\"Beatles, The\"), used for shelf order.  */
    public var alphabeticalName: String?
    /** Joined from `artists.code_letters`. */
    public var codeLetters: String
    /** Joined from `genre_artist_crossreference.artist_genre_code` — the artist's number *within* this release's genre, so the same artist has a different one per genre. Part of the call number, not an id.  */
    public var codeArtistNumber: Int
    /** Joined from `format.format_name`. */
    public var formatName: String
    /** Joined from `genres.genre_name`, a `varchar(64)`. Free-form: `GET /library/genres` is the authoritative enumeration (#367).  */
    public var genreName: String
    /** Station play count for this release. */
    public var plays: Int?
    public var lastModified: Date?
    /** Set when a DJ flags the release missing from the stacks (BS#393). A release is currently missing when `date_lost` is set and `date_found` is either absent or earlier than it.  */
    public var dateLost: Date?
    public var dateFound: Date?
    /** Whether the release resolved to a streaming service. `false` is meaningful (checked, absent — the WXYC EXCLUSIVE case); null means never checked.  */
    public var onStreaming: Bool?
    /** The library row's surrogate key (BS#1963), NOT NULL in the database since migration 0137. Optional here, never required, matching the `CatalogExportRow` and `BulkResolveInput` precedent.  */
    public var legacyReleaseId: Int?
    /** MD-set marker indicating this release is intentionally not on Discogs (embargoed promo, audience-segment release, etc.). When true, the LML runtime-lookup chokepoint does not attempt Discogs resolution for this release. See WXYC/wiki plans/rotation-discogs-unavailable.md.  */
    public var discogsUnavailable: Bool?
    /** Optional free-text reason for `discogsUnavailable`. */
    public var discogsUnavailableNote: String?
    /** Stamped on every recheck attempt by the `library-discogs-unavailable-recheck` cron. Read-only from the client side.  */
    public var lastDiscogsRecheckAt: Date?
    /** The release's definitive external links (label page, Bandcamp, streaming, press), in storage order — position IS the contract, so a consumer renders them in array order. Plain strings, not `format: uri` — MDs paste bare domains, so a value carries no scheme guarantee and a renderer must not bind one into an href without checking it. Release-scoped and rotation-independent: set replace-wholesale via `PUT /library/{id}/urls`. Same `urls` vocabulary and bounds as the search read (`AlbumSearchResult.urls`) and the write shape (`AlbumUrlsUpdate.urls`) — at most 20 links, 2048 characters each. Optional here (never required) and absent until Backend-Service persists it (BS#2491); a consumer must tolerate its absence.  */
    public var urls: [String]?
    public var reconciledIdentity: ReconciledIdentity?

    public init(id: Int, artistId: Int, albumTitle: String, codeNumber: Int, genreId: Int, formatId: Int, label: String?, recordLabel: String? = nil, labelId: Int? = nil, addDate: Date, discQuantity: Int? = nil, alternateArtistName: String? = nil, albumArtist: String? = nil, artistName: String, alphabeticalName: String? = nil, codeLetters: String, codeArtistNumber: Int, formatName: String, genreName: String, plays: Int? = nil, lastModified: Date? = nil, dateLost: Date? = nil, dateFound: Date? = nil, onStreaming: Bool? = nil, legacyReleaseId: Int? = nil, discogsUnavailable: Bool? = nil, discogsUnavailableNote: String? = nil, lastDiscogsRecheckAt: Date? = nil, urls: [String]? = nil, reconciledIdentity: ReconciledIdentity? = nil) {
        self.id = id
        self.artistId = artistId
        self.albumTitle = albumTitle
        self.codeNumber = codeNumber
        self.genreId = genreId
        self.formatId = formatId
        self.label = label
        self.recordLabel = recordLabel
        self.labelId = labelId
        self.addDate = addDate
        self.discQuantity = discQuantity
        self.alternateArtistName = alternateArtistName
        self.albumArtist = albumArtist
        self.artistName = artistName
        self.alphabeticalName = alphabeticalName
        self.codeLetters = codeLetters
        self.codeArtistNumber = codeArtistNumber
        self.formatName = formatName
        self.genreName = genreName
        self.plays = plays
        self.lastModified = lastModified
        self.dateLost = dateLost
        self.dateFound = dateFound
        self.onStreaming = onStreaming
        self.legacyReleaseId = legacyReleaseId
        self.discogsUnavailable = discogsUnavailable
        self.discogsUnavailableNote = discogsUnavailableNote
        self.lastDiscogsRecheckAt = lastDiscogsRecheckAt
        self.urls = urls
        self.reconciledIdentity = reconciledIdentity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case artistId = "artist_id"
        case albumTitle = "album_title"
        case codeNumber = "code_number"
        case genreId = "genre_id"
        case formatId = "format_id"
        case label
        case recordLabel = "record_label"
        case labelId = "label_id"
        case addDate = "add_date"
        case discQuantity = "disc_quantity"
        case alternateArtistName = "alternate_artist_name"
        case albumArtist = "album_artist"
        case artistName = "artist_name"
        case alphabeticalName = "alphabetical_name"
        case codeLetters = "code_letters"
        case codeArtistNumber = "code_artist_number"
        case formatName = "format_name"
        case genreName = "genre_name"
        case plays
        case lastModified = "last_modified"
        case dateLost = "date_lost"
        case dateFound = "date_found"
        case onStreaming = "on_streaming"
        case legacyReleaseId = "legacy_release_id"
        case discogsUnavailable
        case discogsUnavailableNote
        case lastDiscogsRecheckAt
        case urls
        case reconciledIdentity = "reconciled_identity"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(artistId, forKey: .artistId)
        try container.encode(albumTitle, forKey: .albumTitle)
        try container.encode(codeNumber, forKey: .codeNumber)
        try container.encode(genreId, forKey: .genreId)
        try container.encode(formatId, forKey: .formatId)
        try container.encode(label, forKey: .label)
        try container.encodeIfPresent(recordLabel, forKey: .recordLabel)
        try container.encodeIfPresent(labelId, forKey: .labelId)
        try container.encode(addDate, forKey: .addDate)
        try container.encodeIfPresent(discQuantity, forKey: .discQuantity)
        try container.encodeIfPresent(alternateArtistName, forKey: .alternateArtistName)
        try container.encodeIfPresent(albumArtist, forKey: .albumArtist)
        try container.encode(artistName, forKey: .artistName)
        try container.encodeIfPresent(alphabeticalName, forKey: .alphabeticalName)
        try container.encode(codeLetters, forKey: .codeLetters)
        try container.encode(codeArtistNumber, forKey: .codeArtistNumber)
        try container.encode(formatName, forKey: .formatName)
        try container.encode(genreName, forKey: .genreName)
        try container.encodeIfPresent(plays, forKey: .plays)
        try container.encodeIfPresent(lastModified, forKey: .lastModified)
        try container.encodeIfPresent(dateLost, forKey: .dateLost)
        try container.encodeIfPresent(dateFound, forKey: .dateFound)
        try container.encodeIfPresent(onStreaming, forKey: .onStreaming)
        try container.encodeIfPresent(legacyReleaseId, forKey: .legacyReleaseId)
        try container.encodeIfPresent(discogsUnavailable, forKey: .discogsUnavailable)
        try container.encodeIfPresent(discogsUnavailableNote, forKey: .discogsUnavailableNote)
        try container.encodeIfPresent(lastDiscogsRecheckAt, forKey: .lastDiscogsRecheckAt)
        try container.encodeIfPresent(urls, forKey: .urls)
        try container.encodeIfPresent(reconciledIdentity, forKey: .reconciledIdentity)
    }
}

