//
// AlbumMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AlbumMetadata: Sendable, Codable, Hashable {

    public var albumId: Int
    public var artworkUrl: String?
    public var discogsUrl: String?
    public var discogsId: Int?
    public var releaseYear: Int?
    public var spotifyUrl: String?
    public var appleMusicUrl: String?
    public var youtubeMusicUrl: String?
    public var bandcampUrl: String?
    public var soundcloudUrl: String?
    public var lastFetched: Date?

    public init(albumId: Int, artworkUrl: String? = nil, discogsUrl: String? = nil, discogsId: Int? = nil, releaseYear: Int? = nil, spotifyUrl: String? = nil, appleMusicUrl: String? = nil, youtubeMusicUrl: String? = nil, bandcampUrl: String? = nil, soundcloudUrl: String? = nil, lastFetched: Date? = nil) {
        self.albumId = albumId
        self.artworkUrl = artworkUrl
        self.discogsUrl = discogsUrl
        self.discogsId = discogsId
        self.releaseYear = releaseYear
        self.spotifyUrl = spotifyUrl
        self.appleMusicUrl = appleMusicUrl
        self.youtubeMusicUrl = youtubeMusicUrl
        self.bandcampUrl = bandcampUrl
        self.soundcloudUrl = soundcloudUrl
        self.lastFetched = lastFetched
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albumId = "album_id"
        case artworkUrl = "artwork_url"
        case discogsUrl = "discogs_url"
        case discogsId = "discogs_id"
        case releaseYear = "release_year"
        case spotifyUrl = "spotify_url"
        case appleMusicUrl = "apple_music_url"
        case youtubeMusicUrl = "youtube_music_url"
        case bandcampUrl = "bandcamp_url"
        case soundcloudUrl = "soundcloud_url"
        case lastFetched = "last_fetched"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(albumId, forKey: .albumId)
        try container.encodeIfPresent(artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(discogsUrl, forKey: .discogsUrl)
        try container.encodeIfPresent(discogsId, forKey: .discogsId)
        try container.encodeIfPresent(releaseYear, forKey: .releaseYear)
        try container.encodeIfPresent(spotifyUrl, forKey: .spotifyUrl)
        try container.encodeIfPresent(appleMusicUrl, forKey: .appleMusicUrl)
        try container.encodeIfPresent(youtubeMusicUrl, forKey: .youtubeMusicUrl)
        try container.encodeIfPresent(bandcampUrl, forKey: .bandcampUrl)
        try container.encodeIfPresent(soundcloudUrl, forKey: .soundcloudUrl)
        try container.encodeIfPresent(lastFetched, forKey: .lastFetched)
    }
}

