//
// AlbumReview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One archived DJ album review, sourced from the WXYC album-review Google Form (collected since March 2021) and synced nightly by Backend-Service&#39;s album-reviews ETL.  Distinct from ADR 0006&#39;s in-app Review model (one-per-album, author-owned, &#x60;/reviews&#x60;): submissions here are append-only, may number several per album, and identify albums by free text with a best-effort &#x60;album_id&#x60; link. Reviewer identity is deliberately not exposed — the form promised reviewers their names would not be shared.  */
public struct AlbumReview: Sendable, Codable, Hashable {

    public var id: Int
    /** WXYC library album id when the free-text artist/album resolved to exactly one catalog row; null otherwise. */
    public var albumId: Int?
    /** Artist name exactly as the reviewer entered it. */
    public var artistName: String?
    /** Album title exactly as the reviewer entered it. */
    public var albumTitle: String?
    public var recordLabel: String?
    /** Short reviewer-written background on the artist. */
    public var artistBlurb: String?
    /** The review body. */
    public var review: String?
    /** Raw recommended-tracks text, including the form's `!`-rating notation (1–5 exclamation marks) and \"Play All\" shorthand. */
    public var recommendedTracks: String?
    /** Comma-separated reviewer-chosen descriptors. */
    public var buzzwords: String?
    /** Verbatim reviewer answer listing FCC-violating track numbers. Blank (unanswered) is distinct from \"None\"/\"N/A\" (affirmatively clean); values are not normalized. */
    public var fccViolations: String?
    /** Raw multi-select of \"Rotation\", \"New DJ Assignment\", \"Album in the Library\"; comma-joined when multiple were selected. */
    public var reviewPurpose: String?
    /** Curator-maintained \"was this album rotated\" flag; null when the sheet cell is blank or unparseable. */
    public var rotated: Bool?
    /** Whether the album was released within 6 months of the review; null when unanswered (question added mid-2024). */
    public var releasedWithinSixMonths: Bool?
    /** Whether the reviewer consented to the review being shared on station social media (always anonymously); null when unanswered. */
    public var socialConsent: Bool?
    /** Form submission instant. Null only for the rare row whose sheet timestamp is missing. */
    public var submittedAt: Date?

    public init(id: Int, albumId: Int?, artistName: String?, albumTitle: String?, recordLabel: String?, artistBlurb: String?, review: String?, recommendedTracks: String?, buzzwords: String?, fccViolations: String?, reviewPurpose: String?, rotated: Bool?, releasedWithinSixMonths: Bool?, socialConsent: Bool?, submittedAt: Date?) {
        self.id = id
        self.albumId = albumId
        self.artistName = artistName
        self.albumTitle = albumTitle
        self.recordLabel = recordLabel
        self.artistBlurb = artistBlurb
        self.review = review
        self.recommendedTracks = recommendedTracks
        self.buzzwords = buzzwords
        self.fccViolations = fccViolations
        self.reviewPurpose = reviewPurpose
        self.rotated = rotated
        self.releasedWithinSixMonths = releasedWithinSixMonths
        self.socialConsent = socialConsent
        self.submittedAt = submittedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case albumId = "album_id"
        case artistName = "artist_name"
        case albumTitle = "album_title"
        case recordLabel = "record_label"
        case artistBlurb = "artist_blurb"
        case review
        case recommendedTracks = "recommended_tracks"
        case buzzwords
        case fccViolations = "fcc_violations"
        case reviewPurpose = "review_purpose"
        case rotated
        case releasedWithinSixMonths = "released_within_six_months"
        case socialConsent = "social_consent"
        case submittedAt = "submitted_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(albumId, forKey: .albumId)
        try container.encode(artistName, forKey: .artistName)
        try container.encode(albumTitle, forKey: .albumTitle)
        try container.encode(recordLabel, forKey: .recordLabel)
        try container.encode(artistBlurb, forKey: .artistBlurb)
        try container.encode(review, forKey: .review)
        try container.encode(recommendedTracks, forKey: .recommendedTracks)
        try container.encode(buzzwords, forKey: .buzzwords)
        try container.encode(fccViolations, forKey: .fccViolations)
        try container.encode(reviewPurpose, forKey: .reviewPurpose)
        try container.encode(rotated, forKey: .rotated)
        try container.encode(releasedWithinSixMonths, forKey: .releasedWithinSixMonths)
        try container.encode(socialConsent, forKey: .socialConsent)
        try container.encode(submittedAt, forKey: .submittedAt)
    }
}

