//
// ApiErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiErrorResponse: Sendable, Codable, Hashable {

    public var message: String
    public var code: String?
    public var details: [String: JSONValue]?

    public init(message: String, code: String? = nil, details: [String: JSONValue]? = nil) {
        self.message = message
        self.code = code
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case code
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(details, forKey: .details)
    }
}

