//
// AppConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AppConfig: Sendable, Codable, Hashable {

    /** PostHog analytics write key (public by design) */
    public var posthogApiKey: String
    /** PostHog ingestion host */
    public var posthogHost: String
    /** Request-o-matic service URL for song requests */
    public var requestOMaticUrl: String
    /** Backend API base URL */
    public var apiBaseUrl: String

    public init(posthogApiKey: String, posthogHost: String, requestOMaticUrl: String, apiBaseUrl: String) {
        self.posthogApiKey = posthogApiKey
        self.posthogHost = posthogHost
        self.requestOMaticUrl = requestOMaticUrl
        self.apiBaseUrl = apiBaseUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case posthogApiKey
        case posthogHost
        case requestOMaticUrl
        case apiBaseUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(posthogApiKey, forKey: .posthogApiKey)
        try container.encode(posthogHost, forKey: .posthogHost)
        try container.encode(requestOMaticUrl, forKey: .requestOMaticUrl)
        try container.encode(apiBaseUrl, forKey: .apiBaseUrl)
    }
}

