//
// Artist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Artist: Sendable, Codable, Hashable {

    public var id: Int
    public var artistName: String
    public var codeLetters: String
    public var codeArtistNumber: Int
    public var genreId: Int

    public init(id: Int, artistName: String, codeLetters: String, codeArtistNumber: Int, genreId: Int) {
        self.id = id
        self.artistName = artistName
        self.codeLetters = codeLetters
        self.codeArtistNumber = codeArtistNumber
        self.genreId = genreId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case artistName = "artist_name"
        case codeLetters = "code_letters"
        case codeArtistNumber = "code_artist_number"
        case genreId = "genre_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(artistName, forKey: .artistName)
        try container.encode(codeLetters, forKey: .codeLetters)
        try container.encode(codeArtistNumber, forKey: .codeArtistNumber)
        try container.encode(genreId, forKey: .genreId)
    }
}

