//
// ArtistResolveBulkResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response to &#x60;POST /api/v1/artists/resolve/bulk&#x60;. &#x60;results&#x60; is index-aligned with the request&#39;s &#x60;names&#x60;.  */
public struct ArtistResolveBulkResponse: Sendable, Codable, Hashable {

    public var results: [ArtistResolveResult]

    public init(results: [ArtistResolveResult]) {
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(results, forKey: .results)
    }
}

