//
// ArtistResolveCacheLeg.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A discogs-cache candidate-generation leg that produced at least one candidate for the input name. Mirrors the entity-resolution reconciler cascade&#39;s legs (exact / member / alias / name-variation / trigram — the cascade subset of &#x60;IdentityMethod&#x60;), but as candidate sets used for corroboration and conflict detection — never as verdicts. The four equality legs can veto a mint into &#x60;ambiguous&#x60;; fuzzy &#x60;cache_trigram&#x60; neighbors never veto.  */
public enum ArtistResolveCacheLeg: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case cacheExact = "cache_exact"
    case cacheMember = "cache_member"
    case cacheAlias = "cache_alias"
    case cacheNameVariation = "cache_name_variation"
    case cacheTrigram = "cache_trigram"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension ArtistResolveCacheLeg: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
