//
// ArtistMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ArtistMetadata: Sendable, Codable, Hashable {

    public var artistId: Int
    public var bio: String?
    public var wikipediaUrl: String?
    public var discogsUrl: String?
    public var discogsId: Int?
    public var imageUrl: String?
    public var lastFetched: Date?

    public init(artistId: Int, bio: String? = nil, wikipediaUrl: String? = nil, discogsUrl: String? = nil, discogsId: Int? = nil, imageUrl: String? = nil, lastFetched: Date? = nil) {
        self.artistId = artistId
        self.bio = bio
        self.wikipediaUrl = wikipediaUrl
        self.discogsUrl = discogsUrl
        self.discogsId = discogsId
        self.imageUrl = imageUrl
        self.lastFetched = lastFetched
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artistId = "artist_id"
        case bio
        case wikipediaUrl = "wikipedia_url"
        case discogsUrl = "discogs_url"
        case discogsId = "discogs_id"
        case imageUrl = "image_url"
        case lastFetched = "last_fetched"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artistId, forKey: .artistId)
        try container.encodeIfPresent(bio, forKey: .bio)
        try container.encodeIfPresent(wikipediaUrl, forKey: .wikipediaUrl)
        try container.encodeIfPresent(discogsUrl, forKey: .discogsUrl)
        try container.encodeIfPresent(discogsId, forKey: .discogsId)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encodeIfPresent(lastFetched, forKey: .lastFetched)
    }
}

