//
// ArtistSearchAliasSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Origin of an artist search alias variant. Opaque to BS storage (just a tag); used by future read-path ranking and audit. Open enum — new sources can be added by LML without a wire-format break.  */
public enum ArtistSearchAliasSource: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case discogsNameVariation = "discogs_name_variation"
    case discogsAlias = "discogs_alias"
    case discogsMember = "discogs_member"
    case wxycLibraryAlt = "wxyc_library_alt"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension ArtistSearchAliasSource: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
