//
// ArtistGenresSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Where an artist&#39;s genre/style answer came from, so the caller can distinguish a genuine \&quot;Discogs has no genre data for this artist\&quot; (safe to negative-cache) from a transient \&quot;couldn&#39;t ask Discogs\&quot; (retry). &#x60;cache&#x60; — served from the discogs-cache &#x60;release_genre&#x60; rows. &#x60;discogs_api&#x60; — cache miss; the Discogs API fallback produced genres. &#x60;not_found&#x60; — cache miss; the API answered but the artist has no release/genre data (safe to negative-cache). &#x60;unavailable&#x60; — cache miss and the API could not be consulted (no Discogs token, saturation breaker open, or a transient fetch failure); retry, do NOT negative-cache.  */
public enum ArtistGenresSource: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case cache = "cache"
    case discogsApi = "discogs_api"
    case notFound = "not_found"
    case unavailable = "unavailable"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension ArtistGenresSource: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
