//
// ArtistMatchHint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Populated on library search result items when an artist-alias match from the BS-local &#x60;artist_search_alias&#x60; cache drove the inclusion of this release into the results (artist-search-alias plan PR 5). Sibling to TrackMatchHint — track hints carry title + position + artist_credit which have no meaning for alias matches; alias hints carry the variant string that scored and its source tag for UX rendering and audit.  */
public struct ArtistMatchHint: Sendable, Codable, Hashable {

    /** The cached alias string that trigram-matched the query. */
    public var matchedVariant: String
    public var source: ArtistSearchAliasSource

    public init(matchedVariant: String, source: ArtistSearchAliasSource) {
        self.matchedVariant = matchedVariant
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case matchedVariant = "matched_variant"
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(matchedVariant, forKey: .matchedVariant)
        try container.encode(source, forKey: .source)
    }
}


extension ArtistMatchHint: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if source == .unknownDefaultOpenApi { return true }
        return false
    }
}
