//
// ArtistSearchAliasesBulkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ArtistSearchAliasesBulkRequest: Sendable, Codable, Hashable {

    public static let namesRule = ArrayRule(minItems: 1, maxItems: 1000, uniqueItems: false)
    /** WXYC canonical artist names. */
    public var names: [String]

    public init(names: [String]) {
        self.names = names
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case names
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(names, forKey: .names)
    }
}

