//
// ArtistSearchAliasVariant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One alias variant for an artist. The &#x60;variant&#x60; string is what gets matched against search queries via trigram similarity. The &#x60;source&#x60; tag identifies where the row came from; &#x60;method&#x60; classifies the semantic relationship.  */
public struct ArtistSearchAliasVariant: Sendable, Codable, Hashable {

    public static let confidenceRule = NumericRule<Float>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    public var source: ArtistSearchAliasSource
    /** The searchable string (e.g. \"Thee Oh Sees\"). */
    public var variant: String
    /** For alias / member kinds, the namespaced source-side id of the related artist (e.g. \"discogs:artist:67890\", \"musicbrainz:artist:<mbid>\"). NULL for name_variation and alt_curated.  */
    public var relatedExternalId: String?
    /** For alias / member kinds, the canonical name of the related artist as the source records it. NULL otherwise.  */
    public var relatedName: String?
    /** For member kind only — Discogs records active/inactive band membership. NULL for other kinds.  */
    public var active: Bool?
    public var method: ArtistSearchAliasMethod
    /** Per-source default confidence (e.g. 0.95 for discogs_name_variation, 0.85 for discogs_alias / wxyc_library_alt, 0.70 for discogs_member). v1 search ignores this; stored for v2 ranking calibration.  */
    public var confidence: Float

    public init(source: ArtistSearchAliasSource, variant: String, relatedExternalId: String? = nil, relatedName: String? = nil, active: Bool? = nil, method: ArtistSearchAliasMethod, confidence: Float) {
        self.source = source
        self.variant = variant
        self.relatedExternalId = relatedExternalId
        self.relatedName = relatedName
        self.active = active
        self.method = method
        self.confidence = confidence
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
        case variant
        case relatedExternalId = "related_external_id"
        case relatedName = "related_name"
        case active
        case method
        case confidence
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(source, forKey: .source)
        try container.encode(variant, forKey: .variant)
        try container.encodeIfPresent(relatedExternalId, forKey: .relatedExternalId)
        try container.encodeIfPresent(relatedName, forKey: .relatedName)
        try container.encodeIfPresent(active, forKey: .active)
        try container.encode(method, forKey: .method)
        try container.encode(confidence, forKey: .confidence)
    }
}


extension ArtistSearchAliasVariant: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if source == .unknownDefaultOpenApi { return true }
        if method == .unknownDefaultOpenApi { return true }
        return false
    }
}
