//
// ArtistSearchAliasMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Semantic classification of how this variant relates to the subject artist. Distinct from source — multiple sources can emit the same method.  */
public enum ArtistSearchAliasMethod: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case nameVariation = "name_variation"
    case alias = "alias"
    case member = "member"
    case altCurated = "alt_curated"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension ArtistSearchAliasMethod: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
