//
// ArtistSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ArtistSearchResponse: Sendable, Codable, Hashable {

    public var artists: [ArtistSearchMatch]

    public init(artists: [ArtistSearchMatch]) {
        self.artists = artists
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artists
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artists, forKey: .artists)
    }
}

