//
// ArtistMetadataResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ArtistMetadataResponse: Sendable, Codable, Hashable {

    /** Discogs artist ID */
    public var discogsArtistId: Int?
    /** Artist biography from Discogs */
    public var bio: String?
    /** Wikipedia URL for the artist */
    public var wikipediaUrl: String?
    /** Artist image URL from Discogs */
    public var imageUrl: String?
    /** Pre-parsed structured tokens from the artist's Discogs profile markup. Pass-through of DiscogsArtistDetails.profile_tokens, so clients can share token rendering across the two payloads.  */
    public var bioTokens: [DiscogsResolvedToken]?

    public init(discogsArtistId: Int? = nil, bio: String? = nil, wikipediaUrl: String? = nil, imageUrl: String? = nil, bioTokens: [DiscogsResolvedToken]? = nil) {
        self.discogsArtistId = discogsArtistId
        self.bio = bio
        self.wikipediaUrl = wikipediaUrl
        self.imageUrl = imageUrl
        self.bioTokens = bioTokens
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case discogsArtistId
        case bio
        case wikipediaUrl
        case imageUrl
        case bioTokens
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(discogsArtistId, forKey: .discogsArtistId)
        try container.encodeIfPresent(bio, forKey: .bio)
        try container.encodeIfPresent(wikipediaUrl, forKey: .wikipediaUrl)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encodeIfPresent(bioTokens, forKey: .bioTokens)
    }
}

