//
// ArtistSearchAliasesBulkResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ArtistSearchAliasesBulkResponse: Sendable, Codable, Hashable {

    public var artists: [ArtistSearchAliasesResult]
    /** Input names with no `entity.identity` row in LML — i.e., LML doesn't know any external IDs for these. BS can choose to retry later (after a discogs-cache rebuild and entity-resolution campaign) or leave them.  */
    public var missing: [String]
    public var cacheStats: CacheStats?

    public init(artists: [ArtistSearchAliasesResult], missing: [String], cacheStats: CacheStats? = nil) {
        self.artists = artists
        self.missing = missing
        self.cacheStats = cacheStats
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artists
        case missing
        case cacheStats = "cache_stats"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artists, forKey: .artists)
        try container.encode(missing, forKey: .missing)
        try container.encodeIfPresent(cacheStats, forKey: .cacheStats)
    }
}

