//
// ArtworkSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ArtworkSearchResponse: Sendable, Codable, Hashable {

    /** Best-match artwork image URL */
    public var artworkUrl: String?
    /** Provider that supplied the artwork (e.g. \"discogs\") */
    public var source: String?
    /** Confidence score of the match (0-1) */
    public var confidence: Double?

    public init(artworkUrl: String? = nil, source: String? = nil, confidence: Double? = nil) {
        self.artworkUrl = artworkUrl
        self.source = source
        self.confidence = confidence
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artworkUrl
        case source
        case confidence
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(confidence, forKey: .confidence)
    }
}

