//
// AuthSignInResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response body for POST /auth/sign-in/email and POST /auth/sign-in/username — identical shape, since both routes end in the same session-create + setSessionCookie call (better-auth dist/api/routes/sign-in.mjs signInEmail; dist/plugins/username signInUsername). &#x60;token&#x60; also arrives on the &#x60;set-auth-token&#x60; response header (see the two paths below); the body is the documented fallback when a caller can&#39;t read response headers.  */
public struct AuthSignInResult: Sendable, Codable, Hashable {

    /** True when callbackURL was supplied and the client should follow Location. */
    public var redirect: Bool
    /** The session token. */
    public var token: String
    /** The callbackURL echoed back. NOT nullable — when no callbackURL was supplied, better-auth's handler passes `url: ctx.body.callbackURL` (undefined) straight into `ctx.json(...)` (dist/api/routes/sign-in.mjs signInEmail), and JSON serialization drops an undefined-valued key rather than emitting `null`. The key is therefore OMITTED entirely in that case, not present-and-null — see this schema's `required` list, which does not include `url`.  */
    public var url: String?
    public var user: AuthUser

    public init(redirect: Bool, token: String, url: String? = nil, user: AuthUser) {
        self.redirect = redirect
        self.token = token
        self.url = url
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case redirect
        case token
        case url
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(redirect, forKey: .redirect)
        try container.encode(token, forKey: .token)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encode(user, forKey: .user)
    }
}

