//
// AuthTokenAndUserResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response body shared by POST /auth/sign-in/anonymous and POST /auth/sign-in/email-otp — both answer &#x60;{token, user}&#x60; with no redirect/url (better-auth dist/plugins/anonymous/index.mjs signInAnonymous; dist/plugins/email-otp/routes.mjs signInEmailOTP). One type for two endpoints, per the DeviceAuthActionResponse precedent above.  */
public struct AuthTokenAndUserResult: Sendable, Codable, Hashable {

    public var token: String
    public var user: AuthUser

    public init(token: String, user: AuthUser) {
        self.token = token
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encode(user, forKey: .user)
    }
}

