//
// AuthTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response body for GET /auth/token — the short-lived JWT. */
public struct AuthTokenResponse: Sendable, Codable, Hashable {

    /** A signed JWT, verifiable against the JWKS at GET /auth/jwks. */
    public var token: String

    public init(token: String) {
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
    }
}

