//
// AuthErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** better-auth&#39;s uniform error body (@better-auth/core&#39;s &#x60;APIError.from&#x60;/&#x60;defineErrorCodes&#x60;: &#x60;{message, code}&#x60;). Purpose-built rather than a $ref to the shared ApiErrorResponse — see this section&#39;s header comment. Answers every non-2xx response from this section&#39;s better-auth-native operations except the 429s — see AuthRateLimitedResponse and AuthPlainErrorResponse, below, for the two DIFFERENT shapes a 429 can actually carry.  */
public struct AuthErrorResponse: Sendable, Codable, Hashable {

    public var message: String
    /** A defineErrorCodes key, e.g. INVALID_EMAIL_OR_PASSWORD, INVALID_USERNAME_OR_PASSWORD, INVALID_EMAIL, EMAIL_NOT_VERIFIED, UNAUTHORIZED, INVALID_OTP, OTP_EXPIRED, TOO_MANY_ATTEMPTS, ANONYMOUS_USERS_CANNOT_SIGN_IN_AGAIN_ANONYMOUSLY, COULD_NOT_CREATE_SESSION, FAILED_TO_CREATE_USER, MISSING_OR_NULL_ORIGIN, VALIDATION_ERROR (better-call's generic body/query-schema failure, e.g. a missing required field — better-call/dist/endpoint.mjs: `throw new APIError(400, {message: validationError.message, code: \"VALIDATION_ERROR\"})` — thrown before any handler code runs, so it can occur on any operation in this section that takes a body). Left open rather than enumerated — unlike DeviceAuth's closed, small RFC 8628 vocabulary, better-auth's general error surface is broad and not practically exhaustible per operation.  */
    public var code: String?

    public init(message: String, code: String? = nil) {
        self.message = message
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(code, forKey: .code)
    }
}

