//
// AuthSendCodeResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response body for POST /auth/email-otp/send-verification-otp. Always &#x60;{success: true}&#x60; on 2xx — disableSignUp: true makes the server answer identically for an unknown address (anti-enumeration), so a 2xx here does not confirm the account exists.  */
public struct AuthSendCodeResult: Sendable, Codable, Hashable {

    public var success: Bool

    public init(success: Bool) {
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
    }
}

