//
// AuthSignOutResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response body for POST /auth/sign-out. Always &#x60;{success: true}&#x60; on 200 — a failure to delete the session server-side is logged, not surfaced (better-auth dist/api/routes/sign-out.mjs signOut).  */
public struct AuthSignOutResult: Sendable, Codable, Hashable {

    public var success: Bool

    public init(success: Bool) {
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
    }
}

