//
// AutoDJActivationSourceType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AutoDJActivationSourceType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case virtualSwitch = "virtual_switch"
    case button = "button"
    case relay = "relay"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension AutoDJActivationSourceType: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
