//
// AutoDJDeviceSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AutoDJDeviceSummary: Sendable, Codable, Hashable {

    public var online: Bool
    public var transport: AutoDJTransport
    public var lastHeartbeat: Date
    public var relayState: AutoDJRelayState

    public init(online: Bool, transport: AutoDJTransport, lastHeartbeat: Date, relayState: AutoDJRelayState) {
        self.online = online
        self.transport = transport
        self.lastHeartbeat = lastHeartbeat
        self.relayState = relayState
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case online
        case transport
        case lastHeartbeat
        case relayState
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(online, forKey: .online)
        try container.encode(transport, forKey: .transport)
        try container.encode(lastHeartbeat, forKey: .lastHeartbeat)
        try container.encode(relayState, forKey: .relayState)
    }
}


extension AutoDJDeviceSummary: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if transport == .unknownDefaultOpenApi { return true }
        if relayState == .unknownDefaultOpenApi { return true }
        return false
    }
}
