//
// AutoDJRelayState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AutoDJRelayState: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case autoDjActive = "auto_dj_active"
    case djLive = "dj_live"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension AutoDJRelayState: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
