//
// AutoDJWebSocketMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AutoDJWebSocketMessage: Sendable, Codable, Hashable {
    case typeAutoDJAck(AutoDJAck)
    case typeAutoDJButtonToggle(AutoDJButtonToggle)
    case typeAutoDJCommand(AutoDJCommand)
    case typeAutoDJErrorReport(AutoDJErrorReport)
    case typeAutoDJHeartbeat(AutoDJHeartbeat)
    case typeAutoDJNowPlaying(AutoDJNowPlaying)
    case unknownDefaultOpenApi

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAutoDJAck(let value):
            try container.encode(value)
        case .typeAutoDJButtonToggle(let value):
            try container.encode(value)
        case .typeAutoDJCommand(let value):
            try container.encode(value)
        case .typeAutoDJErrorReport(let value):
            try container.encode(value)
        case .typeAutoDJHeartbeat(let value):
            try container.encode(value)
        case .typeAutoDJNowPlaying(let value):
            try container.encode(value)
        case .unknownDefaultOpenApi:
            try container.encodeNil()
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case type = "type"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .type)

        switch discriminatorValue {
        case "ack":
            self = .typeAutoDJAck(try AutoDJAck(from: decoder))
        case "button_toggle":
            self = .typeAutoDJButtonToggle(try AutoDJButtonToggle(from: decoder))
        case "command":
            self = .typeAutoDJCommand(try AutoDJCommand(from: decoder))
        case "error":
            self = .typeAutoDJErrorReport(try AutoDJErrorReport(from: decoder))
        case "heartbeat":
            self = .typeAutoDJHeartbeat(try AutoDJHeartbeat(from: decoder))
        case "now_playing":
            self = .typeAutoDJNowPlaying(try AutoDJNowPlaying(from: decoder))
        default:
            self = .unknownDefaultOpenApi
        }
    }
}

