//
// AutoDJHeartbeat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AutoDJHeartbeat: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case heartbeat = "heartbeat"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var state: AutoDJState
    public var transport: AutoDJTransport
    public var uptimeS: Int
    public var wifiRssi: Int?
    public var freeRam: Int
    /** Always null in the reporter model; retained for schema compatibility. */
    public var radioShowId: Int?
    public var lastTrack: AutoDJLastTrack?
    public var lastError: String?
    public var firmwareVersion: String
    public var configHash: String
    public var loopMaxMs: Int
    public var reconnectCount: Int
    public var tracksDetected: Int
    public var tracksPosted: Int
    public var errorsSinceBoot: Int
    /** Button presses since last heartbeat (HTTP/WiFi fallback; orchestrator toggles if odd). 0 if none. */
    public var buttonPressCount: Int?
    /** Current debounced relay level. true = relay reports auto-DJ-active (no live DJ); false = live DJ on air. */
    public var relayAutoDjActive: Bool?

    public init(type: ModelType, state: AutoDJState, transport: AutoDJTransport, uptimeS: Int, wifiRssi: Int? = nil, freeRam: Int, radioShowId: Int? = nil, lastTrack: AutoDJLastTrack? = nil, lastError: String? = nil, firmwareVersion: String, configHash: String, loopMaxMs: Int, reconnectCount: Int, tracksDetected: Int, tracksPosted: Int, errorsSinceBoot: Int, buttonPressCount: Int? = nil, relayAutoDjActive: Bool? = nil) {
        self.type = type
        self.state = state
        self.transport = transport
        self.uptimeS = uptimeS
        self.wifiRssi = wifiRssi
        self.freeRam = freeRam
        self.radioShowId = radioShowId
        self.lastTrack = lastTrack
        self.lastError = lastError
        self.firmwareVersion = firmwareVersion
        self.configHash = configHash
        self.loopMaxMs = loopMaxMs
        self.reconnectCount = reconnectCount
        self.tracksDetected = tracksDetected
        self.tracksPosted = tracksPosted
        self.errorsSinceBoot = errorsSinceBoot
        self.buttonPressCount = buttonPressCount
        self.relayAutoDjActive = relayAutoDjActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case state
        case transport
        case uptimeS = "uptime_s"
        case wifiRssi = "wifi_rssi"
        case freeRam = "free_ram"
        case radioShowId = "radio_show_id"
        case lastTrack = "last_track"
        case lastError = "last_error"
        case firmwareVersion = "firmware_version"
        case configHash = "config_hash"
        case loopMaxMs = "loop_max_ms"
        case reconnectCount = "reconnect_count"
        case tracksDetected = "tracks_detected"
        case tracksPosted = "tracks_posted"
        case errorsSinceBoot = "errors_since_boot"
        case buttonPressCount = "button_press_count"
        case relayAutoDjActive = "relay_auto_dj_active"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(state, forKey: .state)
        try container.encode(transport, forKey: .transport)
        try container.encode(uptimeS, forKey: .uptimeS)
        try container.encodeIfPresent(wifiRssi, forKey: .wifiRssi)
        try container.encode(freeRam, forKey: .freeRam)
        try container.encodeIfPresent(radioShowId, forKey: .radioShowId)
        try container.encodeIfPresent(lastTrack, forKey: .lastTrack)
        try container.encodeIfPresent(lastError, forKey: .lastError)
        try container.encode(firmwareVersion, forKey: .firmwareVersion)
        try container.encode(configHash, forKey: .configHash)
        try container.encode(loopMaxMs, forKey: .loopMaxMs)
        try container.encode(reconnectCount, forKey: .reconnectCount)
        try container.encode(tracksDetected, forKey: .tracksDetected)
        try container.encode(tracksPosted, forKey: .tracksPosted)
        try container.encode(errorsSinceBoot, forKey: .errorsSinceBoot)
        try container.encodeIfPresent(buttonPressCount, forKey: .buttonPressCount)
        try container.encodeIfPresent(relayAutoDjActive, forKey: .relayAutoDjActive)
    }
}


extension AutoDJHeartbeat: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        if state == .unknownDefaultOpenApi { return true }
        if transport == .unknownDefaultOpenApi { return true }
        return false
    }
}
