//
// AutoDJNowPlaying.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AutoDJNowPlaying: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case nowPlaying = "now_playing"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    /** AzuraCast song history ID */
    public var shId: Int
    public var artist: String
    public var title: String
    public var album: String
    /** Whether a live DJ is streaming */
    public var isLive: Bool

    public init(type: ModelType, shId: Int, artist: String, title: String, album: String, isLive: Bool) {
        self.type = type
        self.shId = shId
        self.artist = artist
        self.title = title
        self.album = album
        self.isLive = isLive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case shId = "sh_id"
        case artist
        case title
        case album
        case isLive = "is_live"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(shId, forKey: .shId)
        try container.encode(artist, forKey: .artist)
        try container.encode(title, forKey: .title)
        try container.encode(album, forKey: .album)
        try container.encode(isLive, forKey: .isLive)
    }
}


extension AutoDJNowPlaying: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        return false
    }
}
