//
// AutoDJCurrentTrack.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AutoDJCurrentTrack: Sendable, Codable, Hashable {

    public var artist: String
    public var title: String
    public var album: String
    public var detectedAt: Date

    public init(artist: String, title: String, album: String, detectedAt: Date) {
        self.artist = artist
        self.title = title
        self.album = album
        self.detectedAt = detectedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artist
        case title
        case album
        case detectedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artist, forKey: .artist)
        try container.encode(title, forKey: .title)
        try container.encode(album, forKey: .album)
        try container.encode(detectedAt, forKey: .detectedAt)
    }
}

