//
// AutoDJDeactivateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AutoDJDeactivateResponse: Sendable, Codable, Hashable {

    public var active: Bool
    public var deactivatedBy: AutoDJActivationSource
    public var deactivatedAt: Date

    public init(active: Bool, deactivatedBy: AutoDJActivationSource, deactivatedAt: Date) {
        self.active = active
        self.deactivatedBy = deactivatedBy
        self.deactivatedAt = deactivatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case active
        case deactivatedBy
        case deactivatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(active, forKey: .active)
        try container.encode(deactivatedBy, forKey: .deactivatedBy)
        try container.encode(deactivatedAt, forKey: .deactivatedAt)
    }
}

