//
// AutoDJLastTrack.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AutoDJLastTrack: Sendable, Codable, Hashable {

    public var artist: String
    public var title: String
    /** Unix timestamp */
    public var postedAt: Int

    public init(artist: String, title: String, postedAt: Int) {
        self.artist = artist
        self.title = title
        self.postedAt = postedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artist
        case title
        case postedAt = "posted_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artist, forKey: .artist)
        try container.encode(title, forKey: .title)
        try container.encode(postedAt, forKey: .postedAt)
    }
}

