//
// AutoDJTransport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AutoDJTransport: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case ethernet = "ethernet"
    case wifi = "wifi"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension AutoDJTransport: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
