//
// AutoDJErrorReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AutoDJErrorReport: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case error = "error"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var level: AutoDJErrorLevel
    /** Source module (e.g. mgmt_client, relay_monitor) */
    public var module: String
    public var code: AutoDJErrorCode
    public var message: String
    public var state: AutoDJState
    public var uptimeS: Int
    public var freeRam: Int
    /** Occurrences since last report */
    public var count: Int

    public init(type: ModelType, level: AutoDJErrorLevel, module: String, code: AutoDJErrorCode, message: String, state: AutoDJState, uptimeS: Int, freeRam: Int, count: Int) {
        self.type = type
        self.level = level
        self.module = module
        self.code = code
        self.message = message
        self.state = state
        self.uptimeS = uptimeS
        self.freeRam = freeRam
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case level
        case module
        case code
        case message
        case state
        case uptimeS = "uptime_s"
        case freeRam = "free_ram"
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(level, forKey: .level)
        try container.encode(module, forKey: .module)
        try container.encode(code, forKey: .code)
        try container.encode(message, forKey: .message)
        try container.encode(state, forKey: .state)
        try container.encode(uptimeS, forKey: .uptimeS)
        try container.encode(freeRam, forKey: .freeRam)
        try container.encode(count, forKey: .count)
    }
}


extension AutoDJErrorReport: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        if level == .unknownDefaultOpenApi { return true }
        if code == .unknownDefaultOpenApi { return true }
        if state == .unknownDefaultOpenApi { return true }
        return false
    }
}
