//
// AutoDJState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AutoDJState: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case booting = "BOOTING"
    case connecting = "CONNECTING"
    case connected = "CONNECTED"
    case errorState = "ERROR_STATE"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension AutoDJState: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
