//
// AutoDJCommandAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AutoDJCommandAction: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case setConfig = "set_config"
    case pause = "pause"
    case resume = "resume"
    case endShow = "end_show"
    case restart = "restart"
    case ping = "ping"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension AutoDJCommandAction: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
