//
// AutoDJButtonToggle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AutoDJButtonToggle: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case buttonToggle = "button_toggle"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    /** Unix timestamp of the button press (from NTP) */
    public var timestamp: Int

    public init(type: ModelType, timestamp: Int) {
        self.type = type
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(timestamp, forKey: .timestamp)
    }
}


extension AutoDJButtonToggle: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        return false
    }
}
