//
// BinEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BinEntry: Sendable, Codable, Hashable {

    public var id: Int
    public var djId: Int
    public var albumId: Int
    public var addedAt: Date
    public var albumTitle: String
    public var artistName: String
    public var codeLetters: String
    public var codeNumber: Int

    public init(id: Int, djId: Int, albumId: Int, addedAt: Date, albumTitle: String, artistName: String, codeLetters: String, codeNumber: Int) {
        self.id = id
        self.djId = djId
        self.albumId = albumId
        self.addedAt = addedAt
        self.albumTitle = albumTitle
        self.artistName = artistName
        self.codeLetters = codeLetters
        self.codeNumber = codeNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case djId = "dj_id"
        case albumId = "album_id"
        case addedAt = "added_at"
        case albumTitle = "album_title"
        case artistName = "artist_name"
        case codeLetters = "code_letters"
        case codeNumber = "code_number"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(djId, forKey: .djId)
        try container.encode(albumId, forKey: .albumId)
        try container.encode(addedAt, forKey: .addedAt)
        try container.encode(albumTitle, forKey: .albumTitle)
        try container.encode(artistName, forKey: .artistName)
        try container.encode(codeLetters, forKey: .codeLetters)
        try container.encode(codeNumber, forKey: .codeNumber)
    }
}

