//
// BinLibraryDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BinLibraryDetails: Sendable, Codable, Hashable {

    public var albumId: Int?
    public var albumTitle: String?
    public var artistName: String?
    public var label: String?
    public var codeLetters: String?
    public var codeArtistNumber: Int?
    public var codeNumber: Int?
    public var formatName: String?
    public var genreName: String?
    /** The library row's surrogate key (BS#1963), NOT NULL in the database since migration 0137. Optional here (never required) so the live openapi-compliance deploy gate stays green across the publish -> BS-deploy window, matching the CatalogExportRow and BulkResolveInput precedent.  */
    public var legacyReleaseId: Int?

    public init(albumId: Int? = nil, albumTitle: String? = nil, artistName: String? = nil, label: String? = nil, codeLetters: String? = nil, codeArtistNumber: Int? = nil, codeNumber: Int? = nil, formatName: String? = nil, genreName: String? = nil, legacyReleaseId: Int? = nil) {
        self.albumId = albumId
        self.albumTitle = albumTitle
        self.artistName = artistName
        self.label = label
        self.codeLetters = codeLetters
        self.codeArtistNumber = codeArtistNumber
        self.codeNumber = codeNumber
        self.formatName = formatName
        self.genreName = genreName
        self.legacyReleaseId = legacyReleaseId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albumId = "album_id"
        case albumTitle = "album_title"
        case artistName = "artist_name"
        case label
        case codeLetters = "code_letters"
        case codeArtistNumber = "code_artist_number"
        case codeNumber = "code_number"
        case formatName = "format_name"
        case genreName = "genre_name"
        case legacyReleaseId = "legacy_release_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(albumId, forKey: .albumId)
        try container.encodeIfPresent(albumTitle, forKey: .albumTitle)
        try container.encodeIfPresent(artistName, forKey: .artistName)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(codeLetters, forKey: .codeLetters)
        try container.encodeIfPresent(codeArtistNumber, forKey: .codeArtistNumber)
        try container.encodeIfPresent(codeNumber, forKey: .codeNumber)
        try container.encodeIfPresent(formatName, forKey: .formatName)
        try container.encodeIfPresent(genreName, forKey: .genreName)
        try container.encodeIfPresent(legacyReleaseId, forKey: .legacyReleaseId)
    }
}

