//
// BulkResolveTrackIdentity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Per-track resolution for a V/A library row. One entry per (library_id, track_position) the request resolved. Sources reflect the per-source rows LML composed the track identity from; the chosen identifiers are not lifted into a per-track &#x60;external_ids&#x60; block at this contract version — Backend writes the per-source rows verbatim into &#x60;library_track_identity_source&#x60; per WXYC/library-metadata-lookup#271&#39;s design.  */
public struct BulkResolveTrackIdentity: Sendable, Codable, Hashable {

    /** Track position; matches the request input. */
    public var trackPosition: String
    /** One per-source row per source LML composed the track from. Empty array means LML attempted resolution at track grain and found no matches.  */
    public var sources: [BulkResolveProvenanceEntry]

    public init(trackPosition: String, sources: [BulkResolveProvenanceEntry]) {
        self.trackPosition = trackPosition
        self.sources = sources
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case trackPosition = "track_position"
        case sources
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(trackPosition, forKey: .trackPosition)
        try container.encode(sources, forKey: .sources)
    }
}

