//
// BulkResolveProvenanceEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One per-source row in LML&#39;s reconciliation log for a single result. Surfaces the (source, method, confidence, external_id) tuple that fed §3.4.1.1 composition. Always returned (empty provenance array on &#x60;BulkResolveResult&#x60; means LML attempted the cascade and no source produced a row).  */
public struct BulkResolveProvenanceEntry: Sendable, Codable, Hashable {

    public static let confidenceRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    public var source: IdentitySource
    public var method: IdentityMethod
    /** Per-source confidence in [0, 1], within the source's locked method range from §3.4.1. NULL when `external_id` is NULL — the source ran but produced no candidate, so confidence is undefined (not zero). When non-null, equal to or greater than the `confidence` of the object this entry hangs off — the composition rules either MIN or boost, and never lower a per-source row. That referent is grain-relative, because this schema is reused at two grains: under `BulkResolveResult.provenance` it is the result's own `confidence`, and under `BulkResolveTrackIdentity.sources` it is that track's `confidence`, not the result's. The two are unrelated — a `kind: compilation` result has no result-level `confidence` at all, while its tracks each have their own.  */
    public var confidence: Double?
    /** The external identifier this source resolved to (Discogs release ID, MusicBrainz MBID, Wikidata QID, Spotify URI suffix, etc.). NULL when the source ran but found no match (the row is still surfaced so consumers see the leg ran); `confidence` is also NULL in that case.  */
    public var externalId: String?

    public init(source: IdentitySource, method: IdentityMethod, confidence: Double?, externalId: String? = nil) {
        self.source = source
        self.method = method
        self.confidence = confidence
        self.externalId = externalId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
        case method
        case confidence
        case externalId = "external_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(source, forKey: .source)
        try container.encode(method, forKey: .method)
        try container.encode(confidence, forKey: .confidence)
        try container.encodeIfPresent(externalId, forKey: .externalId)
    }
}


extension BulkResolveProvenanceEntry: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if source == .unknownDefaultOpenApi { return true }
        if method == .unknownDefaultOpenApi { return true }
        return false
    }
}
