//
// BulkCacheRefreshRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request body. The 50-id batch cap is enforced server-side with HTTP 400 on overflow (not 422 — LML&#39;s &#x60;/api/v1/lookup/bulk&#x60; precedent). Downstream callers should encode 50 as a hard constant or assert at startup, not expose it as an env knob — the cap is bounded by Discogs rate-limit × cold-cache fan-out ≤ Railway&#39;s request-timeout ceiling, and recalibration must land alongside any ingress change. Empty &#x60;identity_ids&#x60; returns 422 (Pydantic &#x60;min_length&#x3D;1&#x60;). Duplicate identity_ids are allowed; each runs independently and shows up as a separate result.  */
public struct BulkCacheRefreshRequest: Sendable, Codable, Hashable {

    public static let identityIdsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    public var identityIds: [Int]

    public init(identityIds: [Int]) {
        self.identityIds = identityIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identityIds = "identity_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identityIds, forKey: .identityIds)
    }
}

