//
// BulkResolveLibrariesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Bulk identity-resolution request. Order is preserved in the response. Up to 1,000 inputs per call (see endpoint cap).  */
public struct BulkResolveLibrariesRequest: Sendable, Codable, Hashable {

    public static let inputsRule = ArrayRule(minItems: 1, maxItems: 1000, uniqueItems: false)
    /** Inputs to resolve. Order preserved in `BulkResolveLibrariesResponse.results`.  */
    public var inputs: [BulkResolveInput]

    public init(inputs: [BulkResolveInput]) {
        self.inputs = inputs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inputs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(inputs, forKey: .inputs)
    }
}

