//
// BulkResolveResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One verdict per request input, in the same order as the request. &#x60;kind&#x60; discriminates the body shape. &#x60;library_id&#x60; echoes the request input so consumers can re-key the response without relying on positional ordering.  */
public struct BulkResolveResult: Sendable, Codable, Hashable {

    public static let confidenceRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    public var kind: BulkResolveResultKind
    /** Backend `library.id` for this result. */
    public var libraryId: Int
    /** Composed external IDs for `kind: single_artist`. NULL for every other `kind`. URL construction is the consumer's job (see existing ReconciledIdentity contract).  */
    public var main: ReconciledIdentity?
    /** The composed top-level method LML's bulk-resolve handler picked per §3.4.1.1 (typically the strongest leg's method, or `cross_source_agreement` when Rule 2 boosted). NULL for `kind: unresolved`.  */
    public var method: IdentityMethod?
    /** Composed top-level confidence in [0, 1] — the MIN of resolved sources' confidences after composition (§3.4.1.1 Rule 4), unless boosted by cross-source agreement (Rule 2). NULL for `kind: unresolved`.  */
    public var confidence: Double?
    /** Per-source rows feeding LML's composition. Always present; empty array means LML attempted the cascade and no source produced a row above the §3.4.1.1 Rule 6 floor.  */
    public var provenance: [BulkResolveProvenanceEntry]
    /** Set only for `kind: compilation`; absent for every other `kind`. Empty array when LML has no per-track data for the V/A row yet. Two states (present-array or absent), not three.  */
    public var tracks: [BulkResolveTrackIdentity]?

    public init(kind: BulkResolveResultKind, libraryId: Int, main: ReconciledIdentity? = nil, method: IdentityMethod? = nil, confidence: Double? = nil, provenance: [BulkResolveProvenanceEntry], tracks: [BulkResolveTrackIdentity]? = nil) {
        self.kind = kind
        self.libraryId = libraryId
        self.main = main
        self.method = method
        self.confidence = confidence
        self.provenance = provenance
        self.tracks = tracks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case libraryId = "library_id"
        case main
        case method
        case confidence
        case provenance
        case tracks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(libraryId, forKey: .libraryId)
        try container.encodeIfPresent(main, forKey: .main)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(confidence, forKey: .confidence)
        try container.encode(provenance, forKey: .provenance)
        try container.encodeIfPresent(tracks, forKey: .tracks)
    }
}


extension BulkResolveResult: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if kind == .unknownDefaultOpenApi { return true }
        if method == .unknownDefaultOpenApi { return true }
        return false
    }
}
