//
// BulkResolveInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One library row to resolve. Uniform shape — LML auto-detects V/A from the row and discriminates the response on &#x60;kind&#x60;. The denormalized hint fields (&#x60;artist_name&#x60;, &#x60;album_title&#x60;) are not required to be canonical; LML may use them as matcher hints or ignore them in favour of its own mirror of Backend&#39;s library data. They are present so LML doesn&#39;t need a Backend DB read to resolve.  */
public struct BulkResolveInput: Sendable, Codable, Hashable {

    /** Backend `wxyc_schema.library.id` (FK target). */
    public var libraryId: Int
    /** Hint — Backend's denormalized artist name for the row. */
    public var artistName: String
    /** Hint — Backend's denormalized album title for the row. */
    public var albumTitle: String

    public init(libraryId: Int, artistName: String, albumTitle: String) {
        self.libraryId = libraryId
        self.artistName = artistName
        self.albumTitle = albumTitle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case libraryId = "library_id"
        case artistName = "artist_name"
        case albumTitle = "album_title"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(libraryId, forKey: .libraryId)
        try container.encode(artistName, forKey: .artistName)
        try container.encode(albumTitle, forKey: .albumTitle)
    }
}

