//
// BulkResolveResultKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Discriminator for &#x60;BulkResolveResult&#x60;. &#x60;single_artist&#x60; carries a composed &#x60;main&#x60; identity. &#x60;compilation&#x60; carries &#x60;tracks&#x60; (empty array if LML has no per-track data for the V/A row yet). &#x60;unresolved&#x60; is a first-class outcome — caching it (with TTL) prevents repeated re-asking for unresolvable rows.  */
public enum BulkResolveResultKind: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case singleArtist = "single_artist"
    case compilation = "compilation"
    case unresolved = "unresolved"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension BulkResolveResultKind: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
