//
// CacheRefreshArtistOutcome.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Per-artist outcome inside the walk-to-artists step of a per-source release refresh. &#x60;external_id&#x60; is string-typed for future source-agnosticism — Discogs IDs serialize as decimal strings.  */
public struct CacheRefreshArtistOutcome: Sendable, Codable, Hashable {

    public var externalId: String
    public var outcome: CacheRefreshSourceOutcome
    /** Exception class name when `outcome != success`. Bare `str()` of the exception is intentionally NOT serialized — it may carry upstream error bodies, SQL fragments, or file paths. Full traceback lands in Sentry.  */
    public var message: String?

    public init(externalId: String, outcome: CacheRefreshSourceOutcome, message: String? = nil) {
        self.externalId = externalId
        self.outcome = outcome
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case externalId = "external_id"
        case outcome
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(externalId, forKey: .externalId)
        try container.encode(outcome, forKey: .outcome)
        try container.encodeIfPresent(message, forKey: .message)
    }
}


extension CacheRefreshArtistOutcome: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if outcome == .unknownDefaultOpenApi { return true }
        return false
    }
}
