//
// CacheStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Cache hit/miss statistics for a single lookup operation. Populated by LML&#39;s &#x60;core/telemetry.py:get_cache_stats()&#x60; and forwarded onto Sentry trace data by both the LML transaction (LML#213) and the BS-side client span wrapping &#x60;lookupMetadata&#x60; (BS#646).  */
public struct CacheStats: Sendable, Codable, Hashable {

    public static let memoryHitsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let pgHitsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let pgMissesRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let apiCallsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let pgTimeMsRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let apiTimeMsRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Hits in LML's per-process in-memory TTL cache */
    public var memoryHits: Int
    /** Hits in the discogs-cache PostgreSQL cache */
    public var pgHits: Int
    /** Misses in the discogs-cache PostgreSQL cache (forced an API call or fallback) */
    public var pgMisses: Int
    /** Number of Discogs API calls made during the lookup */
    public var apiCalls: Int
    /** Total milliseconds spent in PostgreSQL cache lookups */
    public var pgTimeMs: Double
    /** Total milliseconds spent in Discogs API calls */
    public var apiTimeMs: Double

    public init(memoryHits: Int, pgHits: Int, pgMisses: Int, apiCalls: Int, pgTimeMs: Double, apiTimeMs: Double) {
        self.memoryHits = memoryHits
        self.pgHits = pgHits
        self.pgMisses = pgMisses
        self.apiCalls = apiCalls
        self.pgTimeMs = pgTimeMs
        self.apiTimeMs = apiTimeMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case memoryHits = "memory_hits"
        case pgHits = "pg_hits"
        case pgMisses = "pg_misses"
        case apiCalls = "api_calls"
        case pgTimeMs = "pg_time_ms"
        case apiTimeMs = "api_time_ms"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(memoryHits, forKey: .memoryHits)
        try container.encode(pgHits, forKey: .pgHits)
        try container.encode(pgMisses, forKey: .pgMisses)
        try container.encode(apiCalls, forKey: .apiCalls)
        try container.encode(pgTimeMs, forKey: .pgTimeMs)
        try container.encode(apiTimeMs, forKey: .apiTimeMs)
    }
}

