//
// CacheRefreshResultItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Per-identity verdict. &#x60;sources&#x60; is null when &#x60;status &#x3D;&#x3D; not_found&#x60; (no row to dispatch against). Otherwise it is keyed by source vocabulary (&#x60;discogs_release&#x60;, &#x60;discogs_master&#x60;, …); see &#x60;RELEASE_SOURCE_COLUMN&#x60; on the LML side for the canonical set.  */
public struct CacheRefreshResultItem: Sendable, Codable, Hashable {

    public var identityId: Int
    public var status: CacheRefreshItemStatus
    public var sources: [String: CacheRefreshSourceResult]?
    public var message: String?

    public init(identityId: Int, status: CacheRefreshItemStatus, sources: [String: CacheRefreshSourceResult]? = nil, message: String? = nil) {
        self.identityId = identityId
        self.status = status
        self.sources = sources
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identityId = "identity_id"
        case status
        case sources
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identityId, forKey: .identityId)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(sources, forKey: .sources)
        try container.encodeIfPresent(message, forKey: .message)
    }
}


extension CacheRefreshResultItem: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
