//
// CacheRefreshItemStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Per-identity rollup of the per-source outcomes. Release-leg-gated: any source &#x60;success&#x60; → &#x60;warmed&#x60; (artist failures inside a release walk are partial value, not a retry trigger). Only &#x60;not_implemented&#x60; sources → &#x60;not_implemented&#x60;. All sources errored → &#x60;error&#x60;. Row absent in &#x60;entity.release_identity&#x60; → &#x60;not_found&#x60; (with &#x60;sources&#x60; as null). Only &#x60;error&#x60; is a retry signal.  */
public enum CacheRefreshItemStatus: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case warmed = "warmed"
    case notFound = "not_found"
    case notImplemented = "not_implemented"
    case error = "error"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension CacheRefreshItemStatus: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
