//
// CatalogSearchParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CatalogSearchParams: Sendable, Codable, Hashable {

    public enum OrderDirection: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case asc = "asc"
        case desc = "desc"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var artistName: String?
    public var albumTitle: String?
    /** Maximum number of results */
    public var n: Int?
    public var orderBy: String?
    public var orderDirection: OrderDirection?

    public init(artistName: String? = nil, albumTitle: String? = nil, n: Int? = nil, orderBy: String? = nil, orderDirection: OrderDirection? = nil) {
        self.artistName = artistName
        self.albumTitle = albumTitle
        self.n = n
        self.orderBy = orderBy
        self.orderDirection = orderDirection
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artistName = "artist_name"
        case albumTitle = "album_title"
        case n
        case orderBy
        case orderDirection
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(artistName, forKey: .artistName)
        try container.encodeIfPresent(albumTitle, forKey: .albumTitle)
        try container.encodeIfPresent(n, forKey: .n)
        try container.encodeIfPresent(orderBy, forKey: .orderBy)
        try container.encodeIfPresent(orderDirection, forKey: .orderDirection)
    }
}


extension CatalogSearchParams: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if orderDirection == .unknownDefaultOpenApi { return true }
        return false
    }
}
