//
// CatalogExportRow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One row of the WXYC library catalog as served by GET /library/catalog for offline cloning (BS#1468, Epic F #1466). A query-independent snapshot of the core catalog row. Deliberately NOT AlbumSearchResult: it drops the search-only decoration (matched_via, matched_via_alias, album_dist, artist_dist) and the fields the export omits (add_date, label_id, rotation_id, album_artist, date_lost, date_found), and instead ships rotation RAW (rotation_bin + rotation_kill_date) so the client evaluates rotation expiry against its own clock. See the rotation_bin description for the load-bearing semantic difference from AlbumSearchResult.  */
public struct CatalogExportRow: Sendable, Codable, Hashable {

    public var id: Int
    /** Authoritative artist name. The server COALESCEs the denormalized library.artist_name to artists.artist_name (NOT NULL), so this never ships as null even before the denormalization backfill completes.  */
    public var artistName: String
    public var albumTitle: String
    /** Shelf call-number letters (e.g. \"AU\"). */
    public var codeLetters: String
    /** Shelf call-number release number. */
    public var codeNumber: Int
    /** Shelf call-number artist number (genre-scoped). */
    public var codeArtistNumber: Int
    public var label: String?
    public var genreName: String
    public var formatName: String
    /** True if on >=1 streaming service; false if physical-only; null if unknown. */
    public var onStreaming: Bool?
    /** Per-pressing LINKED play count for THIS catalog row (from album_plays). The honest per-release number; to rank by real popularity across all pressings of a logical album, use `popularity` instead.  */
    public var plays: Int?
    /** Attribution-corrected popularity (BS#1486 Phase-2 Track 3): a play count for this row's LOGICAL album rather than this single pressing. Pressings that resolve to the same Discogs master (~90% of RESOLVED library rows) collapse into one count; release-only and unresolved rows keep a per-release or per-library key, with no cross-pressing collapse. It also adds the free-text/unlinked plays Track 1 has resolved to the same release/master (the ~43% free-text tail is the ceiling, not all of it — only the resolved subset counts), which the linked-only `plays` cannot see. Rank releases by `popularity`. null when the album_popularity signal has no row for this row's logical key. Distinct from `plays`, which stays the per-pressing linked count.  */
    public var popularity: Int?
    /** Album cover URL from Discogs; null if not yet fetched. */
    public var artworkUrl: String?
    /** RAW current-rotation bin — the most-recently-ADDED rotation record for this album — NOT the CURRENT_DATE-filtered value AlbumSearchResult returns. Nominal values are H/M/L/S (see RotationBin) but it is typed as a free string, NOT the RotationBin enum, so a value outside those cohorts (e.g. 'N', a current server-enum member — NOT legacy) cannot break a strict-enum decoder. Evaluate live rotation client-side together with rotation_kill_date:   in rotation  ==  rotation_bin != null                   AND (rotation_kill_date == null                        OR rotation_kill_date > today-in-client-tz) The daily kill-date expiry is a clock event no DB trigger can observe, which is why this endpoint ships raw and defers expiry to the client.  */
    public var rotationBin: String?
    /** Date (YYYY-MM-DD; server ::text cast) the current rotation record expires, or null if it has none. Used with rotation_bin to evaluate live rotation client-side. Absent from AlbumSearchResult — a client that reuses AlbumSearchResult for this endpoint silently loses it.  */
    public var rotationKillDate: Date?

    public init(id: Int, artistName: String, albumTitle: String, codeLetters: String, codeNumber: Int, codeArtistNumber: Int, label: String? = nil, genreName: String, formatName: String, onStreaming: Bool? = nil, plays: Int? = nil, popularity: Int? = nil, artworkUrl: String? = nil, rotationBin: String? = nil, rotationKillDate: Date? = nil) {
        self.id = id
        self.artistName = artistName
        self.albumTitle = albumTitle
        self.codeLetters = codeLetters
        self.codeNumber = codeNumber
        self.codeArtistNumber = codeArtistNumber
        self.label = label
        self.genreName = genreName
        self.formatName = formatName
        self.onStreaming = onStreaming
        self.plays = plays
        self.popularity = popularity
        self.artworkUrl = artworkUrl
        self.rotationBin = rotationBin
        self.rotationKillDate = rotationKillDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case artistName = "artist_name"
        case albumTitle = "album_title"
        case codeLetters = "code_letters"
        case codeNumber = "code_number"
        case codeArtistNumber = "code_artist_number"
        case label
        case genreName = "genre_name"
        case formatName = "format_name"
        case onStreaming = "on_streaming"
        case plays
        case popularity
        case artworkUrl = "artwork_url"
        case rotationBin = "rotation_bin"
        case rotationKillDate = "rotation_kill_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(artistName, forKey: .artistName)
        try container.encode(albumTitle, forKey: .albumTitle)
        try container.encode(codeLetters, forKey: .codeLetters)
        try container.encode(codeNumber, forKey: .codeNumber)
        try container.encode(codeArtistNumber, forKey: .codeArtistNumber)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encode(genreName, forKey: .genreName)
        try container.encode(formatName, forKey: .formatName)
        try container.encodeIfPresent(onStreaming, forKey: .onStreaming)
        try container.encodeIfPresent(plays, forKey: .plays)
        try container.encodeIfPresent(popularity, forKey: .popularity)
        try container.encodeIfPresent(artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(rotationBin, forKey: .rotationBin)
        try container.encodeIfPresent(rotationKillDate, forKey: .rotationKillDate)
    }
}

