//
// CatalogCompilationTrackRow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One compilation_track_artist (CTA) row as served by GET /library/catalog/compilation-tracks for the Backend-sourced library.db producer (BS#1965 / discogs-etl#351). The sibling of CatalogExportRow: where that endpoint feeds library.db&#39;s &#x60;library&#x60; table, this feeds its &#x60;compilation_track_artist&#x60; table (3 columns: library_release_id, artist_name, track_title). Keyed on legacy_release_id — the library row&#39;s surrogate key that the producer also emits AS library.db&#39;s library.id — so the producer maps legacy_release_id -&gt; compilation_track_artist.library_release_id. Deliberately drops the CTA row id and track_position: library.db&#39;s 3-column CTA table carries neither, so shipping them would break parity. Distinct from CompilationTrack (the BS#1964 dj-site read shape, which keeps id + track_position and is keyed on the BS serial library_id).  */
public struct CatalogCompilationTrackRow: Sendable, Codable, Hashable {

    public static let artistNameRule = StringRule(minLength: 1, maxLength: 255, pattern: nil)
    public static let trackTitleRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    /** The owning library row's legacy_release_id (BS#1963). Becomes library.db's compilation_track_artist.library_release_id, which joins to library.db's library.id.  */
    public var legacyReleaseId: Int
    /** Per-track performing artist (CTA.artist_name). Bounds mirror CompilationTrackInput and the underlying varchar(255) NOT NULL — the read and write shapes over the same physical column must not disagree about their own constraints, and the producer needs the width to size its SQLite column.  */
    public var artistName: String
    /** Track title; nullable varchar(255), matching the CTA column. */
    public var trackTitle: String?

    public init(legacyReleaseId: Int, artistName: String, trackTitle: String? = nil) {
        self.legacyReleaseId = legacyReleaseId
        self.artistName = artistName
        self.trackTitle = trackTitle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case legacyReleaseId = "legacy_release_id"
        case artistName = "artist_name"
        case trackTitle = "track_title"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(legacyReleaseId, forKey: .legacyReleaseId)
        try container.encode(artistName, forKey: .artistName)
        try container.encodeIfPresent(trackTitle, forKey: .trackTitle)
    }
}

