//
// CompilationTrackSuggestions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Proposed (unwritten) compilation tracklist derived from the linked Discogs release (BS#1964). &#x60;discogs_release_id: null&#x60; + empty &#x60;tracks&#x60; signals no resolvable upstream release -&gt; manual entry.  */
public struct CompilationTrackSuggestions: Sendable, Codable, Hashable {

    public var libraryId: Int
    /** The resolved Discogs release id, or null if none resolved. */
    public var discogsReleaseId: Int?
    public var tracks: [CompilationTrackInput]

    public init(libraryId: Int, discogsReleaseId: Int?, tracks: [CompilationTrackInput]) {
        self.libraryId = libraryId
        self.discogsReleaseId = discogsReleaseId
        self.tracks = tracks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case libraryId = "library_id"
        case discogsReleaseId = "discogs_release_id"
        case tracks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(libraryId, forKey: .libraryId)
        try container.encode(discogsReleaseId, forKey: .discogsReleaseId)
        try container.encode(tracks, forKey: .tracks)
    }
}

