//
// CompilationTracksWriteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Result of an additive CTA write (BS#1964). &#x60;inserted + skipped&#x60; equals the number of input rows — a row that duplicates one already inserted earlier in the same request counts toward &#x60;skipped&#x60; (matched against the just-inserted row on the CTA uniqueness key), so the identity always holds even when the request carries intra-batch duplicates. &#x60;tracks&#x60; is the release&#39;s full stored set after the write.  */
public struct CompilationTracksWriteResponse: Sendable, Codable, Hashable {

    public var libraryId: Int
    /** Rows newly created. */
    public var inserted: Int
    /** Rows already present (matched on a CTA uniqueness key); left untouched. */
    public var skipped: Int
    public var tracks: [CompilationTrack]

    public init(libraryId: Int, inserted: Int, skipped: Int, tracks: [CompilationTrack]) {
        self.libraryId = libraryId
        self.inserted = inserted
        self.skipped = skipped
        self.tracks = tracks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case libraryId = "library_id"
        case inserted
        case skipped
        case tracks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(libraryId, forKey: .libraryId)
        try container.encode(inserted, forKey: .inserted)
        try container.encode(skipped, forKey: .skipped)
        try container.encode(tracks, forKey: .tracks)
    }
}

