//
// CompilationTrackInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A per-track artist entry to write to a compilation (BS#1964). The durable, table-agnostic shape: only the librarian-meaningful free-text fields, so it survives the future compilation_track_artist -&gt; library_track generalization (BS#801), which adds the canonical artist link server-side rather than as a wire field.  */
public struct CompilationTrackInput: Sendable, Codable, Hashable {

    public static let artistNameRule = StringRule(minLength: 1, maxLength: 255, pattern: nil)
    public static let trackTitleRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    public static let trackPositionRule = StringRule(minLength: nil, maxLength: 20, pattern: nil)
    /** Per-track performing artist (CTA.artist_name). */
    public var artistName: String
    /** Track title; nullable, matching the CTA column. */
    public var trackTitle: String?
    /** Sleeve position label, e.g. \"A1\", \"3\". */
    public var trackPosition: String?

    public init(artistName: String, trackTitle: String? = nil, trackPosition: String? = nil) {
        self.artistName = artistName
        self.trackTitle = trackTitle
        self.trackPosition = trackPosition
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artistName = "artist_name"
        case trackTitle = "track_title"
        case trackPosition = "track_position"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artistName, forKey: .artistName)
        try container.encodeIfPresent(trackTitle, forKey: .trackTitle)
        try container.encodeIfPresent(trackPosition, forKey: .trackPosition)
    }
}

