//
// ConcertStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Lifecycle state of a concert as observed at the source. Listener surfaces read this to grey out / strike through cancelled or sold-out shows. */
public enum ConcertStatus: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case onSale = "on_sale"
    case soldOut = "sold_out"
    case cancelled = "cancelled"
    case rescheduled = "rescheduled"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension ConcertStatus: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
