//
// DeviceAuthTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceAuthTokenRequest: Sendable, Codable, Hashable {

    public enum GrantType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case urnIetfParamsOauthGrantTypeDeviceCode = "urn:ietf:params:oauth:grant-type:device_code"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** RFC 8628 device-flow grant type (fixed value). */
    public var grantType: GrantType
    /** The device_code returned by /auth/device/code. */
    public var deviceCode: String
    /** The client ID of the application. */
    public var clientId: String

    public init(grantType: GrantType, deviceCode: String, clientId: String) {
        self.grantType = grantType
        self.deviceCode = deviceCode
        self.clientId = clientId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case grantType = "grant_type"
        case deviceCode = "device_code"
        case clientId = "client_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(grantType, forKey: .grantType)
        try container.encode(deviceCode, forKey: .deviceCode)
        try container.encode(clientId, forKey: .clientId)
    }
}


extension DeviceAuthTokenRequest: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if grantType == .unknownDefaultOpenApi { return true }
        return false
    }
}
