//
// DeviceAuthDenyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceAuthDenyRequest: Sendable, Codable, Hashable {

    /** The user code to deny. NOTE: camelCase on the wire (see DeviceAuthApproveRequest).  */
    public var userCode: String

    public init(userCode: String) {
        self.userCode = userCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userCode, forKey: .userCode)
    }
}

