//
// DeviceAuthCodeError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceAuthCodeError: Sendable, Codable, Hashable {

    public var error: DeviceAuthCodeErrorCode
    public var errorDescription: String

    public init(error: DeviceAuthCodeErrorCode, errorDescription: String) {
        self.error = error
        self.errorDescription = errorDescription
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case errorDescription = "error_description"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
        try container.encode(errorDescription, forKey: .errorDescription)
    }
}


extension DeviceAuthCodeError: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if error == .unknownDefaultOpenApi { return true }
        return false
    }
}
