//
// DeviceAuthCodeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceAuthCodeRequest: Sendable, Codable, Hashable {

    /** The client ID of the application requesting authorization. */
    public var clientId: String
    /** Optional space-separated list of OAuth scopes. */
    public var scope: String?
    /** Optional. The user ID to which the device code should be pre-bound (a better-auth 1.6.20+ plugin field). WXYC's shared-computer QR flow does not send this — the DJ is identified later at /auth/device/approve — but it is mirrored here for runtime fidelity.  */
    public var userId: String?

    public init(clientId: String, scope: String? = nil, userId: String? = nil) {
        self.clientId = clientId
        self.scope = scope
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case scope
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientId, forKey: .clientId)
        try container.encodeIfPresent(scope, forKey: .scope)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}

