//
// DeviceAuthTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceAuthTokenResponse: Sendable, Codable, Hashable {

    public enum TokenType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case bearer = "Bearer"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** The session bearer token for the browser. */
    public var accessToken: String
    public var tokenType: TokenType
    /** Token lifetime in seconds. WXYC's auth-service (Backend-Service#1495, hooks.after on /device/token) rewrites the plugin's session-derived value to a fixed 43200 (12h). The vanilla-plugin value would otherwise be the global ~7-day session TTL.  */
    public var expiresIn: Int
    /** Granted scopes (empty string when none were requested). */
    public var scope: String

    public init(accessToken: String, tokenType: TokenType, expiresIn: Int, scope: String) {
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresIn = expiresIn
        self.scope = scope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresIn = "expires_in"
        case scope
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encode(tokenType, forKey: .tokenType)
        try container.encode(expiresIn, forKey: .expiresIn)
        try container.encode(scope, forKey: .scope)
    }
}


extension DeviceAuthTokenResponse: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if tokenType == .unknownDefaultOpenApi { return true }
        return false
    }
}
