//
// DeviceAuthActionErrorCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Error codes for POST /auth/device/approve and POST /auth/device/deny (shared — both routes emit the same set). &#x60;device_code_already_processed&#x60; is declared in the plugin&#39;s approve zod enum but is NEVER emitted on the wire — the already-processed branch throws &#x60;invalid_request&#x60; — so it is intentionally omitted here (mirror runtime).  */
public enum DeviceAuthActionErrorCode: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case invalidRequest = "invalid_request"
    case expiredToken = "expired_token"
    case unauthorized = "unauthorized"
    case accessDenied = "access_denied"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension DeviceAuthActionErrorCode: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
