//
// DeviceAuthCodeErrorCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Error codes for POST /auth/device/code. */
public enum DeviceAuthCodeErrorCode: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case invalidRequest = "invalid_request"
    case invalidClient = "invalid_client"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension DeviceAuthCodeErrorCode: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
