//
// DeviceAuthVerifyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceAuthVerifyResponse: Sendable, Codable, Hashable {

    public var userCode: String
    public var status: DeviceAuthStatus

    public init(userCode: String, status: DeviceAuthStatus) {
        self.userCode = userCode
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userCode = "user_code"
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userCode, forKey: .userCode)
        try container.encode(status, forKey: .status)
    }
}


extension DeviceAuthVerifyResponse: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
