//
// DeviceRegistration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceRegistration: Sendable, Codable, Hashable {

    public var deviceId: String
    public var registeredAt: Date

    public init(deviceId: String, registeredAt: Date) {
        self.deviceId = deviceId
        self.registeredAt = registeredAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceId = "device_id"
        case registeredAt = "registered_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deviceId, forKey: .deviceId)
        try container.encode(registeredAt, forKey: .registeredAt)
    }
}

