//
// DeviceAuthStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Current status of a device authorization (GET /auth/device). */
public enum DeviceAuthStatus: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case pending = "pending"
    case approved = "approved"
    case denied = "denied"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension DeviceAuthStatus: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
