//
// DigitalArchivePlaybackTrack.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One track of a DigitalArchivePlaybackManifest. The server orders &#x60;tracks&#x60; for the client; disc_number/track_number are informational and nullable rather than a client-side sort key, because partial albums and tag gaps exist in the archive.  */
public struct DigitalArchivePlaybackTrack: Sendable, Codable, Hashable {

    public enum Provenance: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case rotationUpload = "rotation_upload"
        case cdRip = "cd_rip"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** digital_asset_file.id — stable across manifest refetches, for a future offline-cache key. NOT part of any URL; opaque to storage.  */
    public var fileId: Int
    /** Where this track's owning digital asset came from. Per-track rather than per-manifest because a manifest may merge several bound assets for one album — see DigitalArchivePlaybackManifest.  */
    public var provenance: Provenance
    public var discNumber: Int?
    public var trackNumber: Int?
    public var title: String
    public var durationSecs: Double?
    /** MD5 from the store's ETag today; sha256 once CD rips land. Not guaranteed to be either algorithm going forward — treat as an opaque change-detection token, not a verified checksum.  */
    public var contentHash: String?
    /** Every rendition the archive holds for this track, in no guaranteed order. Usually one; a track backfilled to a second format carries both. A client picks whichever codec it can play — do not assume an `mp3` entry is present.  */
    public var renditions: [DigitalArchivePlaybackTrackRenditionsInner]

    public init(fileId: Int, provenance: Provenance, discNumber: Int? = nil, trackNumber: Int? = nil, title: String, durationSecs: Double? = nil, contentHash: String? = nil, renditions: [DigitalArchivePlaybackTrackRenditionsInner]) {
        self.fileId = fileId
        self.provenance = provenance
        self.discNumber = discNumber
        self.trackNumber = trackNumber
        self.title = title
        self.durationSecs = durationSecs
        self.contentHash = contentHash
        self.renditions = renditions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fileId = "file_id"
        case provenance
        case discNumber = "disc_number"
        case trackNumber = "track_number"
        case title
        case durationSecs = "duration_secs"
        case contentHash = "content_hash"
        case renditions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fileId, forKey: .fileId)
        try container.encode(provenance, forKey: .provenance)
        try container.encodeIfPresent(discNumber, forKey: .discNumber)
        try container.encodeIfPresent(trackNumber, forKey: .trackNumber)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(durationSecs, forKey: .durationSecs)
        try container.encodeIfPresent(contentHash, forKey: .contentHash)
        try container.encode(renditions, forKey: .renditions)
    }
}


extension DigitalArchivePlaybackTrack: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if provenance == .unknownDefaultOpenApi { return true }
        return false
    }
}
