//
// DiscogsRelease.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DiscogsRelease: Sendable, Codable, Hashable {

    public var id: Int
    public var title: String
    public var year: Int?
    public var artists: [DiscogsArtistRef]
    public var labels: [DiscogsLabelRef]
    public var genres: [String]
    public var styles: [String]
    public var tracklist: [DiscogsTrack]
    public var images: [DiscogsImage]?

    public init(id: Int, title: String, year: Int? = nil, artists: [DiscogsArtistRef], labels: [DiscogsLabelRef], genres: [String], styles: [String], tracklist: [DiscogsTrack], images: [DiscogsImage]? = nil) {
        self.id = id
        self.title = title
        self.year = year
        self.artists = artists
        self.labels = labels
        self.genres = genres
        self.styles = styles
        self.tracklist = tracklist
        self.images = images
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case year
        case artists
        case labels
        case genres
        case styles
        case tracklist
        case images
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encode(artists, forKey: .artists)
        try container.encode(labels, forKey: .labels)
        try container.encode(genres, forKey: .genres)
        try container.encode(styles, forKey: .styles)
        try container.encode(tracklist, forKey: .tracklist)
        try container.encodeIfPresent(images, forKey: .images)
    }
}

