//
// DiscogsTrackItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A track on a release, with optional per-track artist credits (for compilations). */
public struct DiscogsTrackItem: Sendable, Codable, Hashable {

    public var position: String
    public var title: String
    public var duration: String?
    public var artists: [String]?

    public init(position: String, title: String, duration: String? = nil, artists: [String]? = nil) {
        self.position = position
        self.title = title
        self.duration = duration
        self.artists = artists
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case position
        case title
        case duration
        case artists
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(position, forKey: .position)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(artists, forKey: .artists)
    }
}

