//
// DiscogsTrackReleasesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response from LML&#39;s track-releases search endpoint. */
public struct DiscogsTrackReleasesResponse: Sendable, Codable, Hashable {

    public var track: String?
    public var artist: String?
    public var releases: [DiscogsReleaseInfo]?
    public var total: Int? = 0
    public var cached: Bool? = false

    public init(track: String? = nil, artist: String? = nil, releases: [DiscogsReleaseInfo]? = nil, total: Int? = 0, cached: Bool? = false) {
        self.track = track
        self.artist = artist
        self.releases = releases
        self.total = total
        self.cached = cached
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case track
        case artist
        case releases
        case total
        case cached
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(track, forKey: .track)
        try container.encodeIfPresent(artist, forKey: .artist)
        try container.encodeIfPresent(releases, forKey: .releases)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(cached, forKey: .cached)
    }
}

