//
// DiscogsReleaseMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Full release metadata from LML, including tracklist and enriched credits. */
public struct DiscogsReleaseMetadata: Sendable, Codable, Hashable {

    public var releaseId: Int
    /** Discogs master ID for this release, when the release belongs to a master. `null` when Discogs has no master (one-offs, self-released). Lets a caller collapse multiple pressings/formats of one logical album into a single record keyed on the master.  */
    public var masterId: Int?
    public var title: String
    public var artist: String
    public var year: Int?
    public var label: String?
    public var artistId: Int?
    public var labelId: Int?
    public var genres: [String]?
    public var styles: [String]?
    public var tracklist: [DiscogsTrackItem]?
    public var artworkUrl: String?
    /** Timestamp of the most recent live Discogs API call that resolved this release's artwork. `null` means LML's bulk loader populated the row but the live API has not been queried yet (the \"never asked\" state); a value means LML hit the live API and either populated `artwork_url` or confirmed Discogs has no cover. LML uses this to distinguish bulk-loader gaps (which it back-fills) from genuinely-imageless releases (which it does not refetch). See WXYC/discogs-etl#239 + WXYC/library-metadata-lookup#423.  */
    public var artworkCheckedAt: Date?
    /** Tombstone marker for Discogs 404s on `get_release`. `true` means LML hit the live Discogs API for this release id and Discogs returned 404; subsequent reads short-circuit on this flag rather than re-burning the rate-limit budget. The tombstone row carries `title = \"\"` and `artist = \"\"` as identifier sentinels; consumers must guard against rendering those empty strings as real values. `release_url` is identifier-derived (`https://www.discogs.com/release/{release_id}`) and remains valid even on a tombstone. LML's public boundary translates `not_found = true` back to `None` for direct callers; this flag is observable only by consumers that read the cache row directly (none of which exist in LML's public API today, but the contract is exposed here for future cross-service readers). See WXYC/library-metadata-lookup#510.  */
    public var notFound: Bool? = false
    public var releaseUrl: String
    public var cached: Bool? = false
    public var artists: [DiscogsArtistCredit]?
    public var extraArtists: [DiscogsArtistCredit]?
    public var labels: [DiscogsLabelCredit]?
    /** Release date as ISO string */
    public var released: String?
    public var videos: [DiscogsReleaseVideo]?

    public init(releaseId: Int, masterId: Int? = nil, title: String, artist: String, year: Int? = nil, label: String? = nil, artistId: Int? = nil, labelId: Int? = nil, genres: [String]? = nil, styles: [String]? = nil, tracklist: [DiscogsTrackItem]? = nil, artworkUrl: String? = nil, artworkCheckedAt: Date? = nil, notFound: Bool? = false, releaseUrl: String, cached: Bool? = false, artists: [DiscogsArtistCredit]? = nil, extraArtists: [DiscogsArtistCredit]? = nil, labels: [DiscogsLabelCredit]? = nil, released: String? = nil, videos: [DiscogsReleaseVideo]? = nil) {
        self.releaseId = releaseId
        self.masterId = masterId
        self.title = title
        self.artist = artist
        self.year = year
        self.label = label
        self.artistId = artistId
        self.labelId = labelId
        self.genres = genres
        self.styles = styles
        self.tracklist = tracklist
        self.artworkUrl = artworkUrl
        self.artworkCheckedAt = artworkCheckedAt
        self.notFound = notFound
        self.releaseUrl = releaseUrl
        self.cached = cached
        self.artists = artists
        self.extraArtists = extraArtists
        self.labels = labels
        self.released = released
        self.videos = videos
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case releaseId = "release_id"
        case masterId = "master_id"
        case title
        case artist
        case year
        case label
        case artistId = "artist_id"
        case labelId = "label_id"
        case genres
        case styles
        case tracklist
        case artworkUrl = "artwork_url"
        case artworkCheckedAt = "artwork_checked_at"
        case notFound = "not_found"
        case releaseUrl = "release_url"
        case cached
        case artists
        case extraArtists = "extra_artists"
        case labels
        case released
        case videos
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(releaseId, forKey: .releaseId)
        try container.encodeIfPresent(masterId, forKey: .masterId)
        try container.encode(title, forKey: .title)
        try container.encode(artist, forKey: .artist)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(artistId, forKey: .artistId)
        try container.encodeIfPresent(labelId, forKey: .labelId)
        try container.encodeIfPresent(genres, forKey: .genres)
        try container.encodeIfPresent(styles, forKey: .styles)
        try container.encodeIfPresent(tracklist, forKey: .tracklist)
        try container.encodeIfPresent(artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(artworkCheckedAt, forKey: .artworkCheckedAt)
        try container.encodeIfPresent(notFound, forKey: .notFound)
        try container.encode(releaseUrl, forKey: .releaseUrl)
        try container.encodeIfPresent(cached, forKey: .cached)
        try container.encodeIfPresent(artists, forKey: .artists)
        try container.encodeIfPresent(extraArtists, forKey: .extraArtists)
        try container.encodeIfPresent(labels, forKey: .labels)
        try container.encodeIfPresent(released, forKey: .released)
        try container.encodeIfPresent(videos, forKey: .videos)
    }
}

