//
// DiscogsSearchResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DiscogsSearchResult: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case release = "release"
        case master = "master"
        case artist = "artist"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var id: Int
    public var title: String
    public var year: Int?
    public var thumb: String?
    public var coverImage: String?
    public var resourceUrl: String
    public var type: ModelType

    public init(id: Int, title: String, year: Int? = nil, thumb: String? = nil, coverImage: String? = nil, resourceUrl: String, type: ModelType) {
        self.id = id
        self.title = title
        self.year = year
        self.thumb = thumb
        self.coverImage = coverImage
        self.resourceUrl = resourceUrl
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case year
        case thumb
        case coverImage = "cover_image"
        case resourceUrl = "resource_url"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(thumb, forKey: .thumb)
        try container.encodeIfPresent(coverImage, forKey: .coverImage)
        try container.encode(resourceUrl, forKey: .resourceUrl)
        try container.encode(type, forKey: .type)
    }
}


extension DiscogsSearchResult: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        return false
    }
}
