//
// DiscogsArtistCredit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** An artist credit on a release (performer, producer, etc.). */
public struct DiscogsArtistCredit: Sendable, Codable, Hashable {

    public var artistId: Int?
    public var name: String
    /** Join phrase (e.g. \" & \", \", \") */
    public var join: String? = ""
    /** Role for extra artists (e.g. \"Producer\", \"Mixed By\") */
    public var role: String?

    public init(artistId: Int? = nil, name: String, join: String? = "", role: String? = nil) {
        self.artistId = artistId
        self.name = name
        self.join = join
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artistId = "artist_id"
        case name
        case join
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(artistId, forKey: .artistId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(join, forKey: .join)
        try container.encodeIfPresent(role, forKey: .role)
    }
}

