//
// DiscogsResolvedToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single resolved token from Discogs markup parsing. Discriminated by the &#x60;type&#x60; field. */
public struct DiscogsResolvedToken: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case plaintext = "plainText"
        case artistlink = "artistLink"
        case labelname = "labelName"
        case releaselink = "releaseLink"
        case masterlink = "masterLink"
        case bold = "bold"
        case italic = "italic"
        case underline = "underline"
        case urllink = "urlLink"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    /** Content for plainText tokens */
    public var text: String?
    /** Name for artistLink and labelName tokens */
    public var name: String?
    /** Display name for artistLink tokens (disambiguation suffix stripped) */
    public var displayName: String?
    /** Title for releaseLink and masterLink tokens */
    public var title: String?
    /** URL for artistLink, releaseLink, masterLink tokens */
    public var url: String?
    /** URL for urlLink tokens (null if URL is invalid) */
    public var href: String?
    /** Content for bold, italic, underline, and urlLink tokens */
    public var content: String?

    public init(type: ModelType, text: String? = nil, name: String? = nil, displayName: String? = nil, title: String? = nil, url: String? = nil, href: String? = nil, content: String? = nil) {
        self.type = type
        self.text = text
        self.name = name
        self.displayName = displayName
        self.title = title
        self.url = url
        self.href = href
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case text
        case name
        case displayName = "display_name"
        case title
        case url
        case href
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(href, forKey: .href)
        try container.encodeIfPresent(content, forKey: .content)
    }
}


extension DiscogsResolvedToken: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        return false
    }
}
