//
// DiscogsArtistDetailsMembersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DiscogsArtistDetailsMembersInner: Sendable, Codable, Hashable {

    public var id: Int
    public var name: String
    public var active: Bool? = true

    public init(id: Int, name: String, active: Bool? = true) {
        self.id = id
        self.name = name
        self.active = active
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case active
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(active, forKey: .active)
    }
}

