//
// DiscogsReleaseVideo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DiscogsReleaseVideo: Sendable, Codable, Hashable {

    public var src: String
    public var title: String?
    /** Duration in seconds */
    public var duration: Int?
    public var embed: Bool? = true

    public init(src: String, title: String? = nil, duration: Int? = nil, embed: Bool? = true) {
        self.src = src
        self.title = title
        self.duration = duration
        self.embed = embed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case src
        case title
        case duration
        case embed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(src, forKey: .src)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(embed, forKey: .embed)
    }
}

