//
// DiscogsImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DiscogsImage: Sendable, Codable, Hashable {

    public var type: String
    public var uri: String
    public var width: Int
    public var height: Int

    public init(type: String, uri: String, width: Int, height: Int) {
        self.type = type
        self.uri = uri
        self.width = width
        self.height = height
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case uri
        case width
        case height
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(uri, forKey: .uri)
        try container.encode(width, forKey: .width)
        try container.encode(height, forKey: .height)
    }
}

