//
// DiscogsTrack.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DiscogsTrack: Sendable, Codable, Hashable {

    public var position: String
    public var title: String
    public var duration: String?

    public init(position: String, title: String, duration: String? = nil) {
        self.position = position
        self.title = title
        self.duration = duration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case position
        case title
        case duration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(position, forKey: .position)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(duration, forKey: .duration)
    }
}

