//
// DiscogsArtistDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Full artist details from Discogs, including bio, aliases, and group members. */
public struct DiscogsArtistDetails: Sendable, Codable, Hashable {

    public var artistId: Int
    public var name: String
    public var profile: String?
    /** Pre-parsed structured tokens from the Discogs profile markup */
    public var profileTokens: [DiscogsResolvedToken]?
    public var imageUrl: String?
    public var nameVariations: [String]?
    public var aliases: [DiscogsArtistDetailsAliasesInner]?
    public var members: [DiscogsArtistDetailsMembersInner]?
    public var urls: [String]?
    public var cached: Bool? = false

    public init(artistId: Int, name: String, profile: String? = nil, profileTokens: [DiscogsResolvedToken]? = nil, imageUrl: String? = nil, nameVariations: [String]? = nil, aliases: [DiscogsArtistDetailsAliasesInner]? = nil, members: [DiscogsArtistDetailsMembersInner]? = nil, urls: [String]? = nil, cached: Bool? = false) {
        self.artistId = artistId
        self.name = name
        self.profile = profile
        self.profileTokens = profileTokens
        self.imageUrl = imageUrl
        self.nameVariations = nameVariations
        self.aliases = aliases
        self.members = members
        self.urls = urls
        self.cached = cached
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artistId = "artist_id"
        case name
        case profile
        case profileTokens = "profile_tokens"
        case imageUrl = "image_url"
        case nameVariations = "name_variations"
        case aliases
        case members
        case urls
        case cached
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artistId, forKey: .artistId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(profile, forKey: .profile)
        try container.encodeIfPresent(profileTokens, forKey: .profileTokens)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encodeIfPresent(nameVariations, forKey: .nameVariations)
        try container.encodeIfPresent(aliases, forKey: .aliases)
        try container.encodeIfPresent(members, forKey: .members)
        try container.encodeIfPresent(urls, forKey: .urls)
        try container.encodeIfPresent(cached, forKey: .cached)
    }
}

