//
// DJ.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DJ: Sendable, Codable, Hashable {

    public var id: Int
    public var djName: String
    public var realName: String?
    public var email: String?

    public init(id: Int, djName: String, realName: String? = nil, email: String? = nil) {
        self.id = id
        self.djName = djName
        self.realName = realName
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case djName = "dj_name"
        case realName = "real_name"
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(djName, forKey: .djName)
        try container.encodeIfPresent(realName, forKey: .realName)
        try container.encodeIfPresent(email, forKey: .email)
    }
}

