//
// DJBinResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DJBinResponse: Sendable, Codable, Hashable {

    public var djId: Int
    public var entries: [BinEntry]

    public init(djId: Int, entries: [BinEntry]) {
        self.djId = djId
        self.entries = entries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case djId = "dj_id"
        case entries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(djId, forKey: .djId)
        try container.encode(entries, forKey: .entries)
    }
}

