//
// DJPlaylistsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DJPlaylistsResponse: Sendable, Codable, Hashable {

    public var djId: Int
    public var playlists: [Playlist]

    public init(djId: Int, playlists: [Playlist]) {
        self.djId = djId
        self.playlists = playlists
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case djId = "dj_id"
        case playlists
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(djId, forKey: .djId)
        try container.encode(playlists, forKey: .playlists)
    }
}

