//
// DjsBinPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DjsBinPostRequest: Sendable, Codable, Hashable {

    public var djId: Int
    public var albumId: Int
    public var trackTitle: String?

    public init(djId: Int, albumId: Int, trackTitle: String? = nil) {
        self.djId = djId
        self.albumId = albumId
        self.trackTitle = trackTitle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case djId = "dj_id"
        case albumId = "album_id"
        case trackTitle = "track_title"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(djId, forKey: .djId)
        try container.encode(albumId, forKey: .albumId)
        try container.encodeIfPresent(trackTitle, forKey: .trackTitle)
    }
}

