//
// EmailSignInRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Body for POST /auth/sign-in/email. */
public struct EmailSignInRequest: Sendable, Codable, Hashable {

    public var email: String
    public var password: String
    /** Redirect target after sign-in / email verification. WXYC's native clients never send this — a callbackURL flips `redirect` true in the response and sets a Location header, both meant for a browser.  */
    public var callbackURL: String?
    /** When false, the session is not remembered (shorter-lived cookie). */
    public var rememberMe: Bool? = true

    public init(email: String, password: String, callbackURL: String? = nil, rememberMe: Bool? = true) {
        self.email = email
        self.password = password
        self.callbackURL = callbackURL
        self.rememberMe = rememberMe
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case callbackURL
        case rememberMe
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encodeIfPresent(callbackURL, forKey: .callbackURL)
        try container.encodeIfPresent(rememberMe, forKey: .rememberMe)
    }
}

