//
// EnhancedRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EnhancedRequest: Sendable, Codable, Hashable {

    public var id: Int
    public var deviceId: String
    public var message: String
    public var createdAt: Date
    public var status: RequestStatus
    public var parsed: ParsedSongRequest?
    public var matches: [LibraryMatch]?
    public var artworkUrl: String?
    public var discogsUrl: String?

    public init(id: Int, deviceId: String, message: String, createdAt: Date, status: RequestStatus, parsed: ParsedSongRequest? = nil, matches: [LibraryMatch]? = nil, artworkUrl: String? = nil, discogsUrl: String? = nil) {
        self.id = id
        self.deviceId = deviceId
        self.message = message
        self.createdAt = createdAt
        self.status = status
        self.parsed = parsed
        self.matches = matches
        self.artworkUrl = artworkUrl
        self.discogsUrl = discogsUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case deviceId = "device_id"
        case message
        case createdAt = "created_at"
        case status
        case parsed
        case matches
        case artworkUrl = "artwork_url"
        case discogsUrl = "discogs_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(deviceId, forKey: .deviceId)
        try container.encode(message, forKey: .message)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(parsed, forKey: .parsed)
        try container.encodeIfPresent(matches, forKey: .matches)
        try container.encodeIfPresent(artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(discogsUrl, forKey: .discogsUrl)
    }
}


extension EnhancedRequest: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
