//
// FilingArtist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Either a full new-artist payload (&#x60;kind: create&#x60;) or a reference to an already-catalogued artist (&#x60;kind: existing&#x60;). Discriminated rather than left a bare &#x60;oneOf&#x60; deliberately — the same idiom as &#x60;LiveFsEvent&#x60; and &#x60;AutoDJWebSocketMessage&#x60;: without &#x60;kind&#x60;, a payload carrying both an &#x60;artist_id&#x60; and the new-artist trio validates against both arms, and try-order decoders (the generated Swift and Python clients) silently take the create arm — filing a duplicate artist while reporting success instead of attaching the release to the referenced one. The required &#x60;kind&#x60; makes the caller&#39;s intent explicit on the wire and that ambiguous payload rejectable.  */
public enum FilingArtist: Sendable, Codable, Hashable {
    case typeFilingArtistCreate(FilingArtistCreate)
    case typeFilingArtistExisting(FilingArtistExisting)
    case unknownDefaultOpenApi

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeFilingArtistCreate(let value):
            try container.encode(value)
        case .typeFilingArtistExisting(let value):
            try container.encode(value)
        case .unknownDefaultOpenApi:
            try container.encodeNil()
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case kind = "kind"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .kind)

        switch discriminatorValue {
        case "create":
            self = .typeFilingArtistCreate(try FilingArtistCreate(from: decoder))
        case "existing":
            self = .typeFilingArtistExisting(try FilingArtistExisting(from: decoder))
        default:
            self = .unknownDefaultOpenApi
        }
    }
}

