//
// FilingArtistCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The create arm of &#x60;FilingArtist&#x60;: a full &#x60;AddArtistRequest&#x60; plus the &#x60;kind&#x60; discriminant. Inherits &#x60;AddArtistRequest&#x60;&#39;s field semantics unchanged, including &#x60;code_number&#x60;&#39;s deployed-requirement-vs-#2475-assignment note.  */
public struct FilingArtistCreate: Sendable, Codable, Hashable {

    public enum Kind: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case create = "create"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let codeNumberRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public var artistName: String
    public var codeLetters: String
    public var genreId: Int
    /** Operator-chosen artist call number within the `(genre_id, code_letters)` bucket. The backing column (`genre_artist_crossreference.artist_genre_code`) is a Postgres integer, hence the 2147483647 ceiling — bounded here, at publish time, because oasdiff treats adding request-side bounds later as a breaking change (see `RotationCreateFields.urls`). Declared optional ahead of the Backend-Service relaxation that honors omission (WXYC/Backend-Service#2475): the deployed `POST /library/artists` still 400s on a body without it, so a client must keep sending it until #2475 ships. Once omission is honored, the server assigns the next number in the bucket — the same generator behind Backend's artist-code peek route (`GET /library/artists/peek-code`, a Backend route this contract does not declare) — and this field makes that assignment overridable, it does not replace it.  */
    public var codeNumber: Int?
    public var kind: Kind

    public init(artistName: String, codeLetters: String, genreId: Int, codeNumber: Int? = nil, kind: Kind) {
        self.artistName = artistName
        self.codeLetters = codeLetters
        self.genreId = genreId
        self.codeNumber = codeNumber
        self.kind = kind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artistName = "artist_name"
        case codeLetters = "code_letters"
        case genreId = "genre_id"
        case codeNumber = "code_number"
        case kind
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artistName, forKey: .artistName)
        try container.encode(codeLetters, forKey: .codeLetters)
        try container.encode(genreId, forKey: .genreId)
        try container.encodeIfPresent(codeNumber, forKey: .codeNumber)
        try container.encode(kind, forKey: .kind)
    }
}


extension FilingArtistCreate: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if kind == .unknownDefaultOpenApi { return true }
        return false
    }
}
