//
// FlowsheetEndPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FlowsheetEndPostRequest: Sendable, Codable, Hashable {

    public var djId: Int?

    public init(djId: Int? = nil) {
        self.djId = djId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case djId = "dj_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(djId, forKey: .djId)
    }
}

