//
// FlowsheetRangeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response body of &#x60;GET /flowsheet/range&#x60;. &#x60;shows&#x60; is a deliberate superset: consumers that only need the entry stream (which carries inline &#x60;show_start&#x60; / &#x60;show_end&#x60; markers in &#x60;entry_type&#x60;) can ignore it. */
public struct FlowsheetRangeResponse: Sendable, Codable, Hashable {

    /** Every show overlapping the window, ordered by `start_time` ascending. Empty when the window contains no shows. */
    public var shows: [FlowsheetRangeShow]
    /** Every flowsheet row in the window, ordered by `add_time` ascending and tie-broken on `id` — NOT by `play_order`, which is per-show and interleaves a multi-show window (see the endpoint description). Includes the `show_start` / `show_end` marker rows. Those markers are a convenience, not a guarantee: a show whose `show_end` delivery was dropped has no closing marker (the same failure that leaves `FlowsheetRangeShow.end_time` null), so a consumer that segments purely on markers will run one show's entries into the next. Segment on `show_id` and treat the markers as labels. */
    public var entries: [FlowsheetRangeEntry]

    public init(shows: [FlowsheetRangeShow], entries: [FlowsheetRangeEntry]) {
        self.shows = shows
        self.entries = entries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shows
        case entries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shows, forKey: .shows)
        try container.encode(entries, forKey: .entries)
    }
}

