//
// FlowsheetCreateSongFreeform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FlowsheetCreateSongFreeform: Sendable, Codable, Hashable {

    public var artistName: String
    public var albumTitle: String
    public var trackTitle: String
    public var requestFlag: Bool
    public var segue: Bool?
    public var recordLabel: String?
    public var labelId: Int?
    /** Rotation linkage for a track on a rotation album that isn't in the WXYC library catalog (BS#1308). The Backend snapshot/else branch persists `rotation_id` alongside `album_id IS NULL` so the V2 read path can JOIN back to `rotation` for `rotation_bin` and the iOS rotation-artwork resolver can find the entry. `rotation_bin` is derived on read and intentionally not declared here.  */
    public var rotationId: Int?

    public init(artistName: String, albumTitle: String, trackTitle: String, requestFlag: Bool, segue: Bool? = nil, recordLabel: String? = nil, labelId: Int? = nil, rotationId: Int? = nil) {
        self.artistName = artistName
        self.albumTitle = albumTitle
        self.trackTitle = trackTitle
        self.requestFlag = requestFlag
        self.segue = segue
        self.recordLabel = recordLabel
        self.labelId = labelId
        self.rotationId = rotationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artistName = "artist_name"
        case albumTitle = "album_title"
        case trackTitle = "track_title"
        case requestFlag = "request_flag"
        case segue
        case recordLabel = "record_label"
        case labelId = "label_id"
        case rotationId = "rotation_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artistName, forKey: .artistName)
        try container.encode(albumTitle, forKey: .albumTitle)
        try container.encode(trackTitle, forKey: .trackTitle)
        try container.encode(requestFlag, forKey: .requestFlag)
        try container.encodeIfPresent(segue, forKey: .segue)
        try container.encodeIfPresent(recordLabel, forKey: .recordLabel)
        try container.encodeIfPresent(labelId, forKey: .labelId)
        try container.encodeIfPresent(rotationId, forKey: .rotationId)
    }
}

