//
// FlowsheetEntryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Flowsheet entry as returned by the API with all possible fields */
public struct FlowsheetEntryResponse: Sendable, Codable, Hashable {

    public var id: Int
    public var playOrder: Int
    public var showId: Int
    public var albumId: Int?
    public var trackTitle: String?
    public var albumTitle: String?
    public var artistName: String?
    public var recordLabel: String?
    public var labelId: Int?
    public var rotationId: Int?
    public var rotationBin: RotationBin?
    public var requestFlag: Bool
    public var segue: Bool?
    public var message: String?
    public var artworkUrl: String?
    public var discogsUrl: String?
    public var releaseYear: Int?
    public var spotifyUrl: String?
    public var appleMusicUrl: String?
    public var youtubeMusicUrl: String?
    public var bandcampUrl: String?
    public var soundcloudUrl: String?
    public var artistBio: String?
    public var artistWikipediaUrl: String?
    /** Track position on the release (e.g., \"A1\", \"B2\", \"5\"). Populated when the flowsheet entry was created via the dj-site picker after release selection (catalog-track-search plan §5.3 / Track 3). String-typed to match Discogs's `release_track.position`. Null for free-text entries and legacy rows.  */
    public var trackPosition: String?
    public var metadataStatus: MetadataStatus?
    public var entryType: FlowsheetEntryType?
    /** The instant this row was logged (ISO 8601). */
    public var addTime: Date?
    /** Top-of-hour a breakpoint row marks (ISO 8601), sourced from tubafrenzy's RADIO_HOUR. Null on non-breakpoint rows and rows predating the producer rollout. Mirrors the V2 breakpoint entry. */
    public var radioHour: Date?
    /** Resolved public display name of the DJ on the row's show. Nullable per the PII-safe resolution chain (BS#1371): user.djName -> shows.legacy_dj_name -> null; never the real-name PII column. */
    public var djName: String?

    public init(id: Int, playOrder: Int, showId: Int, albumId: Int? = nil, trackTitle: String? = nil, albumTitle: String? = nil, artistName: String? = nil, recordLabel: String? = nil, labelId: Int? = nil, rotationId: Int? = nil, rotationBin: RotationBin? = nil, requestFlag: Bool, segue: Bool? = nil, message: String? = nil, artworkUrl: String? = nil, discogsUrl: String? = nil, releaseYear: Int? = nil, spotifyUrl: String? = nil, appleMusicUrl: String? = nil, youtubeMusicUrl: String? = nil, bandcampUrl: String? = nil, soundcloudUrl: String? = nil, artistBio: String? = nil, artistWikipediaUrl: String? = nil, trackPosition: String? = nil, metadataStatus: MetadataStatus? = nil, entryType: FlowsheetEntryType? = nil, addTime: Date? = nil, radioHour: Date? = nil, djName: String? = nil) {
        self.id = id
        self.playOrder = playOrder
        self.showId = showId
        self.albumId = albumId
        self.trackTitle = trackTitle
        self.albumTitle = albumTitle
        self.artistName = artistName
        self.recordLabel = recordLabel
        self.labelId = labelId
        self.rotationId = rotationId
        self.rotationBin = rotationBin
        self.requestFlag = requestFlag
        self.segue = segue
        self.message = message
        self.artworkUrl = artworkUrl
        self.discogsUrl = discogsUrl
        self.releaseYear = releaseYear
        self.spotifyUrl = spotifyUrl
        self.appleMusicUrl = appleMusicUrl
        self.youtubeMusicUrl = youtubeMusicUrl
        self.bandcampUrl = bandcampUrl
        self.soundcloudUrl = soundcloudUrl
        self.artistBio = artistBio
        self.artistWikipediaUrl = artistWikipediaUrl
        self.trackPosition = trackPosition
        self.metadataStatus = metadataStatus
        self.entryType = entryType
        self.addTime = addTime
        self.radioHour = radioHour
        self.djName = djName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case playOrder = "play_order"
        case showId = "show_id"
        case albumId = "album_id"
        case trackTitle = "track_title"
        case albumTitle = "album_title"
        case artistName = "artist_name"
        case recordLabel = "record_label"
        case labelId = "label_id"
        case rotationId = "rotation_id"
        case rotationBin = "rotation_bin"
        case requestFlag = "request_flag"
        case segue
        case message
        case artworkUrl = "artwork_url"
        case discogsUrl = "discogs_url"
        case releaseYear = "release_year"
        case spotifyUrl = "spotify_url"
        case appleMusicUrl = "apple_music_url"
        case youtubeMusicUrl = "youtube_music_url"
        case bandcampUrl = "bandcamp_url"
        case soundcloudUrl = "soundcloud_url"
        case artistBio = "artist_bio"
        case artistWikipediaUrl = "artist_wikipedia_url"
        case trackPosition = "track_position"
        case metadataStatus = "metadata_status"
        case entryType = "entry_type"
        case addTime = "add_time"
        case radioHour = "radio_hour"
        case djName = "dj_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(playOrder, forKey: .playOrder)
        try container.encode(showId, forKey: .showId)
        try container.encodeIfPresent(albumId, forKey: .albumId)
        try container.encodeIfPresent(trackTitle, forKey: .trackTitle)
        try container.encodeIfPresent(albumTitle, forKey: .albumTitle)
        try container.encodeIfPresent(artistName, forKey: .artistName)
        try container.encodeIfPresent(recordLabel, forKey: .recordLabel)
        try container.encodeIfPresent(labelId, forKey: .labelId)
        try container.encodeIfPresent(rotationId, forKey: .rotationId)
        try container.encodeIfPresent(rotationBin, forKey: .rotationBin)
        try container.encode(requestFlag, forKey: .requestFlag)
        try container.encodeIfPresent(segue, forKey: .segue)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(discogsUrl, forKey: .discogsUrl)
        try container.encodeIfPresent(releaseYear, forKey: .releaseYear)
        try container.encodeIfPresent(spotifyUrl, forKey: .spotifyUrl)
        try container.encodeIfPresent(appleMusicUrl, forKey: .appleMusicUrl)
        try container.encodeIfPresent(youtubeMusicUrl, forKey: .youtubeMusicUrl)
        try container.encodeIfPresent(bandcampUrl, forKey: .bandcampUrl)
        try container.encodeIfPresent(soundcloudUrl, forKey: .soundcloudUrl)
        try container.encodeIfPresent(artistBio, forKey: .artistBio)
        try container.encodeIfPresent(artistWikipediaUrl, forKey: .artistWikipediaUrl)
        try container.encodeIfPresent(trackPosition, forKey: .trackPosition)
        try container.encodeIfPresent(metadataStatus, forKey: .metadataStatus)
        try container.encodeIfPresent(entryType, forKey: .entryType)
        try container.encodeIfPresent(addTime, forKey: .addTime)
        try container.encodeIfPresent(radioHour, forKey: .radioHour)
        try container.encodeIfPresent(djName, forKey: .djName)
    }
}


extension FlowsheetEntryResponse: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if rotationBin == .unknownDefaultOpenApi { return true }
        if metadataStatus == .unknownDefaultOpenApi { return true }
        if entryType == .unknownDefaultOpenApi { return true }
        return false
    }
}
