//
// FlowsheetCreateSongFromCatalog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FlowsheetCreateSongFromCatalog: Sendable, Codable, Hashable {

    public var albumId: Int
    public var trackTitle: String
    /** Track position on the release (e.g., \"A1\", \"B2\", \"5\", \"1-12\"). Written by the dj-site flowsheet picker (catalog-track-search plan §5.3 / Track 3) when the DJ selects a track from the resolved release. Omitted when the DJ enters a free-text track_title without a tracklist lookup or when the release has no resolvable identity. String-typed to match Discogs's `release_track.position` (vinyl side notation, multi-disc prefixes).  */
    public var trackPosition: String?
    public var rotationId: Int?
    public var requestFlag: Bool
    public var segue: Bool?
    public var recordLabel: String?

    public init(albumId: Int, trackTitle: String, trackPosition: String? = nil, rotationId: Int? = nil, requestFlag: Bool, segue: Bool? = nil, recordLabel: String? = nil) {
        self.albumId = albumId
        self.trackTitle = trackTitle
        self.trackPosition = trackPosition
        self.rotationId = rotationId
        self.requestFlag = requestFlag
        self.segue = segue
        self.recordLabel = recordLabel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albumId = "album_id"
        case trackTitle = "track_title"
        case trackPosition = "track_position"
        case rotationId = "rotation_id"
        case requestFlag = "request_flag"
        case segue
        case recordLabel = "record_label"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(albumId, forKey: .albumId)
        try container.encode(trackTitle, forKey: .trackTitle)
        try container.encodeIfPresent(trackPosition, forKey: .trackPosition)
        try container.encodeIfPresent(rotationId, forKey: .rotationId)
        try container.encode(requestFlag, forKey: .requestFlag)
        try container.encodeIfPresent(segue, forKey: .segue)
        try container.encodeIfPresent(recordLabel, forKey: .recordLabel)
    }
}

