//
// FlowsheetRangeEntryBase.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Identity block for &#x60;GET /flowsheet/range&#x60;. Identical to &#x60;FlowsheetEntryBase&#x60; except that &#x60;show_id&#x60; is nullable — see that property&#39;s description. Kept separate rather than relaxing &#x60;FlowsheetEntryBase&#x60; in place so the other flowsheet paths&#39; documented shapes are untouched by this endpoint. */
public struct FlowsheetRangeEntryBase: Sendable, Codable, Hashable {

    public var id: Int
    public var playOrder: Int
    /** The show this entry belongs to, or `null` for an **unattributed** entry — a row that exists with no linked show. 20 of 2,619,011 rows are in that state (2005-02-06 → 2026-04-21), and the Phase 0 audit for the tubafrenzy decommissioning decided against backfilling them, so this endpoint returns them rather than dropping them. Consumers that group entries by show must render an unattributed bucket; they must not assume every entry joins to a member of `shows`, and must not crash on the null. The key is always present. */
    public var showId: Int?

    public init(id: Int, playOrder: Int, showId: Int?) {
        self.id = id
        self.playOrder = playOrder
        self.showId = showId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case playOrder = "play_order"
        case showId = "show_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(playOrder, forKey: .playOrder)
        try container.encode(showId, forKey: .showId)
    }
}

