//
// FlowsheetGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum FlowsheetGet200Response: Sendable, Codable, Hashable {
    case typeFlowsheetV2PaginatedResponse(FlowsheetV2PaginatedResponse)
    case typeArrayOfFlowsheetV2Entry([FlowsheetV2Entry])
    case unknownDefaultOpenApi

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeFlowsheetV2PaginatedResponse(let value):
            try container.encode(value)
        case .typeArrayOfFlowsheetV2Entry(let value):
            try container.encode(value)
        case .unknownDefaultOpenApi:
            try container.encodeNil()
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(FlowsheetV2PaginatedResponse.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeFlowsheetV2PaginatedResponse(value)
        } else if let value = try? container.decode([FlowsheetV2Entry].self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeArrayOfFlowsheetV2Entry(value)
        } else {
            self = .unknownDefaultOpenApi
        }
    }
}

