//
// FlowsheetEntryType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Discriminator for V2 flowsheet entry types */
public enum FlowsheetEntryType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case track = "track"
    case showStart = "show_start"
    case showEnd = "show_end"
    case djJoin = "dj_join"
    case djLeave = "dj_leave"
    case talkset = "talkset"
    case breakpoint = "breakpoint"
    case message = "message"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension FlowsheetEntryType: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
