//
// FlowsheetV2TalksetEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** V2 talkset entry - DJ talk segment */
public struct FlowsheetV2TalksetEntry: Sendable, Codable, Hashable {

    public enum EntryType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case talkset = "talkset"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var id: Int
    public var showId: Int?
    public var playOrder: Int
    public var addTime: Date
    public var entryType: EntryType
    public var message: String

    public init(id: Int, showId: Int?, playOrder: Int, addTime: Date, entryType: EntryType, message: String) {
        self.id = id
        self.showId = showId
        self.playOrder = playOrder
        self.addTime = addTime
        self.entryType = entryType
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case showId = "show_id"
        case playOrder = "play_order"
        case addTime = "add_time"
        case entryType = "entry_type"
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(showId, forKey: .showId)
        try container.encode(playOrder, forKey: .playOrder)
        try container.encode(addTime, forKey: .addTime)
        try container.encode(entryType, forKey: .entryType)
        try container.encode(message, forKey: .message)
    }
}


extension FlowsheetV2TalksetEntry: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if entryType == .unknownDefaultOpenApi { return true }
        return false
    }
}
