//
// FlowsheetV2BreakpointEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** V2 breakpoint entry - hour marker */
public struct FlowsheetV2BreakpointEntry: Sendable, Codable, Hashable {

    public enum EntryType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case breakpoint = "breakpoint"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var id: Int
    public var showId: Int?
    public var playOrder: Int
    public var addTime: Date
    public var entryType: EntryType
    /** Exact top-of-hour this breakpoint marks (ISO 8601), sourced from tubafrenzy's RADIO_HOUR. Distinct from `add_time`, which is the row's logging instant (~1 min before the hour). Optional and nullable: absent on servers predating the producer rollout, null for breakpoint rows not yet backfilled. Clients use `radio_hour` for the hour-marker label when present and fall back to `add_time` otherwise. */
    public var radioHour: Date?
    public var message: String?

    public init(id: Int, showId: Int?, playOrder: Int, addTime: Date, entryType: EntryType, radioHour: Date? = nil, message: String? = nil) {
        self.id = id
        self.showId = showId
        self.playOrder = playOrder
        self.addTime = addTime
        self.entryType = entryType
        self.radioHour = radioHour
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case showId = "show_id"
        case playOrder = "play_order"
        case addTime = "add_time"
        case entryType = "entry_type"
        case radioHour = "radio_hour"
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(showId, forKey: .showId)
        try container.encode(playOrder, forKey: .playOrder)
        try container.encode(addTime, forKey: .addTime)
        try container.encode(entryType, forKey: .entryType)
        try container.encodeIfPresent(radioHour, forKey: .radioHour)
        try container.encodeIfPresent(message, forKey: .message)
    }
}


extension FlowsheetV2BreakpointEntry: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if entryType == .unknownDefaultOpenApi { return true }
        return false
    }
}
