//
// FlowsheetPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum FlowsheetPostRequest: Sendable, Codable, Hashable {
    case typeFlowsheetCreateMessage(FlowsheetCreateMessage)
    case typeFlowsheetCreateSongFreeform(FlowsheetCreateSongFreeform)
    case typeFlowsheetCreateSongFromCatalog(FlowsheetCreateSongFromCatalog)
    case unknownDefaultOpenApi

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeFlowsheetCreateMessage(let value):
            try container.encode(value)
        case .typeFlowsheetCreateSongFreeform(let value):
            try container.encode(value)
        case .typeFlowsheetCreateSongFromCatalog(let value):
            try container.encode(value)
        case .unknownDefaultOpenApi:
            try container.encodeNil()
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(FlowsheetCreateMessage.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeFlowsheetCreateMessage(value)
        } else if let value = try? container.decode(FlowsheetCreateSongFreeform.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeFlowsheetCreateSongFreeform(value)
        } else if let value = try? container.decode(FlowsheetCreateSongFromCatalog.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeFlowsheetCreateSongFromCatalog(value)
        } else {
            self = .unknownDefaultOpenApi
        }
    }
}

