//
// FlowsheetV2Base.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Base fields shared by all V2 flowsheet entries */
public struct FlowsheetV2Base: Sendable, Codable, Hashable {

    public var id: Int
    public var showId: Int?
    public var playOrder: Int
    public var addTime: Date

    public init(id: Int, showId: Int?, playOrder: Int, addTime: Date) {
        self.id = id
        self.showId = showId
        self.playOrder = playOrder
        self.addTime = addTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case showId = "show_id"
        case playOrder = "play_order"
        case addTime = "add_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(showId, forKey: .showId)
        try container.encode(playOrder, forKey: .playOrder)
        try container.encode(addTime, forKey: .addTime)
    }
}

