//
// FlowsheetMessageEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Message entry (talkset, etc.) */
public struct FlowsheetMessageEntry: Sendable, Codable, Hashable {

    public var id: Int
    public var playOrder: Int
    public var showId: Int
    public var message: String

    public init(id: Int, playOrder: Int, showId: Int, message: String) {
        self.id = id
        self.playOrder = playOrder
        self.showId = showId
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case playOrder = "play_order"
        case showId = "show_id"
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(playOrder, forKey: .playOrder)
        try container.encode(showId, forKey: .showId)
        try container.encode(message, forKey: .message)
    }
}

