//
// FlowsheetV2Base.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Base fields shared by all V2 flowsheet entries */
public struct FlowsheetV2Base: Sendable, Codable, Hashable {

    public var id: Int
    /** The show this entry belongs to, or `null` for an **unattributed** entry — a row that exists with no linked show. 20 of 2,619,011 rows are in that state (2005-02-06 → 2026-04-21), and the Phase 0 audit for the tubafrenzy decommissioning decided against backfilling them, so every read that can reach a historical row can reach a null here. Consumers that group entries by show must render an unattributed bucket; they must not assume every entry joins to a show, and must not crash on the null. The key is always present. */
    public var showId: Int?
    public var playOrder: Int
    public var addTime: Date

    public init(id: Int, showId: Int?, playOrder: Int, addTime: Date) {
        self.id = id
        self.showId = showId
        self.playOrder = playOrder
        self.addTime = addTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case showId = "show_id"
        case playOrder = "play_order"
        case addTime = "add_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(showId, forKey: .showId)
        try container.encode(playOrder, forKey: .playOrder)
        try container.encode(addTime, forKey: .addTime)
    }
}

