//
// FlowsheetV2TrackEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** V2 track entry - a song that was played */
public struct FlowsheetV2TrackEntry: Sendable, Codable, Hashable {

    public enum EntryType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case track = "track"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var id: Int
    public var showId: Int?
    public var playOrder: Int
    public var addTime: Date
    public var entryType: EntryType
    public var albumId: Int?
    public var rotationId: Int?
    /** The played release's resolved WXYC catalog artist id (`flowsheet.album_id → library.artist_id`), computed server-side on the same join that powers `upcoming_show`. Shares the catalog artist-id keyspace with `Concert.headlining_artist_id` and `SimilarArtist.artist_id`, so on-device features — the On Tour likes match — can intersect a liked playcut's artist against concert headliners and their affinity neighbors in one id space.  Null for free-form entries (no `album_id`) and for library rows whose album has no linked artist. Additive and optional: older app builds that don't decode it are unaffected.  */
    public var artistId: Int?
    public var artistName: String?
    public var albumTitle: String?
    public var trackTitle: String?
    /** Track position on the release (e.g., \"A1\", \"B2\", \"5\", \"1-12\"). Set by the dj-site flowsheet picker (catalog-track-search plan §5.3 / Track 3) when the DJ selected a track from the resolved release; null when the track_title was entered free-form or the release had no resolvable identity. String-typed to match Discogs's `release_track.position`.  */
    public var trackPosition: String?
    public var recordLabel: String?
    public var requestFlag: Bool
    public var segue: Bool?
    public var rotationBin: RotationBin?
    public var artworkUrl: String?
    public var discogsUrl: String?
    public var releaseYear: Int?
    public var spotifyUrl: String?
    public var appleMusicUrl: String?
    public var youtubeMusicUrl: String?
    public var bandcampUrl: String?
    public var soundcloudUrl: String?
    public var artistBio: String?
    public var artistWikipediaUrl: String?
    /** Whether this album is available on streaming platforms. False means WXYC library exclusive. Null if unknown. */
    public var onStreaming: Bool?
    public var metadataStatus: MetadataStatus?
    /** Discogs genre tags surfaced on the Playcut Detail card. */
    public var genres: [String]?
    /** Discogs style tags (finer-grained than genres). */
    public var styles: [String]?
    /** An optional embedded upcoming Triangle-area concert whose headliner is this track's resolved catalog artist, attached server-side at feed-assembly time so the iOS \"On Tour\" Box Office CTA renders inline with no second round-trip.  Match rule (mirrors `GET /concerts?curated=true`): the track's resolved artist — `flowsheet.album_id → library.artist_id` — is matched against `concerts.headlining_artist_id` on curated, non-tombstoned, upcoming rows (`headlining_artist_id IS NOT NULL`, `removed_at IS NULL`, `starts_on >= today` America/New_York). When an artist has several upcoming dates the **soonest** wins (`ORDER BY starts_on ASC LIMIT 1`), so at most one concert rides each playcut.  Absent/null when the track has no resolved artist (free-form entries with no `album_id`, or an `album_id` whose library row has no matched artist) or when that artist has no curated upcoming date. The field is additive and optional — older app builds that don't decode it are unaffected. Reuses the `Concert` schema verbatim so iOS decodes one type across the On Tour tab and the playcut CTA; the `BoxOfficeTicketPresenter` reads `id`, `title` / `headlining_artist_raw`, `venue` (name + city), `starts_on`, `doors_at`, `status`, `price_min` / `price_max`, `ticket_url`, and `image_url` off it.  */
    public var upcomingShow: Concert?

    public init(id: Int, showId: Int?, playOrder: Int, addTime: Date, entryType: EntryType, albumId: Int? = nil, rotationId: Int? = nil, artistId: Int? = nil, artistName: String? = nil, albumTitle: String? = nil, trackTitle: String? = nil, trackPosition: String? = nil, recordLabel: String? = nil, requestFlag: Bool, segue: Bool? = nil, rotationBin: RotationBin? = nil, artworkUrl: String? = nil, discogsUrl: String? = nil, releaseYear: Int? = nil, spotifyUrl: String? = nil, appleMusicUrl: String? = nil, youtubeMusicUrl: String? = nil, bandcampUrl: String? = nil, soundcloudUrl: String? = nil, artistBio: String? = nil, artistWikipediaUrl: String? = nil, onStreaming: Bool? = nil, metadataStatus: MetadataStatus? = nil, genres: [String]? = nil, styles: [String]? = nil, upcomingShow: Concert? = nil) {
        self.id = id
        self.showId = showId
        self.playOrder = playOrder
        self.addTime = addTime
        self.entryType = entryType
        self.albumId = albumId
        self.rotationId = rotationId
        self.artistId = artistId
        self.artistName = artistName
        self.albumTitle = albumTitle
        self.trackTitle = trackTitle
        self.trackPosition = trackPosition
        self.recordLabel = recordLabel
        self.requestFlag = requestFlag
        self.segue = segue
        self.rotationBin = rotationBin
        self.artworkUrl = artworkUrl
        self.discogsUrl = discogsUrl
        self.releaseYear = releaseYear
        self.spotifyUrl = spotifyUrl
        self.appleMusicUrl = appleMusicUrl
        self.youtubeMusicUrl = youtubeMusicUrl
        self.bandcampUrl = bandcampUrl
        self.soundcloudUrl = soundcloudUrl
        self.artistBio = artistBio
        self.artistWikipediaUrl = artistWikipediaUrl
        self.onStreaming = onStreaming
        self.metadataStatus = metadataStatus
        self.genres = genres
        self.styles = styles
        self.upcomingShow = upcomingShow
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case showId = "show_id"
        case playOrder = "play_order"
        case addTime = "add_time"
        case entryType = "entry_type"
        case albumId = "album_id"
        case rotationId = "rotation_id"
        case artistId = "artist_id"
        case artistName = "artist_name"
        case albumTitle = "album_title"
        case trackTitle = "track_title"
        case trackPosition = "track_position"
        case recordLabel = "record_label"
        case requestFlag = "request_flag"
        case segue
        case rotationBin = "rotation_bin"
        case artworkUrl = "artwork_url"
        case discogsUrl = "discogs_url"
        case releaseYear = "release_year"
        case spotifyUrl = "spotify_url"
        case appleMusicUrl = "apple_music_url"
        case youtubeMusicUrl = "youtube_music_url"
        case bandcampUrl = "bandcamp_url"
        case soundcloudUrl = "soundcloud_url"
        case artistBio = "artist_bio"
        case artistWikipediaUrl = "artist_wikipedia_url"
        case onStreaming = "on_streaming"
        case metadataStatus = "metadata_status"
        case genres
        case styles
        case upcomingShow = "upcoming_show"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(showId, forKey: .showId)
        try container.encode(playOrder, forKey: .playOrder)
        try container.encode(addTime, forKey: .addTime)
        try container.encode(entryType, forKey: .entryType)
        try container.encodeIfPresent(albumId, forKey: .albumId)
        try container.encodeIfPresent(rotationId, forKey: .rotationId)
        try container.encodeIfPresent(artistId, forKey: .artistId)
        try container.encodeIfPresent(artistName, forKey: .artistName)
        try container.encodeIfPresent(albumTitle, forKey: .albumTitle)
        try container.encodeIfPresent(trackTitle, forKey: .trackTitle)
        try container.encodeIfPresent(trackPosition, forKey: .trackPosition)
        try container.encodeIfPresent(recordLabel, forKey: .recordLabel)
        try container.encode(requestFlag, forKey: .requestFlag)
        try container.encodeIfPresent(segue, forKey: .segue)
        try container.encodeIfPresent(rotationBin, forKey: .rotationBin)
        try container.encodeIfPresent(artworkUrl, forKey: .artworkUrl)
        try container.encodeIfPresent(discogsUrl, forKey: .discogsUrl)
        try container.encodeIfPresent(releaseYear, forKey: .releaseYear)
        try container.encodeIfPresent(spotifyUrl, forKey: .spotifyUrl)
        try container.encodeIfPresent(appleMusicUrl, forKey: .appleMusicUrl)
        try container.encodeIfPresent(youtubeMusicUrl, forKey: .youtubeMusicUrl)
        try container.encodeIfPresent(bandcampUrl, forKey: .bandcampUrl)
        try container.encodeIfPresent(soundcloudUrl, forKey: .soundcloudUrl)
        try container.encodeIfPresent(artistBio, forKey: .artistBio)
        try container.encodeIfPresent(artistWikipediaUrl, forKey: .artistWikipediaUrl)
        try container.encodeIfPresent(onStreaming, forKey: .onStreaming)
        try container.encodeIfPresent(metadataStatus, forKey: .metadataStatus)
        try container.encodeIfPresent(genres, forKey: .genres)
        try container.encodeIfPresent(styles, forKey: .styles)
        try container.encodeIfPresent(upcomingShow, forKey: .upcomingShow)
    }
}


extension FlowsheetV2TrackEntry: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if entryType == .unknownDefaultOpenApi { return true }
        if rotationBin == .unknownDefaultOpenApi { return true }
        if metadataStatus == .unknownDefaultOpenApi { return true }
        return false
    }
}
