//
// FlowsheetBreakpointEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Breakpoint entry (marks time boundaries) */
public struct FlowsheetBreakpointEntry: Sendable, Codable, Hashable {

    public var id: Int
    public var playOrder: Int
    public var showId: Int
    public var message: String
    /** Day string (e.g., \"Monday\") */
    public var day: String
    /** Time string (e.g., \"14:00\") */
    public var time: String

    public init(id: Int, playOrder: Int, showId: Int, message: String, day: String, time: String) {
        self.id = id
        self.playOrder = playOrder
        self.showId = showId
        self.message = message
        self.day = day
        self.time = time
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case playOrder = "play_order"
        case showId = "show_id"
        case message
        case day
        case time
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(playOrder, forKey: .playOrder)
        try container.encode(showId, forKey: .showId)
        try container.encode(message, forKey: .message)
        try container.encode(day, forKey: .day)
        try container.encode(time, forKey: .time)
    }
}

