//
// FlowsheetV2ShowStartEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** V2 show start event - when a show begins */
public struct FlowsheetV2ShowStartEntry: Sendable, Codable, Hashable {

    public enum EntryType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case showStart = "show_start"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var id: Int
    public var showId: Int?
    public var playOrder: Int
    public var addTime: Date
    public var entryType: EntryType
    public var djName: String
    public var timestamp: Date

    public init(id: Int, showId: Int?, playOrder: Int, addTime: Date, entryType: EntryType, djName: String, timestamp: Date) {
        self.id = id
        self.showId = showId
        self.playOrder = playOrder
        self.addTime = addTime
        self.entryType = entryType
        self.djName = djName
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case showId = "show_id"
        case playOrder = "play_order"
        case addTime = "add_time"
        case entryType = "entry_type"
        case djName = "dj_name"
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(showId, forKey: .showId)
        try container.encode(playOrder, forKey: .playOrder)
        try container.encode(addTime, forKey: .addTime)
        try container.encode(entryType, forKey: .entryType)
        try container.encode(djName, forKey: .djName)
        try container.encode(timestamp, forKey: .timestamp)
    }
}


extension FlowsheetV2ShowStartEntry: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if entryType == .unknownDefaultOpenApi { return true }
        return false
    }
}
