//
// FlowsheetCreateMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FlowsheetCreateMessage: Sendable, Codable, Hashable {

    public enum EntryType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case talkset = "talkset"
        case breakpoint = "breakpoint"
        case message = "message"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var message: String
    /** Explicit entry type. If omitted, the backend infers from message content. */
    public var entryType: EntryType?

    public init(message: String, entryType: EntryType? = nil) {
        self.message = message
        self.entryType = entryType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case entryType = "entry_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(entryType, forKey: .entryType)
    }
}


extension FlowsheetCreateMessage: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if entryType == .unknownDefaultOpenApi { return true }
        return false
    }
}
