//
// FlowsheetV2DJLeaveEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** V2 DJ leave event - when a DJ leaves an active show */
public struct FlowsheetV2DJLeaveEntry: Sendable, Codable, Hashable {

    public enum EntryType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case djLeave = "dj_leave"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var id: Int
    /** The show this entry belongs to, or `null` for an **unattributed** entry — a row that exists with no linked show. 20 of 2,619,011 rows are in that state (2005-02-06 → 2026-04-21), and the Phase 0 audit for the tubafrenzy decommissioning decided against backfilling them, so every read that can reach a historical row can reach a null here. Consumers that group entries by show must render an unattributed bucket; they must not assume every entry joins to a show, and must not crash on the null. The key is always present. */
    public var showId: Int?
    public var playOrder: Int
    public var addTime: Date
    public var entryType: EntryType
    /** The public handle (`user.djName`) of the DJ who left, never the DJ's legal name. Unlike the full BS#1371 chain, this does not consult a per-show override or the legacy tubafrenzy handle. */
    public var djName: String

    public init(id: Int, showId: Int?, playOrder: Int, addTime: Date, entryType: EntryType, djName: String) {
        self.id = id
        self.showId = showId
        self.playOrder = playOrder
        self.addTime = addTime
        self.entryType = entryType
        self.djName = djName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case showId = "show_id"
        case playOrder = "play_order"
        case addTime = "add_time"
        case entryType = "entry_type"
        case djName = "dj_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(showId, forKey: .showId)
        try container.encode(playOrder, forKey: .playOrder)
        try container.encode(addTime, forKey: .addTime)
        try container.encode(entryType, forKey: .entryType)
        try container.encode(djName, forKey: .djName)
    }
}


extension FlowsheetV2DJLeaveEntry: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if entryType == .unknownDefaultOpenApi { return true }
        return false
    }
}
