//
// FlowsheetOnAirGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FlowsheetOnAirGet200Response: Sendable, Codable, Hashable {

    public var id: Int?
    public var isLive: Bool?

    public init(id: Int? = nil, isLive: Bool? = nil) {
        self.id = id
        self.isLive = isLive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case isLive = "is_live"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(isLive, forKey: .isLive)
    }
}

