//
// FlowsheetJoinPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FlowsheetJoinPostRequest: Sendable, Codable, Hashable {

    public static let djNameOverrideRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    public var djId: Int
    /** Required only when starting a new show */
    public var showName: String?
    /** ID of specialty show entry */
    public var specialtyId: Int?
    /** Optional per-show override for the public DJ name. When present and non-empty after trim, supersedes the caller's `auth_user.dj_name`-derived name on the `show_start` marker text, on the `flowsheet.dj_name` column of every entry in this show, and on `shows.legacy_dj_name`. Empty or whitespace-only values are treated as absent. Scoped to the new-show (start-show) path; the co-host /join branch intentionally ignores this field. Max length matches `auth_user.dj_name varchar(255)`.  */
    public var djNameOverride: String?

    public init(djId: Int, showName: String? = nil, specialtyId: Int? = nil, djNameOverride: String? = nil) {
        self.djId = djId
        self.showName = showName
        self.specialtyId = specialtyId
        self.djNameOverride = djNameOverride
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case djId = "dj_id"
        case showName = "show_name"
        case specialtyId = "specialty_id"
        case djNameOverride = "dj_name_override"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(djId, forKey: .djId)
        try container.encodeIfPresent(showName, forKey: .showName)
        try container.encodeIfPresent(specialtyId, forKey: .specialtyId)
        try container.encodeIfPresent(djNameOverride, forKey: .djNameOverride)
    }
}

