//
// FlowsheetV2PaginatedResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FlowsheetV2PaginatedResponse: Sendable, Codable, Hashable {

    public var entries: [V2FlowsheetLatestGet200Response]
    public var page: Int
    public var limit: Int
    /** Total number of entries */
    public var total: Int
    /** Total number of pages */
    public var totalPages: Int
    /** The DJ currently on air, when known. An object with `dj_name` means a named DJ is live; JSON `null` means the station is confirmed on automation (\"Auto DJ\"); the field being absent entirely means the server does not report on-air status (older backends / non-default query branches) and clients should treat it as unknown rather than asserting automation. Not in `required` so absence stays distinct from an explicit `null`.  Codegen note: this three-way distinction (object / null / absent) survives openapi-typescript (`on_air?: OnAirInfo | null`), but a *synthesized* decoder in Swift (Codable `decodeIfPresent`), Kotlin (kotlinx default value), or Python (pydantic `| None = None`) collapses JSON `null` and an absent key into the same value. A consumer that needs the third state must decode by key presence (e.g. Swift's `container.contains` + `decodeNil`), as the iOS app does — do not rely on a generated model to tell `null` from absent. */
    public var onAir: OnAirInfo?

    public init(entries: [V2FlowsheetLatestGet200Response], page: Int, limit: Int, total: Int, totalPages: Int, onAir: OnAirInfo? = nil) {
        self.entries = entries
        self.page = page
        self.limit = limit
        self.total = total
        self.totalPages = totalPages
        self.onAir = onAir
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entries
        case page
        case limit
        case total
        case totalPages
        case onAir = "on_air"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(entries, forKey: .entries)
        try container.encode(page, forKey: .page)
        try container.encode(limit, forKey: .limit)
        try container.encode(total, forKey: .total)
        try container.encode(totalPages, forKey: .totalPages)
        try container.encodeIfPresent(onAir, forKey: .onAir)
    }
}

