//
// Format.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum Format: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case vinyl = "Vinyl"
    case cd = "CD"
    case unknown = "Unknown"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension Format: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
