//
// GenreEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GenreEntry: Sendable, Codable, Hashable {

    public var id: Int
    public var genreName: Genre
    public var codeLetters: String

    public init(id: Int, genreName: Genre, codeLetters: String) {
        self.id = id
        self.genreName = genreName
        self.codeLetters = codeLetters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case genreName = "genre_name"
        case codeLetters = "code_letters"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(genreName, forKey: .genreName)
        try container.encode(codeLetters, forKey: .codeLetters)
    }
}


extension GenreEntry: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if genreName == .unknownDefaultOpenApi { return true }
        return false
    }
}
