//
// HealthCheckResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Liveness response shape for &#x60;GET /health&#x60; (and equivalent) endpoints. Cross-language contract owned by &#x60;wxyc-fastapi&#x60; (Python) and adopted by Backend-Service (Node) via generated TS types.  &#x60;additionalProperties: true&#x60; lets services attach extra fields without breaking consumers; semantic-index, for example, returns &#x60;artist_count&#x60; alongside &#x60;status&#x60;.  */
public struct HealthCheckResponse: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case healthy = "healthy"
        case degraded = "degraded"
        case unhealthy = "unhealthy"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** Service-reported health. `healthy` = fully operational; `degraded` = serving but with reduced capability; `unhealthy` = should not receive traffic.  */
    public var status: Status

    public init(status: Status) {
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
    }

    public var additionalProperties: [String: JSONValue] = [:]

    public subscript(key: String) -> JSONValue? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        status = try container.decode(Status.self, forKey: .status)
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("status")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        additionalProperties = try additionalPropertiesContainer.decodeMap(JSONValue.self, excludedKeys: nonAdditionalPropertyKeys)
    }
}


extension HealthCheckResponse: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
