//
// IdentityMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The matcher method that produced this resolution, drawn from plan §3.4.1&#39;s locked confidence-method enum. The order in this list also reflects descending confidence ceilings (manual &#x3D; 1.00, cross_source_agreement up to 1.00, exact_match &#x3D; 1.00, name_variation 0.90-0.99, member_group 0.80-0.89, alias_match 0.75-0.84, trigram 0.70+, llm 0.60-0.79). Backend&#39;s writer rejects rows where confidence falls outside the method&#39;s locked range (§3.2.2 sanity check).  */
public enum IdentityMethod: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case manual = "manual"
    case crossSourceAgreement = "cross_source_agreement"
    case exactMatch = "exact_match"
    case nameVariation = "name_variation"
    case memberGroup = "member_group"
    case aliasMatch = "alias_match"
    case trigram = "trigram"
    case llm = "llm"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension IdentityMethod: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
