//
// IdentityResolution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One source&#39;s leg of the §3.2.5 cascade for a single library row. Either resolved (&#x60;attempted: true&#x60; and &#x60;external_id&#x60; populated when a match was found, NULL when the source ran but found no match) or skipped (&#x60;attempted: false&#x60; with &#x60;reason&#x60; populated and the rest nullable). The full &#x60;LookupIdentityBlock.resolved&#x60; array is complete (one entry per known source), not sparse — consumers can tell apart \&quot;leg ran, no match\&quot; from \&quot;leg didn&#39;t run\&quot; without guessing.  */
public struct IdentityResolution: Sendable, Codable, Hashable {

    public static let confidenceRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    public var source: IdentitySource
    /** True when this source's leg actually ran (whether or not it found a match). False when it was skipped — `reason` is populated, `external_id`/`method`/`confidence` are NULL.  */
    public var attempted: Bool
    /** The external identifier this leg resolved to (Discogs release ID, MusicBrainz MBID, Wikidata QID, Spotify URI suffix, Apple Music ID, Bandcamp slug). Stored as a string regardless of the source's native type so the API surface is uniform; Backend casts to the per-source column type when writing `library_identity_source`. NULL when `attempted: false`, or when the leg ran but found no match.  */
    public var externalId: String?
    /** The matcher method that produced the resolution. NULL when `attempted: false` or when the leg ran but found no match.  */
    public var method: IdentityMethod?
    /** Confidence in [0, 1]. Must fall within the method's locked range from plan §3.4.1 — Backend's writer rejects rows where confidence is out of range. NULL when `attempted: false` or when the leg ran but found no match.  */
    public var confidence: Double?
    /** Required when `attempted: false`; absent or NULL otherwise.  */
    public var reason: IdentitySkipReason?

    public init(source: IdentitySource, attempted: Bool, externalId: String? = nil, method: IdentityMethod? = nil, confidence: Double? = nil, reason: IdentitySkipReason? = nil) {
        self.source = source
        self.attempted = attempted
        self.externalId = externalId
        self.method = method
        self.confidence = confidence
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
        case attempted
        case externalId = "external_id"
        case method
        case confidence
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(source, forKey: .source)
        try container.encode(attempted, forKey: .attempted)
        try container.encodeIfPresent(externalId, forKey: .externalId)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(confidence, forKey: .confidence)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}


extension IdentityResolution: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if source == .unknownDefaultOpenApi { return true }
        if method == .unknownDefaultOpenApi { return true }
        if reason == .unknownDefaultOpenApi { return true }
        return false
    }
}
