//
// IdentitySkipReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Why a source&#39;s leg of the cascade did not run. Set on &#x60;IdentityResolution.reason&#x60; when &#x60;attempted: false&#x60;. Order is irrelevant; values are mutually exclusive per leg.  */
public enum IdentitySkipReason: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case error = "error"
    case manualOverrideProtected = "manual_override_protected"
    case disabled = "disabled"
    case prerequisiteFailed = "prerequisite_failed"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension IdentitySkipReason: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
