//
// KillRotationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct KillRotationRequest: Sendable, Codable, Hashable {

    public var rotationId: Int
    /** ISO date string, defaults to today */
    public var killDate: Date?

    public init(rotationId: Int, killDate: Date? = nil) {
        self.rotationId = rotationId
        self.killDate = killDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rotationId = "rotation_id"
        case killDate = "kill_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rotationId, forKey: .rotationId)
        try container.encodeIfPresent(killDate, forKey: .killDate)
    }
}

