//
// LibraryFilingConflictReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Discriminator for the &#x60;POST /library/filings&#x60; 409, telling the caller which composed write collided so it can offer the right remedy. Named rather than left inline, pairing with &#x60;LibraryFilingConflictError&#x60; the way &#x60;ShowAlreadyOpenErrorCode&#x60; pairs with &#x60;ShowAlreadyOpenError&#x60;. &#x60;artist_code_conflict&#x60; and &#x60;artist_name_conflict&#x60; are the exact strings the deployed &#x60;POST /library/artists&#x60; controller already answers with — the composite reuses that create path; &#x60;rotation_card_bin_mismatch&#x60; is defined ahead of the Backend-Service implementation for the rotation arm&#39;s card-bin invariant, the same string &#x60;RotationConflictReason&#x60; declares for the direct &#x60;POST /library/rotation&#x60; and &#x60;DELETE /library/rotation/cards/{id}&#x60; 409s (WXYC/Backend-Service#2472, inherited by the composite per WXYC/Backend-Service#2474) — pinned equal by a spec test rather than composed, since OpenAPI enums do not merge cleanly across two purpose-built discriminators.  */
public enum LibraryFilingConflictReason: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case artistCodeConflict = "artist_code_conflict"
    case artistNameConflict = "artist_name_conflict"
    case rotationCardBinMismatch = "rotation_card_bin_mismatch"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension LibraryFilingConflictReason: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
