//
// LibraryCatalogItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single item from the WXYC library catalog. Mirrors request-parser&#39;s LibraryItem with computed properties serialized as regular fields. Library identity is the &#x60;id&#x60; field alone — there is deliberately no &#x60;album_id&#x60;. An &#x60;id&#x60; of &#x60;0&#x60; is the \&quot;no catalog row\&quot; marker: the release is not shelved in the WXYC library, but the result may still carry a real Discogs identity in its &#x60;LookupResultItem.artwork&#x60;. See &#x60;LookupResultItem&#x60; for that row-less shape and its discriminator.  */
public struct LibraryCatalogItem: Sendable, Codable, Hashable {

    /** Unique identifier in the library database. `0` means there is no WXYC catalog row for this result (a row-less / \"(external)\" item, e.g. a Discogs-only library miss); any positive value is a real shelved release.  */
    public var id: Int
    /** Album/release title */
    public var title: String?
    /** Artist name */
    public var artist: String?
    /** Library call letter code */
    public var callLetters: String?
    /** Numeric part of artist classification */
    public var artistCallNumber: Int?
    /** Numeric part of release classification */
    public var releaseCallNumber: Int?
    /** Genre classification */
    public var genre: String?
    /** Physical format (vinyl, CD, etc.) */
    public var format: String?
    /** Record label name from the library catalog */
    public var label: String?
    /** Full call number for shelf lookup, e.g. \"Rock CD ABC 123/45\". Computed from genre, format, call_letters, artist_call_number, and release_call_number.  */
    public var callNumber: String
    /** URL to view this release in the WXYC library */
    public var libraryUrl: String
    /** True if this release is available on at least one streaming service. False means only available in the WXYC physical library. Null if unknown. */
    public var onStreaming: Bool?

    public init(id: Int, title: String? = nil, artist: String? = nil, callLetters: String? = nil, artistCallNumber: Int? = nil, releaseCallNumber: Int? = nil, genre: String? = nil, format: String? = nil, label: String? = nil, callNumber: String, libraryUrl: String, onStreaming: Bool? = nil) {
        self.id = id
        self.title = title
        self.artist = artist
        self.callLetters = callLetters
        self.artistCallNumber = artistCallNumber
        self.releaseCallNumber = releaseCallNumber
        self.genre = genre
        self.format = format
        self.label = label
        self.callNumber = callNumber
        self.libraryUrl = libraryUrl
        self.onStreaming = onStreaming
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case artist
        case callLetters = "call_letters"
        case artistCallNumber = "artist_call_number"
        case releaseCallNumber = "release_call_number"
        case genre
        case format
        case label
        case callNumber = "call_number"
        case libraryUrl = "library_url"
        case onStreaming = "on_streaming"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(artist, forKey: .artist)
        try container.encodeIfPresent(callLetters, forKey: .callLetters)
        try container.encodeIfPresent(artistCallNumber, forKey: .artistCallNumber)
        try container.encodeIfPresent(releaseCallNumber, forKey: .releaseCallNumber)
        try container.encodeIfPresent(genre, forKey: .genre)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encode(callNumber, forKey: .callNumber)
        try container.encode(libraryUrl, forKey: .libraryUrl)
        try container.encodeIfPresent(onStreaming, forKey: .onStreaming)
    }
}

