//
// LibraryFilingResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LibraryFilingResponse: Sendable, Codable, Hashable {

    public var artist: Artist
    public var release: Album
    public var rotation: RotationEntry?

    public init(artist: Artist, release: Album, rotation: RotationEntry? = nil) {
        self.artist = artist
        self.release = release
        self.rotation = rotation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artist
        case release
        case rotation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artist, forKey: .artist)
        try container.encode(release, forKey: .release)
        try container.encodeIfPresent(rotation, forKey: .rotation)
    }
}

