//
// LibrarySearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LibrarySearchResponse: Sendable, Codable, Hashable {

    public var results: [LibrarySearchItem]?
    public var total: Int?
    public var query: String?

    public init(results: [LibrarySearchItem]? = nil, total: Int? = nil, query: String? = nil) {
        self.results = results
        self.total = total
        self.query = query
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results
        case total
        case query
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(results, forKey: .results)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(query, forKey: .query)
    }
}

