//
// LibraryLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single other WXYC shelf location carrying the same track, returned on &#x60;LookupResponse.also_available_on&#x60; when the request set &#x60;include_locations: true&#x60; (LML#1018/#1022&#39;s comprehensive multi-location union). Deliberately a lean entry rather than a full &#x60;LookupResultItem&#x60; — no live artwork/identity resolution; art is precomputed at index time.  */
public struct LibraryLocation: Sendable, Codable, Hashable {

    public enum CreditRole: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case primary = "primary"
        case featured = "featured"
        case extra = "extra"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** WXYC library.id (shelf location) for this copy. */
    public var libraryId: Int
    /** Shelf/album artist (e.g. \"Soundtracks - L\"). */
    public var artist: String?
    /** Album/release title (e.g. \"Lost in Translation\"). */
    public var albumTitle: String?
    /** The track's position on this release (e.g. \"A1\"), when known. */
    public var trackPosition: String?
    /** Track title. */
    public var trackTitle: String
    /** Credited-as artist for this track (e.g. \"Brian Reitzell And Roger J. Manning, Jr.\"), which may differ from the shelf artist on a compilation.  */
    public var trackArtist: String
    /** The role this credit represents on the track. */
    public var creditRole: CreditRole?
    /** Discogs release ID, usable as an art re-resolution key. */
    public var discogsReleaseId: Int?
    /** Precomputed cover art URL for this location. */
    public var artworkUrl: String?

    public init(libraryId: Int, artist: String? = nil, albumTitle: String? = nil, trackPosition: String? = nil, trackTitle: String, trackArtist: String, creditRole: CreditRole? = nil, discogsReleaseId: Int? = nil, artworkUrl: String? = nil) {
        self.libraryId = libraryId
        self.artist = artist
        self.albumTitle = albumTitle
        self.trackPosition = trackPosition
        self.trackTitle = trackTitle
        self.trackArtist = trackArtist
        self.creditRole = creditRole
        self.discogsReleaseId = discogsReleaseId
        self.artworkUrl = artworkUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case libraryId = "library_id"
        case artist
        case albumTitle = "album_title"
        case trackPosition = "track_position"
        case trackTitle = "track_title"
        case trackArtist = "track_artist"
        case creditRole = "credit_role"
        case discogsReleaseId = "discogs_release_id"
        case artworkUrl = "artwork_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(libraryId, forKey: .libraryId)
        try container.encodeIfPresent(artist, forKey: .artist)
        try container.encodeIfPresent(albumTitle, forKey: .albumTitle)
        try container.encodeIfPresent(trackPosition, forKey: .trackPosition)
        try container.encode(trackTitle, forKey: .trackTitle)
        try container.encode(trackArtist, forKey: .trackArtist)
        try container.encodeIfPresent(creditRole, forKey: .creditRole)
        try container.encodeIfPresent(discogsReleaseId, forKey: .discogsReleaseId)
        try container.encodeIfPresent(artworkUrl, forKey: .artworkUrl)
    }
}


extension LibraryLocation: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if creditRole == .unknownDefaultOpenApi { return true }
        return false
    }
}
