//
// LibrarySearchItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single item from LML&#39;s library catalog search. */
public struct LibrarySearchItem: Sendable, Codable, Hashable {

    public var id: Int
    public var title: String?
    public var artist: String?
    public var callLetters: String?
    public var artistCallNumber: Int?
    public var releaseCallNumber: Int?
    public var genre: String?
    public var format: String?
    public var alternateArtistName: String?
    public var label: String?
    public var onStreaming: Bool?
    /** Computed call number (e.g. \"Rock CD S 1/1\") */
    public var callNumber: String?
    /** URL to the release on wxyc.info */
    public var libraryUrl: String?
    /** Populated when a track-title match drove this release into the results (catalog-track-search plan §5.1). Empty or absent when the release matched on artist / title normally. Backward-compatible — existing consumers ignore the field.  */
    public var matchedVia: [TrackMatchHint]?
    /** Sibling to `matched_via`. Reserved for the day LML composes artist-alias hits itself; not produced in v1 of the artist-search-alias plan (BS-local cache only). Optional and backward-compatible.  */
    public var matchedViaAlias: [ArtistMatchHint]?

    public init(id: Int, title: String? = nil, artist: String? = nil, callLetters: String? = nil, artistCallNumber: Int? = nil, releaseCallNumber: Int? = nil, genre: String? = nil, format: String? = nil, alternateArtistName: String? = nil, label: String? = nil, onStreaming: Bool? = nil, callNumber: String? = nil, libraryUrl: String? = nil, matchedVia: [TrackMatchHint]? = nil, matchedViaAlias: [ArtistMatchHint]? = nil) {
        self.id = id
        self.title = title
        self.artist = artist
        self.callLetters = callLetters
        self.artistCallNumber = artistCallNumber
        self.releaseCallNumber = releaseCallNumber
        self.genre = genre
        self.format = format
        self.alternateArtistName = alternateArtistName
        self.label = label
        self.onStreaming = onStreaming
        self.callNumber = callNumber
        self.libraryUrl = libraryUrl
        self.matchedVia = matchedVia
        self.matchedViaAlias = matchedViaAlias
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case artist
        case callLetters = "call_letters"
        case artistCallNumber = "artist_call_number"
        case releaseCallNumber = "release_call_number"
        case genre
        case format
        case alternateArtistName = "alternate_artist_name"
        case label
        case onStreaming = "on_streaming"
        case callNumber = "call_number"
        case libraryUrl = "library_url"
        case matchedVia = "matched_via"
        case matchedViaAlias = "matched_via_alias"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(artist, forKey: .artist)
        try container.encodeIfPresent(callLetters, forKey: .callLetters)
        try container.encodeIfPresent(artistCallNumber, forKey: .artistCallNumber)
        try container.encodeIfPresent(releaseCallNumber, forKey: .releaseCallNumber)
        try container.encodeIfPresent(genre, forKey: .genre)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(alternateArtistName, forKey: .alternateArtistName)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(onStreaming, forKey: .onStreaming)
        try container.encodeIfPresent(callNumber, forKey: .callNumber)
        try container.encodeIfPresent(libraryUrl, forKey: .libraryUrl)
        try container.encodeIfPresent(matchedVia, forKey: .matchedVia)
        try container.encodeIfPresent(matchedViaAlias, forKey: .matchedViaAlias)
    }
}

