//
// LiveFsRefetchEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** SSE event emitted on the &#x60;live-fs-topic&#x60; when bulk state changes (ETL runs, schema migrations) make targeted patches impractical. Consumers respond with a coarse cache invalidation. &#x60;payload.source&#x60; is a free-text label for telemetry only (&#x60;etl&#x60;, &#x60;migration&#x60;, etc.) — clients must not branch on it.  */
public struct LiveFsRefetchEvent: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case refetch = "refetch"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var payload: LiveFsRefetchEventPayload
    public var timestamp: Date

    public init(type: ModelType, payload: LiveFsRefetchEventPayload, timestamp: Date) {
        self.type = type
        self.payload = payload
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case payload
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(payload, forKey: .payload)
        try container.encode(timestamp, forKey: .timestamp)
    }
}


extension LiveFsRefetchEvent: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        return false
    }
}
