//
// LiveFsRefetchEventPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LiveFsRefetchEventPayload: Sendable, Codable, Hashable {

    /** Free-text label naming the upstream cause (telemetry only). */
    public var source: String

    public init(source: String) {
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(source, forKey: .source)
    }
}

