//
// LookupResultItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single lookup result pairing a library item with optional artwork and reconciled identity. &#x60;artwork&#x60; is optional and independent of &#x60;library_item&#x60;. This makes the *row-less* shape valid and first-class: &#x60;library_item.id &#x3D;&#x3D; 0&#x60; (no WXYC catalog row) paired with a present &#x60;artwork&#x60; carrying &#x60;release_id &gt; 0&#x60; and a non-empty &#x60;release_url&#x60; is a \&quot;Discogs identity, no catalog row\&quot; result — the album isn&#39;t shelved in the library, but Discogs confidently identifies the release, so the link, artwork, and downstream streaming buttons still render. LML emits this shape both from a library-miss Discogs search and from a non-library track carry-through (a confidently-resolved release for a track whose album isn&#39;t shelved). This is distinct from the &#x60;artwork.release_id &#x3D;&#x3D; 0&#x60; / &#x60;release_url &#x3D;&#x3D; \&quot;\&quot;&#x60; streaming-only sentinel (BS#1185), which carries streaming URLs but no linkable Discogs release. The discriminator is &#x60;artwork.release_id &gt; 0 &amp;&amp; library_item.id &#x3D;&#x3D; 0&#x60;: unambiguous against the sentinel and backward-compatible with any consumer keying \&quot;has Discogs identity\&quot; on &#x60;release_id !&#x3D; 0&#x60;.  */
public struct LookupResultItem: Sendable, Codable, Hashable {

    public var libraryItem: LibraryCatalogItem
    public var artwork: DiscogsMatchResult?
    public var reconciledIdentity: ReconciledIdentity?
    /** Populated when a track-title match (LML's new SONG_AS_TRACK strategy) drove this release into the results, per catalog-track-search plan §5.1. Empty or absent when the release matched via artist/album strategies. Backward-compatible — existing consumers ignore the field.  */
    public var matchedVia: [TrackMatchHint]?
    /** Sibling to `matched_via`. Reserved for the day LML composes artist-alias hits itself; not produced in v1 of the artist-search-alias plan (BS-local cache only). Optional and backward-compatible.  */
    public var matchedViaAlias: [ArtistMatchHint]?

    public init(libraryItem: LibraryCatalogItem, artwork: DiscogsMatchResult? = nil, reconciledIdentity: ReconciledIdentity? = nil, matchedVia: [TrackMatchHint]? = nil, matchedViaAlias: [ArtistMatchHint]? = nil) {
        self.libraryItem = libraryItem
        self.artwork = artwork
        self.reconciledIdentity = reconciledIdentity
        self.matchedVia = matchedVia
        self.matchedViaAlias = matchedViaAlias
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case libraryItem = "library_item"
        case artwork
        case reconciledIdentity = "reconciled_identity"
        case matchedVia = "matched_via"
        case matchedViaAlias = "matched_via_alias"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(libraryItem, forKey: .libraryItem)
        try container.encodeIfPresent(artwork, forKey: .artwork)
        try container.encodeIfPresent(reconciledIdentity, forKey: .reconciledIdentity)
        try container.encodeIfPresent(matchedVia, forKey: .matchedVia)
        try container.encodeIfPresent(matchedViaAlias, forKey: .matchedViaAlias)
    }
}

