//
// LookupEmailRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Body for POST /auth/wxyc/lookup-email — a WXYC-custom route (see the path&#39;s own comment), not a better-auth one.  */
public struct LookupEmailRequest: Sendable, Codable, Hashable {

    public var identifier: String

    public init(identifier: String) {
        self.identifier = identifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identifier
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(identifier, forKey: .identifier)
    }
}

