//
// LookupEmailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** &#x60;email: null&#x60; means no account matches &#x60;identifier&#x60; — the one precise failure this route can report (apps/auth/lookup-email.ts). Everything downstream of a resolved email is deliberately vague (anti-enumeration): send-verification-otp answers success for an unknown address, and sign-in/email-otp answers the same INVALID_OTP for a wrong code as for no account.  */
public struct LookupEmailResponse: Sendable, Codable, Hashable {

    public var email: String?

    public init(email: String?) {
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
    }
}

