//
// LookupRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LookupRequest: Sendable, Codable, Hashable {

    /** Parsed artist name */
    public var artist: String?
    /** Parsed song/track title */
    public var song: String?
    /** Parsed album name */
    public var album: String?
    /** Original request message (used for ambiguous format detection). Optional when structured fields (artist, album, song) are provided.  */
    public var rawMessage: String?
    /** Per cross-cache-identity plan §3.2.2 (E2-LML write contract). When true, the response carries an additional `identity` block (the §3.2.5 cascade's per-source resolution detail), and `api_version` is set to 2. When false (the default), the response is byte-identical to v0.5.0 — `identity` is absent and `api_version` is omitted. Backend's `library-identity-writer.ts` (E2-BS) sets this to true on every call; other consumers (catalog search, dj-site proxy, iOS apps) leave it false.  */
    public var includeIdentity: Bool? = false
    /** When true, the top-1 result's `artwork` block is populated with additional fields LML already fetches during enrichment but normally discards: `discogs_artist_id`, `tracklist`, `genres`, `styles`, `label`, `full_release_date`, `artist_image_url`, and `profile_tokens` (cache-only deep parse of the artist's profile markup). Lets a caller obtain a full playcut metadata payload in a single `/lookup` call instead of following up with separate `/discogs/release/{id}` and `/discogs/artist/{id}` requests. Absent or false leaves the response shape unchanged.  */
    public var extended: Bool?
    /** When true, LML schedules a fire-and-forget background task after the response is built that runs a *deep* async parse of the top-1 artist's bio. The task resolves all `[a…]`/`[r…]`/`[m…]` references against the Discogs API where the local cache misses, warming the PG cache so subsequent reads of the same artist render richer bio tokens. Intended for write-path callers (e.g. Backend-Service's flowsheet-linkage service committing a new DJ entry); read-path callers should leave this absent/false to avoid doubling the Discogs-API load per request.  */
    public var warmCache: Bool?

    public init(artist: String? = nil, song: String? = nil, album: String? = nil, rawMessage: String? = nil, includeIdentity: Bool? = false, extended: Bool? = nil, warmCache: Bool? = nil) {
        self.artist = artist
        self.song = song
        self.album = album
        self.rawMessage = rawMessage
        self.includeIdentity = includeIdentity
        self.extended = extended
        self.warmCache = warmCache
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artist
        case song
        case album
        case rawMessage = "raw_message"
        case includeIdentity = "include_identity"
        case extended
        case warmCache = "warm_cache"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(artist, forKey: .artist)
        try container.encodeIfPresent(song, forKey: .song)
        try container.encodeIfPresent(album, forKey: .album)
        try container.encodeIfPresent(rawMessage, forKey: .rawMessage)
        try container.encodeIfPresent(includeIdentity, forKey: .includeIdentity)
        try container.encodeIfPresent(extended, forKey: .extended)
        try container.encodeIfPresent(warmCache, forKey: .warmCache)
    }
}

