//
// NewDJ.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NewDJ: Sendable, Codable, Hashable {

    public var cognitoUserName: String?
    public var realName: String?
    public var djName: String?

    public init(cognitoUserName: String? = nil, realName: String? = nil, djName: String? = nil) {
        self.cognitoUserName = cognitoUserName
        self.realName = realName
        self.djName = djName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cognitoUserName = "cognito_user_name"
        case realName = "real_name"
        case djName = "dj_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cognitoUserName, forKey: .cognitoUserName)
        try container.encodeIfPresent(realName, forKey: .realName)
        try container.encodeIfPresent(djName, forKey: .djName)
    }
}

