//
// OpenShow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One open show as reported by &#x60;GET /flowsheet/open-shows&#x60;. Distinct from &#x60;Show&#x60;: it carries the derived &#x60;entry_count&#x60;, &#x60;is_current&#x60; and &#x60;likely_abandoned&#x60; fields, and omits &#x60;end_time&#x60;, which is NULL for every member of this collection by construction.  */
public struct OpenShow: Sendable, Codable, Hashable {

    public var id: Int
    /** NULL for legacy/tubafrenzy-originated shows and for any show whose DJ account was deleted (`ON DELETE SET NULL`). Such a show can still be closed via `force-end`.  */
    public var primaryDjId: String?
    /** The DJ's public on-air handle, never the DJ's legal name. Same PII-safe resolution chain as `FlowsheetEntryFields.dj_name` (BS#1371): per-show override -> the DJ's chosen handle -> the legacy tubafrenzy handle -> `null` when unresolvable.  */
    public var djName: String?
    public var showName: String?
    public var startTime: Date
    /** The tubafrenzy surrogate key, when this show was mirrored. */
    public var legacyShowId: Int?
    /** Flowsheet rows belonging to this show, all entry types included. */
    public var entryCount: Int
    /** True for the single show every on-air read resolves to. Present so a client can never offer to close the live broadcast.  */
    public var isCurrent: Bool
    /** Advisory only — an operator hint, not a verdict. True when the show is not current and has fewer than four entries. A show with many entries can still be abandoned; check `start_time`.  */
    public var likelyAbandoned: Bool

    public init(id: Int, primaryDjId: String?, djName: String?, showName: String?, startTime: Date, legacyShowId: Int?, entryCount: Int, isCurrent: Bool, likelyAbandoned: Bool) {
        self.id = id
        self.primaryDjId = primaryDjId
        self.djName = djName
        self.showName = showName
        self.startTime = startTime
        self.legacyShowId = legacyShowId
        self.entryCount = entryCount
        self.isCurrent = isCurrent
        self.likelyAbandoned = likelyAbandoned
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case primaryDjId = "primary_dj_id"
        case djName = "dj_name"
        case showName = "show_name"
        case startTime = "start_time"
        case legacyShowId = "legacy_show_id"
        case entryCount = "entry_count"
        case isCurrent = "is_current"
        case likelyAbandoned = "likely_abandoned"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(primaryDjId, forKey: .primaryDjId)
        try container.encode(djName, forKey: .djName)
        try container.encode(showName, forKey: .showName)
        try container.encode(startTime, forKey: .startTime)
        try container.encode(legacyShowId, forKey: .legacyShowId)
        try container.encode(entryCount, forKey: .entryCount)
        try container.encode(isCurrent, forKey: .isCurrent)
        try container.encode(likelyAbandoned, forKey: .likelyAbandoned)
    }
}

