//
// OpenShowsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OpenShowsResponse: Sendable, Codable, Hashable {

    /** Ordered oldest-first by `start_time`, tie-broken on `id`. */
    public var shows: [OpenShow]
    /** How many open shows the window holds in total, before `limit` truncates. `shows.length < total_in_window` is the only way a caller can tell it is looking at a partial answer.  */
    public var totalInWindow: Int
    /** Open shows that started BEFORE the window, reported as a count and never listed. Almost all of these are legacy imports whose `show_end` never arrived; see the endpoint description. Widen `window_hours` to reach them.  **Expected to go to zero and stay there.** This field and the 30-year `window_hours` ceiling both exist for one finite cohort — the ~2,813 shows WXYC/Backend-Service#1543 repairs from the final tubafrenzy dump. Once that lands, both are vestigial and a later contract version should drop them rather than preserve them out of habit.  */
    public var olderOpenShowCount: Int

    public init(shows: [OpenShow], totalInWindow: Int, olderOpenShowCount: Int) {
        self.shows = shows
        self.totalInWindow = totalInWindow
        self.olderOpenShowCount = olderOpenShowCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shows
        case totalInWindow = "total_in_window"
        case olderOpenShowCount = "older_open_show_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shows, forKey: .shows)
        try container.encode(totalInWindow, forKey: .totalInWindow)
        try container.encode(olderOpenShowCount, forKey: .olderOpenShowCount)
    }
}

