//
// OTPSignInRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Body for POST /auth/sign-in/email-otp. &#x60;name&#x60;/&#x60;image&#x60; are dead on this deployment: Backend-Service sets &#x60;disableSignUp: true&#x60; on the emailOTP plugin (shared/authentication/src/auth.definition.ts), and that flag gates THIS route (dist/plugins/email-otp/routes.mjs signInEmailOTP: &#x60;if (!user) { if (opts.disableSignUp) throw APIError.from(\&quot;BAD_REQUEST\&quot;, INVALID_OTP); ... }&#x60;), not just send-verification-otp as an earlier version of this comment claimed. A correct code for an email with no existing account 400s INVALID_OTP rather than auto-registering, so &#x60;name&#x60;/&#x60;image&#x60; are never reached and registration via this route is unreachable on this deployment. See LookupEmailResponse&#39;s description, which already documented the true anti-enumeration behavior this field list previously contradicted.  */
public struct OTPSignInRequest: Sendable, Codable, Hashable {

    public var email: String
    public var otp: String
    public var name: String?
    public var image: String?

    public init(email: String, otp: String, name: String? = nil, image: String? = nil) {
        self.email = email
        self.otp = otp
        self.name = name
        self.image = image
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case otp
        case name
        case image
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(otp, forKey: .otp)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(image, forKey: .image)
    }
}

