//
// OTPType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The &#x60;type&#x60; values better-auth&#39;s email-otp plugin schema declares. WXYC&#39;s OTP sign-in flow always sends \&quot;sign-in\&quot;. \&quot;change-email\&quot; is declared by the plugin&#39;s own schema but always 400s on POST /auth/email-otp/send-verification-otp — a dedicated /email-otp/request-email-change route exists for it. Named rather than left as an inline enum on SendLoginCodeRequest.type: an unnamed inline enum is emitted by the Python generator (datamodel-code-generator) as a bare &#x60;Type&#x60; class, silently renumbering (&#x60;Type1&#x60;, &#x60;Type2&#x60;, ...) every other unnamed inline enum in the document depending on declaration order — see the issue #379 review finding that named this one.  */
public enum OTPType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case signIn = "sign-in"
    case emailVerification = "email-verification"
    case forgetPassword = "forget-password"
    case changeEmail = "change-email"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension OTPType: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
