//
// PaginationParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginationParams: Sendable, Codable, Hashable {

    public static let pageRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let limitRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public var page: Int?
    public var limit: Int?

    public init(page: Int? = nil, limit: Int? = nil) {
        self.page = page
        self.limit = limit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case limit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(limit, forKey: .limit)
    }
}

