//
// PaginationInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginationInfo: Sendable, Codable, Hashable {

    public var page: Int
    public var limit: Int
    public var total: Int?
    public var hasMore: Bool?

    public init(page: Int, limit: Int, total: Int? = nil, hasMore: Bool? = nil) {
        self.page = page
        self.limit = limit
        self.total = total
        self.hasMore = hasMore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case limit
        case total
        case hasMore
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(page, forKey: .page)
        try container.encode(limit, forKey: .limit)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(hasMore, forKey: .hasMore)
    }
}

