//
// PlaylistWithEntries.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlaylistWithEntries: Sendable, Codable, Hashable {

    public var id: Int
    public var djId: Int
    public var name: String
    public var createdAt: Date
    public var updatedAt: Date
    public var entries: [PlaylistEntry]

    public init(id: Int, djId: Int, name: String, createdAt: Date, updatedAt: Date, entries: [PlaylistEntry]) {
        self.id = id
        self.djId = djId
        self.name = name
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.entries = entries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case djId = "dj_id"
        case name
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case entries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(djId, forKey: .djId)
        try container.encode(name, forKey: .name)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(entries, forKey: .entries)
    }
}

