//
// PlaylistSearchResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlaylistSearchResult: Sendable, Codable, Hashable {

    public var id: Int
    public var playDate: Date
    public var artistName: String
    public var trackTitle: String
    public var albumTitle: String
    public var recordLabel: String
    public var djName: String
    public var showId: Int

    public init(id: Int, playDate: Date, artistName: String, trackTitle: String, albumTitle: String, recordLabel: String, djName: String, showId: Int) {
        self.id = id
        self.playDate = playDate
        self.artistName = artistName
        self.trackTitle = trackTitle
        self.albumTitle = albumTitle
        self.recordLabel = recordLabel
        self.djName = djName
        self.showId = showId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case playDate = "play_date"
        case artistName = "artist_name"
        case trackTitle = "track_title"
        case albumTitle = "album_title"
        case recordLabel = "record_label"
        case djName = "dj_name"
        case showId = "show_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(playDate, forKey: .playDate)
        try container.encode(artistName, forKey: .artistName)
        try container.encode(trackTitle, forKey: .trackTitle)
        try container.encode(albumTitle, forKey: .albumTitle)
        try container.encode(recordLabel, forKey: .recordLabel)
        try container.encode(djName, forKey: .djName)
        try container.encode(showId, forKey: .showId)
    }
}

