//
// RecentShowsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RecentShowsResponse: Sendable, Codable, Hashable {

    /** Ordered newest-first by `start_time`, tie-broken on `id` DESC.  Capped at 200 rows, which truncates the OLDEST shows in the window — the reason no `limit` parameter is offered, since those are the least useful rows to a DJ taking over. A page that reaches the cap carries no flag saying so; narrow `window_hours` if you need to know you have the whole window.  */
    public var shows: [RecentShow]

    public init(shows: [RecentShow]) {
        self.shows = shows
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shows
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shows, forKey: .shows)
    }
}

