//
// ReleaseIdentitySource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Source whose external ID is being resolved into a release identity. Matches the v1 source list from LML#526; new sources land in lockstep with their column on &#x60;entity.release_identity&#x60; and a matching sentinel rule on the LML side.  */
public enum ReleaseIdentitySource: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case discogsRelease = "discogs_release"
    case discogsMaster = "discogs_master"
    case bandcamp = "bandcamp"
    case appleMusicAlbum = "apple_music_album"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension ReleaseIdentitySource: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
