//
// ReleaseIdentityResolveRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request body for &#x60;POST /api/v1/identity/resolve&#x60;. The triple &#x60;(kind, source, external_id)&#x60; is the identity key — the same triple always returns the same identity_id.  */
public struct ReleaseIdentityResolveRequest: Sendable, Codable, Hashable {

    public var kind: IdentityKind
    public var source: ReleaseIdentitySource
    /** Source-specific identifier. For `discogs_release` / `discogs_master` it is the positive integer ID as a string; zero and negative values are rejected with 422 (Discogs uses `0` for the unknown-release sentinel). For `bandcamp` it is the canonical album URL (e.g. `https://autechre.bandcamp.com/album/confield`); LML URL-canonicalises before mint so trailing-slash and equivalent variants converge on one identity row. Non-album Bandcamp URLs (track URLs, bare subdomain) are rejected with 422. For `apple_music_album` it is the numeric Apple Music album ID as a string (e.g. `1234567890`); zero, negative, and non-numeric values are rejected with 422.  */
    public var externalId: String

    public init(kind: IdentityKind, source: ReleaseIdentitySource, externalId: String) {
        self.kind = kind
        self.source = source
        self.externalId = externalId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case source
        case externalId = "external_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(source, forKey: .source)
        try container.encode(externalId, forKey: .externalId)
    }
}


extension ReleaseIdentityResolveRequest: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if kind == .unknownDefaultOpenApi { return true }
        if source == .unknownDefaultOpenApi { return true }
        return false
    }
}
