//
// RequestStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RequestStatus: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case pending = "pending"
    case played = "played"
    case rejected = "rejected"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension RequestStatus: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
