//
// RequestSubmissionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RequestSubmissionResponse: Sendable, Codable, Hashable {

    public var success: Bool
    public var requestId: Int?
    public var rateLimit: RateLimitInfo?
    public var message: String?

    public init(success: Bool, requestId: Int? = nil, rateLimit: RateLimitInfo? = nil, message: String? = nil) {
        self.success = success
        self.requestId = requestId
        self.rateLimit = rateLimit
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case requestId = "request_id"
        case rateLimit = "rate_limit"
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(rateLimit, forKey: .rateLimit)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

