//
// RotationEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RotationEntry: Sendable, Codable, Hashable {

    public var id: Int
    public var albumId: Int
    public var rotationBin: RotationBin
    public var addDate: Date
    public var killDate: Date?

    public init(id: Int, albumId: Int, rotationBin: RotationBin, addDate: Date, killDate: Date? = nil) {
        self.id = id
        self.albumId = albumId
        self.rotationBin = rotationBin
        self.addDate = addDate
        self.killDate = killDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case albumId = "album_id"
        case rotationBin = "rotation_bin"
        case addDate = "add_date"
        case killDate = "kill_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(albumId, forKey: .albumId)
        try container.encode(rotationBin, forKey: .rotationBin)
        try container.encode(addDate, forKey: .addDate)
        try container.encodeIfPresent(killDate, forKey: .killDate)
    }
}


extension RotationEntry: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if rotationBin == .unknownDefaultOpenApi { return true }
        return false
    }
}
