//
// RotationBin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Rotation bin levels: H&#x3D;Heavy, M&#x3D;Medium, L&#x3D;Light, S&#x3D;Single */
public enum RotationBin: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case h = "H"
    case m = "M"
    case l = "L"
    case s = "S"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension RotationBin: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
