//
// RotationConflictError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The 409 body on &#x60;POST /library/rotation&#x60; and &#x60;DELETE /library/rotation/cards/{id}&#x60;, following &#x60;ShowAlreadyOpenError&#x60;.  */
public struct RotationConflictError: Sendable, Codable, Hashable {

    public var message: String
    public var reason: RotationConflictReason

    public init(message: String, reason: RotationConflictReason) {
        self.message = message
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(reason, forKey: .reason)
    }
}


extension RotationConflictError: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if reason == .unknownDefaultOpenApi { return true }
        return false
    }
}
