//
// RotationConflictReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Discriminator for the 409s on &#x60;POST /library/rotation&#x60; and &#x60;DELETE /library/rotation/cards/{id}&#x60;, pairing with &#x60;RotationConflictError&#x60; the way &#x60;ShowAlreadyOpenErrorCode&#x60; pairs with &#x60;ShowAlreadyOpenError&#x60;. &#x60;rotation_card_bin_mismatch&#x60; is the single source of truth for the identically-named value &#x60;LibraryFilingConflictReason&#x60; carries for the composite&#39;s rotation arm — see that schema&#39;s description. The other two distinguish the card-delete guard&#39;s conjunctive halves: a sibling card with a higher &#x60;number&#x60; (&#x60;card_not_highest_in_bin&#x60;) vs. an active rotation row still assigned to this card (&#x60;card_has_active_rotations&#x60;). All three values are declared ahead of the Backend-Service implementation (WXYC/Backend-Service#2472, delivered by its open PR WXYC/Backend-Service#2482): the deployed backend has no rotation-card code path yet, so no endpoint raises them today — each endpoint&#39;s 409 states what the deployed behavior is meanwhile.  */
public enum RotationConflictReason: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case rotationCardBinMismatch = "rotation_card_bin_mismatch"
    case cardNotHighestInBin = "card_not_highest_in_bin"
    case cardHasActiveRotations = "card_has_active_rotations"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension RotationConflictReason: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
