//
// ScheduleShift.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScheduleShift: Sendable, Codable, Hashable {

    public var id: Int
    public var djId: Int
    public var djName: String
    public var day: DayOfWeek
    /** Time in HH:MM format */
    public var startTime: String
    /** Time in HH:MM format */
    public var endTime: String
    public var showName: String?
    public var specialtyId: Int?

    public init(id: Int, djId: Int, djName: String, day: DayOfWeek, startTime: String, endTime: String, showName: String? = nil, specialtyId: Int? = nil) {
        self.id = id
        self.djId = djId
        self.djName = djName
        self.day = day
        self.startTime = startTime
        self.endTime = endTime
        self.showName = showName
        self.specialtyId = specialtyId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case djId = "dj_id"
        case djName = "dj_name"
        case day
        case startTime = "start_time"
        case endTime = "end_time"
        case showName = "show_name"
        case specialtyId = "specialty_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(djId, forKey: .djId)
        try container.encode(djName, forKey: .djName)
        try container.encode(day, forKey: .day)
        try container.encode(startTime, forKey: .startTime)
        try container.encode(endTime, forKey: .endTime)
        try container.encodeIfPresent(showName, forKey: .showName)
        try container.encodeIfPresent(specialtyId, forKey: .specialtyId)
    }
}


extension ScheduleShift: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if day == .unknownDefaultOpenApi { return true }
        return false
    }
}
