//
// ScheduleShift.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScheduleShift: Sendable, Codable, Hashable {

    public static let dayRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 6, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int
    public var djId: Int
    /** The DJ's public on-air handle, never the DJ's legal name. Per the declared/actual mismatch noted above (BS#2224), no current handler populates this from a verified `dj_name`-bearing source — this description states the intent for when that gap closes, not today's implemented behavior. */
    public var djName: String
    /** Day of the week 0 = Monday, 6 = Sunday */
    public var day: Int
    /** Time in HH:MM format */
    public var startTime: String
    /** Time in HH:MM format */
    public var endTime: String
    public var showName: String?
    public var specialtyId: Int?

    public init(id: Int, djId: Int, djName: String, day: Int, startTime: String, endTime: String, showName: String? = nil, specialtyId: Int? = nil) {
        self.id = id
        self.djId = djId
        self.djName = djName
        self.day = day
        self.startTime = startTime
        self.endTime = endTime
        self.showName = showName
        self.specialtyId = specialtyId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case djId = "dj_id"
        case djName = "dj_name"
        case day
        case startTime = "start_time"
        case endTime = "end_time"
        case showName = "show_name"
        case specialtyId = "specialty_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(djId, forKey: .djId)
        try container.encode(djName, forKey: .djName)
        try container.encode(day, forKey: .day)
        try container.encode(startTime, forKey: .startTime)
        try container.encode(endTime, forKey: .endTime)
        try container.encodeIfPresent(showName, forKey: .showName)
        try container.encodeIfPresent(specialtyId, forKey: .specialtyId)
    }
}

