//
// SendLoginCodeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Body for POST /auth/email-otp/send-verification-otp. */
public struct SendLoginCodeRequest: Sendable, Codable, Hashable {

    public var email: String
    public var type: OTPType

    public init(email: String, type: OTPType) {
        self.email = email
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(type, forKey: .type)
    }
}


extension SendLoginCodeRequest: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        return false
    }
}
