//
// ShowDJ.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ShowDJ: Sendable, Codable, Hashable {

    public var showId: Int?
    public var djId: Int?
    public var active: Bool?

    public init(showId: Int? = nil, djId: Int? = nil, active: Bool? = nil) {
        self.showId = showId
        self.djId = djId
        self.active = active
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case showId = "show_id"
        case djId = "dj_id"
        case active
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(showId, forKey: .showId)
        try container.encodeIfPresent(djId, forKey: .djId)
        try container.encodeIfPresent(active, forKey: .active)
    }
}

