//
// ShowAlreadyOpenErrorDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Wrapper matching &#x60;ApiErrorResponse&#x60;&#39;s &#x60;details&#x60; position, so the 409 body stays shape-compatible with every other error on the service even though it is typed. Named for the same reason as the code enum above: inline, it generates as a top-level &#x60;Details&#x60; class.  */
public struct ShowAlreadyOpenErrorDetails: Sendable, Codable, Hashable {

    public var show: ShowAlreadyOpenShow?

    public init(show: ShowAlreadyOpenShow? = nil) {
        self.show = show
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case show
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(show, forKey: .show)
    }
}

