//
// ShowAlreadyOpenShow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Identity of the open show the caller collided with. A strict subset of &#x60;OpenShow&#x60;, whose rows &#x60;GET /flowsheet/open-shows&#x60; returns — same fields, same nullability, same BS#1371 resolution chain for &#x60;dj_name&#x60;.  */
public struct ShowAlreadyOpenShow: Sendable, Codable, Hashable {

    /** `shows.id` of the open show. This is the value a follow-up `intent: takeover` must send as `expected_show_id`.  */
    public var id: Int
    /** The show OWNER's public handle, resolved through the same PII-safe chain as `OpenShow.dj_name` (BS#1371): per-show override -> the DJ's chosen handle -> the legacy tubafrenzy handle -> `null` when unresolvable.  **Null is the common case, not the edge.** Essentially the whole open-show backlog this handshake exists to unstick reaches nothing through that chain (2,813 of production's 2,814 open shows carried a NULL `primary_dj_id` as of 2026-08-21), so a prompt that interpolates it unguarded renders \"null is on air\". Fall back to generic phrasing.  For an abandoned show this names the DJ who LEFT. A client showing \"who is on air right now\" should prefer `GET /flowsheet/djs-on-air`, whose active-membership answer is the one that disagrees with this field precisely when it matters.  */
    public var djName: String?
    public var startTime: Date

    public init(id: Int, djName: String? = nil, startTime: Date) {
        self.id = id
        self.djName = djName
        self.startTime = startTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case djName = "dj_name"
        case startTime = "start_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(djName, forKey: .djName)
        try container.encode(startTime, forKey: .startTime)
    }
}

