//
// ShowPeekDjsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ShowPeekDjsInner: Sendable, Codable, Hashable {

    public var djId: Int?
    public var djName: String?

    public init(djId: Int? = nil, djName: String? = nil) {
        self.djId = djId
        self.djName = djName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case djId = "dj_id"
        case djName = "dj_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(djId, forKey: .djId)
        try container.encodeIfPresent(djName, forKey: .djName)
    }
}

