//
// ShowAlreadyOpenErrorCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Discriminator for the &#x60;POST /flowsheet/join&#x60; 409. Named rather than left inline on &#x60;ShowAlreadyOpenError.code&#x60;, pairing with it the way &#x60;DeviceAuthCodeErrorCode&#x60; pairs with &#x60;DeviceAuthCodeError&#x60; — an inline enum under an anonymous parent generates as a top-level &#x60;Code&#x60; class in the Python module, which is both meaningless at the call site and a collision waiting to happen in a file that already carries a generic &#x60;Status&#x60; and &#x60;Show&#x60; from the same mechanism.  */
public enum ShowAlreadyOpenErrorCode: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case showAlreadyOpen = "show_already_open"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension ShowAlreadyOpenErrorCode: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
