//
// ShowAlreadyOpenError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The &#x60;POST /flowsheet/join&#x60; 409 body. Purpose-built rather than a &#x60;$ref&#x60; to the shared &#x60;ApiErrorResponse&#x60;, following &#x60;AuthErrorResponse&#x60; and the &#x60;DeviceAuth*Error&#x60; family: &#x60;ApiErrorResponse.details&#x60; is &#x60;additionalProperties: true&#x60;, which reaches consumers as an untyped bag (&#x60;JSONValue&#x60; in Swift, &#x60;Record&lt;string, unknown&gt;&#x60; in TS), and &#x60;details.show.id&#x60; is not an incidental diagnostic here — a client is REQUIRED to read it and echo it back as &#x60;expected_show_id&#x60; to complete the takeover handshake. Typing it is what makes that a compare-and-set rather than four hand-written key-path digs.  */
public struct ShowAlreadyOpenError: Sendable, Codable, Hashable {

    public var message: String
    public var code: ShowAlreadyOpenErrorCode?
    public var details: ShowAlreadyOpenErrorDetails?

    public init(message: String, code: ShowAlreadyOpenErrorCode? = nil, details: ShowAlreadyOpenErrorDetails? = nil) {
        self.message = message
        self.code = code
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case code
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(details, forKey: .details)
    }
}


extension ShowAlreadyOpenError: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if code == .unknownDefaultOpenApi { return true }
        return false
    }
}
