//
// SimilarArtist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One affinity neighbor of a resolved concert headliner, drawn from the semantic-index graph. &#x60;artist_id&#x60; shares the WXYC catalog artist-id keyspace with &#x60;Concert.headlining_artist_id&#x60; (and &#x60;FlowsheetV2TrackEntry.artist_id&#x60;), so on-device For You matching can intersect it against liked-artist ids in one id space. */
public struct SimilarArtist: Sendable, Codable, Hashable {

    /** WXYC catalog artist id, same keyspace as `Concert.headlining_artist_id`. */
    public var artistId: Int
    /** semantic-index affinity score, used for client-side ranking and the similar-tier noise cap. Higher is closer. */
    public var weight: Double

    public init(artistId: Int, weight: Double) {
        self.artistId = artistId
        self.weight = weight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artistId = "artist_id"
        case weight
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artistId, forKey: .artistId)
        try container.encode(weight, forKey: .weight)
    }
}

