//
// SongLikeDelta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** One increment or decrement to a song&#39;s public like tally. Carries the song&#39;s identity and nothing whatsoever about who liked it — see &#x60;POST /likes/tally&#x60; for why no listener key exists anywhere in this contract. */
public struct SongLikeDelta: Sendable, Codable, Hashable {

    public enum Delta: Int, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case number1 = -1
        case _1 = 1
        case unknownDefaultOpenApi = 11184809
    }
    /** The client's folded identity for the song: `SongKey.fold` applied to artist and title, joined with `|` (case-, diacritic-, and width-insensitive, whitespace collapsed). The server stores this verbatim as the tally's key and MUST NOT recompute it — the client's fold is authoritative for song identity. Album is deliberately excluded from the key, so a single, an LP cut, and a free-text replay all tally together. */
    public var songKey: String
    /** Raw, unfolded song title, exactly as displayed on-device. */
    public var songTitle: String
    /** Raw, unfolded artist name, exactly as displayed on-device — NOT the folded value baked into `song_key`. The server folds this itself with its own `fold_artist_name` (NFD, strip combining diacritics, lowercase — no width folding, no whitespace collapsing; the twin of the SQL `wxyc_schema.fold_artist_name`) to attempt a catalog match when `artist_id` is absent. The client's fold and the server's fold are deliberately different functions and are never required to agree: width-variant or multi-space artist names may match under one and miss under the other. This field exists for that best-effort match, not for identity — `song_key` alone owns that. */
    public var artistName: String
    /** Album/release title, when the like has one. Optional: standalone tracks and some free-text plays carry no matched release. */
    public var releaseTitle: String?
    /** WXYC catalog artist id, when already resolved on-device (e.g. healed from a V2 flowsheet play). Optional and absent for name-only likes sourced from the V1 API or free-text plays; the server then falls back to matching `artist_name` via its own fold, leaving the artist unresolved — never failing the write — on a miss. */
    public var artistId: Int?
    /** `1` when the listener liked the song, `-1` when they unliked it. The server clamps the resulting tally at zero: deltas are fire-and-forget and lossy by design, so a `-1` can arrive without its matching `1`. */
    public var delta: Delta

    public init(songKey: String, songTitle: String, artistName: String, releaseTitle: String? = nil, artistId: Int? = nil, delta: Delta) {
        self.songKey = songKey
        self.songTitle = songTitle
        self.artistName = artistName
        self.releaseTitle = releaseTitle
        self.artistId = artistId
        self.delta = delta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case songKey = "song_key"
        case songTitle = "song_title"
        case artistName = "artist_name"
        case releaseTitle = "release_title"
        case artistId = "artist_id"
        case delta
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(songKey, forKey: .songKey)
        try container.encode(songTitle, forKey: .songTitle)
        try container.encode(artistName, forKey: .artistName)
        try container.encodeIfPresent(releaseTitle, forKey: .releaseTitle)
        try container.encodeIfPresent(artistId, forKey: .artistId)
        try container.encode(delta, forKey: .delta)
    }
}


extension SongLikeDelta: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if delta == .unknownDefaultOpenApi { return true }
        return false
    }
}
