//
// SongLikeTallyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response body for &#x60;POST /likes/tally&#x60;. */
public struct SongLikeTallyResponse: Sendable, Codable, Hashable {

    /** Number of deltas applied to the tallies. */
    public var applied: Int
    /** Of `applied`, how many carried or matched a WXYC catalog artist id. Diagnostic only: it describes catalog coverage, not the caller. */
    public var resolved: Int

    public init(applied: Int, resolved: Int) {
        self.applied = applied
        self.resolved = resolved
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case applied
        case resolved
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(applied, forKey: .applied)
        try container.encode(resolved, forKey: .resolved)
    }
}

