//
// SongLikeTallyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request body for &#x60;POST /likes/tally&#x60;. A batch of independent counter deltas — NOT a snapshot of anyone&#39;s library, and not an event log that could be reassembled into one. */
public struct SongLikeTallyRequest: Sendable, Codable, Hashable {

    public static let deltasRule = ArrayRule(minItems: 1, maxItems: 1000, uniqueItems: false)
    /** One or more deltas, at most 1000. Order carries no meaning. A client normally sends a single delta per toggle; the array exists so a client adopting the feature can submit the likes already on the device in one request. A device holding more than 1000 likes chunks them across requests — there is no cross-request continuity to preserve, since each delta is independent and the endpoint holds no per-caller state. */
    public var deltas: [SongLikeDelta]

    public init(deltas: [SongLikeDelta]) {
        self.deltas = deltas
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deltas
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deltas, forKey: .deltas)
    }
}

