//
// SpecialtyShow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SpecialtyShow: Sendable, Codable, Hashable {

    public var id: Int
    public var specialtyName: String
    public var description: String?

    public init(id: Int, specialtyName: String, description: String? = nil) {
        self.id = id
        self.specialtyName = specialtyName
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case specialtyName = "specialty_name"
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(specialtyName, forKey: .specialtyName)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

