//
// StreamingCheckRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StreamingCheckRequest: Sendable, Codable, Hashable {

    /** Artist name to search for */
    public var artist: String
    /** Album title to search for */
    public var title: String

    public init(artist: String, title: String) {
        self.artist = artist
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artist
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artist, forKey: .artist)
        try container.encode(title, forKey: .title)
    }
}

