//
// StreamingResolution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Per-service streaming resolution status for one lookup result, keyed by streaming service (keys match the &#x60;*_url&#x60; prefixes on &#x60;DiscogsMatchResult&#x60;). A service&#39;s key is PRESENT only when that service was consulted during this lookup; an omitted service was never probed and must NOT be treated as &#x60;absent&#x60; (the never-consulted state — key omission is its sole encoding, so a consumer has one rule, not two). Additive and independent of the &#x60;*_url&#x60; fields: it annotates why a &#x60;*_url&#x60; is null (transient &#x60;unresolved&#x60; vs terminal &#x60;absent&#x60;) without changing the meaning of the url fields themselves. Mirrors the per-service shape of &#x60;StreamingCheckSources&#x60; (LML#376), except a consulted-but-absent service is the explicit &#x60;absent&#x60; verdict rather than a null, so these per-service fields are non-nullable. Covers the services with a genuine probe/absence distinction on the lookup path (&#x60;spotify&#x60;, &#x60;apple_music&#x60;, &#x60;bandcamp&#x60;); YouTube Music and SoundCloud are search-URL-only and carry no resolution verdict.  */
public struct StreamingResolution: Sendable, Codable, Hashable {

    public var spotify: StreamingResolutionStatus?
    public var appleMusic: StreamingResolutionStatus?
    public var bandcamp: StreamingResolutionStatus?

    public init(spotify: StreamingResolutionStatus? = nil, appleMusic: StreamingResolutionStatus? = nil, bandcamp: StreamingResolutionStatus? = nil) {
        self.spotify = spotify
        self.appleMusic = appleMusic
        self.bandcamp = bandcamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case spotify
        case appleMusic = "apple_music"
        case bandcamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(spotify, forKey: .spotify)
        try container.encodeIfPresent(appleMusic, forKey: .appleMusic)
        try container.encodeIfPresent(bandcamp, forKey: .bandcamp)
    }
}


extension StreamingResolution: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if spotify == .unknownDefaultOpenApi { return true }
        if appleMusic == .unknownDefaultOpenApi { return true }
        if bandcamp == .unknownDefaultOpenApi { return true }
        return false
    }
}
