//
// StreamingSourceMatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A match found on a single streaming service. */
public struct StreamingSourceMatch: Sendable, Codable, Hashable {

    /** URL to the matched album on the service */
    public var url: String
    /** Match confidence score (0-100) */
    public var confidence: Double

    public init(url: String, confidence: Double) {
        self.url = url
        self.confidence = confidence
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case confidence
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(confidence, forKey: .confidence)
    }
}

