//
// StreamingCheckSources.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Per-service streaming match results. */
public struct StreamingCheckSources: Sendable, Codable, Hashable {

    public var spotify: StreamingSourceMatch?
    public var deezer: StreamingSourceMatch?
    public var appleMusic: StreamingSourceMatch?
    public var bandcamp: StreamingSourceMatch?

    public init(spotify: StreamingSourceMatch? = nil, deezer: StreamingSourceMatch? = nil, appleMusic: StreamingSourceMatch? = nil, bandcamp: StreamingSourceMatch? = nil) {
        self.spotify = spotify
        self.deezer = deezer
        self.appleMusic = appleMusic
        self.bandcamp = bandcamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case spotify
        case deezer
        case appleMusic = "apple_music"
        case bandcamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(spotify, forKey: .spotify)
        try container.encodeIfPresent(deezer, forKey: .deezer)
        try container.encodeIfPresent(appleMusic, forKey: .appleMusic)
        try container.encodeIfPresent(bandcamp, forKey: .bandcamp)
    }
}

