//
// TrackSearchResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrackSearchResult: Sendable, Codable, Hashable {

    public enum Source: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case discogs = "discogs"
        case flowsheet = "flowsheet"
        case bin = "bin"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var trackId: Int?
    public var title: String
    public var position: String?
    public var duration: String?
    public var albumId: Int?
    public var albumTitle: String
    public var artistName: String
    public var label: String?
    public var rotationId: Int?
    public var rotationBin: RotationBin?
    public var source: Source

    public init(trackId: Int? = nil, title: String, position: String? = nil, duration: String? = nil, albumId: Int? = nil, albumTitle: String, artistName: String, label: String? = nil, rotationId: Int? = nil, rotationBin: RotationBin? = nil, source: Source) {
        self.trackId = trackId
        self.title = title
        self.position = position
        self.duration = duration
        self.albumId = albumId
        self.albumTitle = albumTitle
        self.artistName = artistName
        self.label = label
        self.rotationId = rotationId
        self.rotationBin = rotationBin
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case trackId = "track_id"
        case title
        case position
        case duration
        case albumId = "album_id"
        case albumTitle = "album_title"
        case artistName = "artist_name"
        case label
        case rotationId = "rotation_id"
        case rotationBin = "rotation_bin"
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(trackId, forKey: .trackId)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(position, forKey: .position)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(albumId, forKey: .albumId)
        try container.encode(albumTitle, forKey: .albumTitle)
        try container.encode(artistName, forKey: .artistName)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(rotationId, forKey: .rotationId)
        try container.encodeIfPresent(rotationBin, forKey: .rotationBin)
        try container.encode(source, forKey: .source)
    }
}


extension TrackSearchResult: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if rotationBin == .unknownDefaultOpenApi { return true }
        if source == .unknownDefaultOpenApi { return true }
        return false
    }
}
