//
// TrackMatchSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Provenance of a TrackMatchHint. &#x60;cta&#x60; indicates Backend&#39;s local &#x60;compilation_track_artist&#x60; lookup (Track 1, BS-local). &#x60;discogs_release&#x60; indicates LML matched via a Discogs release_id (Track 2; pre-cross-cache-identity, this is a direct CEI release-format hit; post-cross-cache-identity, it&#39;s a &#x60;library_identity.discogs_release_id&#x60; hit). &#x60;discogs_master&#x60; indicates LML matched via a Discogs master_id (Track 2; the more common pre-cross-cache-identity path, since ~90% of CEI rows are master-format). &#x60;library_identity&#x60; indicates an explicit substrate match — emitted post-cross-cache-identity when LML&#39;s pipeline exposes the distinction in its response.  */
public enum TrackMatchSource: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case cta = "cta"
    case discogsRelease = "discogs_release"
    case discogsMaster = "discogs_master"
    case libraryIdentity = "library_identity"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension TrackMatchSource: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
