//
// TrackMatchHint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Populated on library search / lookup result items when a track-title match drove the inclusion of this release into the results. The &#x60;source&#x60; field distinguishes the underlying match pathway so consumers can render appropriate UX (e.g., qualitative \&quot;matched via Discogs (verified)\&quot; tooltips) and downstream audits can break coverage down by source.  */
public struct TrackMatchHint: Sendable, Codable, Hashable {

    public static let confidenceRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 1, exclusiveMaximum: false, multipleOf: nil)
    /** The track title as stored in the source. */
    public var title: String
    /** Per-track artist credit (for compilations, where each track may credit a distinct artist). Null for non-comp tracks where the release-level artist applies.  */
    public var artistCredit: String?
    /** Track position on the release as stored in the source (e.g., \"A1\", \"B2\", \"5\"). String-typed to match Discogs's `release_track.position` shape, which uses vinyl-side notation for LP releases. Null when position is unknown or inapplicable (e.g., CTA-derived matches, since `compilation_track_artist` has no position column).  */
    public var position: String?
    /** Confidence score for the underlying identity match. Sourced from `library_identity.confidence` post-cross-cache-identity, from `canonical_entity_confidence` pre-cross-cache-identity, or fixed at 1.0 for `cta`-source hits (the curated VA-disambiguation data is treated as authoritative). Used by the UI to render qualitative tooltips on the chip; consumers should not assume null for `cta` source.  */
    public var confidence: Double?
    public var source: TrackMatchSource

    public init(title: String, artistCredit: String? = nil, position: String? = nil, confidence: Double? = nil, source: TrackMatchSource) {
        self.title = title
        self.artistCredit = artistCredit
        self.position = position
        self.confidence = confidence
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case artistCredit = "artist_credit"
        case position
        case confidence
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(artistCredit, forKey: .artistCredit)
        try container.encodeIfPresent(position, forKey: .position)
        try container.encodeIfPresent(confidence, forKey: .confidence)
        try container.encode(source, forKey: .source)
    }
}


extension TrackMatchHint: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if source == .unknownDefaultOpenApi { return true }
        return false
    }
}
