//
// TrackSearchParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrackSearchParams: Sendable, Codable, Hashable {

    public var song: String
    public var artist: String?
    public var album: String?
    public var label: String?
    public var n: Int?

    public init(song: String, artist: String? = nil, album: String? = nil, label: String? = nil, n: Int? = nil) {
        self.song = song
        self.artist = artist
        self.album = album
        self.label = label
        self.n = n
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case song
        case artist
        case album
        case label
        case n
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(song, forKey: .song)
        try container.encodeIfPresent(artist, forKey: .artist)
        try container.encodeIfPresent(album, forKey: .album)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(n, forKey: .n)
    }
}

