//
// V2FlowsheetLatestGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum V2FlowsheetLatestGet200Response: Sendable, Codable, Hashable {
    case typeFlowsheetV2BreakpointEntry(FlowsheetV2BreakpointEntry)
    case typeFlowsheetV2DJJoinEntry(FlowsheetV2DJJoinEntry)
    case typeFlowsheetV2DJLeaveEntry(FlowsheetV2DJLeaveEntry)
    case typeFlowsheetV2MessageEntry(FlowsheetV2MessageEntry)
    case typeFlowsheetV2ShowEndEntry(FlowsheetV2ShowEndEntry)
    case typeFlowsheetV2ShowStartEntry(FlowsheetV2ShowStartEntry)
    case typeFlowsheetV2TalksetEntry(FlowsheetV2TalksetEntry)
    case typeFlowsheetV2TrackEntry(FlowsheetV2TrackEntry)
    case unknownDefaultOpenApi

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeFlowsheetV2BreakpointEntry(let value):
            try container.encode(value)
        case .typeFlowsheetV2DJJoinEntry(let value):
            try container.encode(value)
        case .typeFlowsheetV2DJLeaveEntry(let value):
            try container.encode(value)
        case .typeFlowsheetV2MessageEntry(let value):
            try container.encode(value)
        case .typeFlowsheetV2ShowEndEntry(let value):
            try container.encode(value)
        case .typeFlowsheetV2ShowStartEntry(let value):
            try container.encode(value)
        case .typeFlowsheetV2TalksetEntry(let value):
            try container.encode(value)
        case .typeFlowsheetV2TrackEntry(let value):
            try container.encode(value)
        case .unknownDefaultOpenApi:
            try container.encodeNil()
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case entryType = "entry_type"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .entryType)

        switch discriminatorValue {
        case "breakpoint":
            self = .typeFlowsheetV2BreakpointEntry(try FlowsheetV2BreakpointEntry(from: decoder))
        case "dj_join":
            self = .typeFlowsheetV2DJJoinEntry(try FlowsheetV2DJJoinEntry(from: decoder))
        case "dj_leave":
            self = .typeFlowsheetV2DJLeaveEntry(try FlowsheetV2DJLeaveEntry(from: decoder))
        case "message":
            self = .typeFlowsheetV2MessageEntry(try FlowsheetV2MessageEntry(from: decoder))
        case "show_end":
            self = .typeFlowsheetV2ShowEndEntry(try FlowsheetV2ShowEndEntry(from: decoder))
        case "show_start":
            self = .typeFlowsheetV2ShowStartEntry(try FlowsheetV2ShowStartEntry(from: decoder))
        case "talkset":
            self = .typeFlowsheetV2TalksetEntry(try FlowsheetV2TalksetEntry(from: decoder))
        case "track":
            self = .typeFlowsheetV2TrackEntry(try FlowsheetV2TrackEntry(from: decoder))
        default:
            self = .unknownDefaultOpenApi
        }
    }
}

