//
// WxycReviewItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WxycReviewItem: Sendable, Codable, Hashable {

    /** The DJ review body */
    public var review: String
    /** Reviewer-written artist background, when provided */
    public var artistBlurb: String?
    /** Raw recommended-tracks text, including the form's \"!\"-rating notation */
    public var recommendedTracks: String?
    /** Comma-separated descriptors chosen by the reviewer */
    public var buzzwords: String?
    /** Form submission date when available (e.g. \"2024-03-15\") */
    public var submittedDate: String?

    public init(review: String, artistBlurb: String? = nil, recommendedTracks: String? = nil, buzzwords: String? = nil, submittedDate: String? = nil) {
        self.review = review
        self.artistBlurb = artistBlurb
        self.recommendedTracks = recommendedTracks
        self.buzzwords = buzzwords
        self.submittedDate = submittedDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case review
        case artistBlurb
        case recommendedTracks
        case buzzwords
        case submittedDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(review, forKey: .review)
        try container.encodeIfPresent(artistBlurb, forKey: .artistBlurb)
        try container.encodeIfPresent(recommendedTracks, forKey: .recommendedTracks)
        try container.encodeIfPresent(buzzwords, forKey: .buzzwords)
        try container.encodeIfPresent(submittedDate, forKey: .submittedDate)
    }
}

